### ISSUE TITLE
Question: ons-toolbar box-shadow

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#1009]
Hey Guys, I would like to add a constant box-shadow at the bottom of the ons-toolbar, just to get some visual divider between the content and the toolbar. But somehow if I push/pop a page I will also see a box-shadow and/or border which is probably added for the animation. Can you tell me how I can get rid of it without touching your code?
Thanks a lot and keep up your good work!

P.s a cool idea would be if you could add a box-shadow to the toolbar if a user is scrolling and not at the top of the page

**Comment by argelius** [comment]
Hi @d3orn !

We have added a material toolbar with a shadow. We will make it react to scroll since that is the native behaviour. Unfortunately that can't be done in pure CSS so we need to do it with JavaScript.

About your problem. The thing your seeing is probably the semi-transparent mask making the shadow darker than it usually is.

Try using the `simpleslide` animation instead for an animation without a mask. Unfortunately there is no easy way to hide the mask since it doesn't have a class name so we can't hide it with CSS.
