### ISSUE TITLE
Feature request: Datepicker / Timepicker

### ISSUE THREAD

**Issue by boustanihani** [OnsenUI/OnsenUI#1036]
Hi, are there any plans of offering a Datepicker / Timepicker ?

**Comment by frankdiox** [comment]
Hello @boustanihani ! Currently there are no plans for a Datepicker, unfortunately. We are focusing on improving Onsen UI main components to have a robust framework and enhance user experience. Since you can find many datepickers for jQuery, Angular or any other framework you choose, implementing one in Onsen UI is not a priority right now.

But as always, this is open source so if we receive a PR from the community we will love to review it :)

**Comment by asial-matagawa** [comment]
This issue was superseded by #1479.

Closing this.
