### ISSUE TITLE
<ons-sliding-menu> don't work 

### ISSUE THREAD

**Issue by PhilTheNet** [OnsenUI/OnsenUI#1077]
Hello,
The sample <ons-sliding-menu>  (https://onsen.io/reference/ons-sliding-menu.html) don't work in WindowsEmulator & device with the "Onsen UI Templates for Visual Studio 2015"
It's a known issue ?
(No problem with android and ios)
Error on javascript console : 
CSS3111: @font-face encountered unknown error.
fontawesome-webfont.eot & ionicons.eot

Thanks

**Comment by frankdiox** [comment]
@PhilTheNet Thanks for reporting! Are you using Universal Applications or WP8? It should work in Universal Apps, if not we have to fix it. With WP8 there were some security issues with icons.

**Comment by PhilTheNet** [comment]
Universal Apps & WP8
However the template Onsen UI Sliding Menu for VisualStudio 2015 work fine, I do not see where is the structural difference...
Thanks

**Comment by frankdiox** [comment]
@PhilTheNet I have found some information about that error here: http://www.marinbezhanov.com/web-development/16/how-to-embed-webfonts-properly-and-how-to-solve-the-ambiguous-css3111-font-face-encountered-unknown-error/

It is just related to the fonts in IE. Since it is working with the real Sliding Menu template for VS2015 I think we don't need to worry about this. Closing this for now, ping if you need anything else.
