### ISSUE TITLE
Ons-Tabbar

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#1109]
I have a ons-tabbar with animation = slide
I can click on a tab multiple times even if it is already the active tab. Doing so restarts the slide animation. This is probably a bug. I think the click handler should be disabled if a tab is active.

EDIT: Love Onsen 2.0 and I hope my bug reports help you!

**Comment by argelius** [comment]
This looks like a bug. We will take a look.

@d3orn Your bug reports are highly appreciated! Keep them coming :)

**Comment by frankdiox** [comment]
@d3orn Thanks for the report! Right now you can use `no-reload` attribute to skip reloading page and animation. If you still want to reload the page on click without animation you can do it on `reactive` event.

We will change this to make `no-reload` the default behavior since seems more logic for mobile apps.
