### ISSUE TITLE
Make ons-list-item's border to real iOS style.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1133]
![image](https://cloud.githubusercontent.com/assets/59784/11866896/2cb6e3ac-a4f1-11e5-97a4-43f8573edf8e.png)
![image](https://cloud.githubusercontent.com/assets/59784/11866945/7abfb07e-a4f1-11e5-9849-42e22e08bd29.png)

**Comment by frankdiox** [comment]
@anatoo I think @argelius implemented something similar for material design in #1105 . It is probably the same but just changing margins and paddings.

**Comment by argelius** [comment]
I will do this! :)

**Comment by themikem** [comment]
Is it possible to get an optional style which will keep the non-indented look (a la Onsen1) as well?  For some app designs, leaving off the indent looks better, especially when using an inset list.  I can post screenshots if needed, but I'd like to have the option here without having to write a custom class or override the built-in style every time.

**Comment by frankdiox** [comment]
@themikem  I think you are looking for `modifier="longdivider"`.

**Comment by themikem** [comment]
@frankdiox Indeed.  Thank you! That does solve it.

I will say that it would be nice to set up a simple list with just UL and LI tags.  As it stands, even with this style, I have to include a DIV on each element to get the left indent on the items.  For simple cases (say a tappable list of 3-5 text items with chevrons, for example), this seems like a bit of overkill.  It'd be nice to have the base indent in the list__item padding and then work the left/center/right styles off of that.  Just a thought.

**Comment by frankdiox** [comment]
@themikem I'm not sure what you mean, I can see "indentation" without specifying any extra div: http://codepen.io/frankdiox/pen/Mypapv

What's the behavior you'd expect?

**Comment by themikem** [comment]
The code in your pen is generating the div's.  If you view the compiled code:
```
<ons-list class="list" _compiled="">
<ons-list-header class="list__header" _compiled="">Items without divs</ons-list-header>
<ons-list-item class="list__item" _compiled="" style="transition: background-color 0s linear 0.15s; -webkit-transition: background-color 0s linear 0.15s;">
<div class="center list__item__center">Ichi</div>
</ons-list-item>
<ons-list-item class="list__item" _compiled="">
<div class="center list__item__center">Ni</div>
</ons-list-item>
<ons-list-item class="list__item" _compiled="">
<div class="center list__item__center">San</div>
</ons-list-item>
<ons-list-item class="list__item" _compiled="">
<div class="center list__item__center">Yon</div>
</ons-list-item>
<ons-list-item class="list__item" _compiled="">
<div class="center list__item__center">Go</div>
</ons-list-item>
</ons-list>
```

However, if I just make a simple list using ul/li tags, I find that the text in the list items is flush against the left side of the list:
http://codepen.io/themikem/pen/XdMmxP/

The behavior I expect is this:
http://codepen.io/themikem/pen/oxZjar/
(notice that the HTML code is a direct cut & paste from the prior pen - I just swapped the script/stylesheet tags)

Specifically, notice that the list item content is indented with a 10px margin on the left side.

Also, while I was building those pens, I noticed that if I do an inset list without a header, I get a double-border at the top due to the shadow from the `.list__item:first-child` style.  Just an FYI, looks a bit odd.

So maybe I'm expecting a bit much in terms of backwards compatibility, but I was expecting the old ul/li code to appear the same with onsen2.  I don't mind the longborder mod, and I think the left/center/right structure is a superior approach to onsen1.  It is also more consistent with the toolbar pattern, which is a good thing in this library.  I'd just like the simple case to work without having to think about the more advanced structure.

**Comment by themikem** [comment]
Just to complete the thought, my suggestions for a potential fix: http://codepen.io/themikem/pen/xVqwoe

- indentation is backwards compatible
- header vertical spacing also backwards compatible
- extended left/center concept to the header (for example, if you wanted to put icons in header rows for a settings page with category headers)

**Comment by frankdiox** [comment]
@themikem Oh! Now I see what you mean, you were speaking about the CSS only version without using the web components. Of course the components will create divs internally to fit the CSS.
We will probably add this and try to fix the header border problem, thanks! :)

**Comment by themikem** [comment]
Okay, sounds good.  Thanks for looking at this.  Let me know if you'd like a patch or pull request for the fixes. (happy to do it if it would help)

**Comment by argelius** [comment]
@themikem @frankdiox 

I agree that we should add padding on the left for lists without the inner divs. There is no way we can add the short borders in this case but you can get long borders using `longdivider` modifier.

We will fix this before releasing the next beta.

Expanding the left, right, center concept to the headers also sounds good but will probably not happen in this version.

The top padding on the headers should default to something that looks like list headers in native apps. In the case you want to change it I think it's better to set it manually since Onsen UI can't anticipate what everyone needs.

**Comment by argelius** [comment]
@themikem 

To use the inset list you need to also tell the items that the list is inset:

```
<div class="list list--inset">
  <div class="list__item list--inset__item">Item</div>
</div>
```

If you define it like this there will be no double border.

**Comment by themikem** [comment]
@argelius 

On the header: you're point is well taken.  That's what I'm trying to achieve.  There are two "headers" in iOS natively: the header at the top of the list, and a category divider between list items.

For example, look at the image below from the Settings app (region settings):
![2016-03-22 08 23 04](https://cloud.githubusercontent.com/assets/5784219/13953073/f7a39edc-f007-11e5-8008-4c3d183ac95b.png)

So my point with the example is that if you include the header between items, the height offset needs to be reduced to match the native behavior.  That was the point of my pen example.

Inset lists & border:
Rather than including the inset tag on each element, since the first is the only offending element anyway, could this be made as an inherited style from list--inset?  Something like:
```
.list--inset .list--inset__item {
-webkit-box-shadow: none;
box-shadow: none;
}

Seem easier than having to put that style on all the elements, or putting it just on the first.  Also, the tag insets the list as a whole.  It would be preferable not to have the items need to know whether or not they are inset.

Thanks again.

**Comment by argelius** [comment]
@themikem Making the `inset` modifier only apply to the list is a good idea. We will consider this. Only problem is the header on the top of the first item so it might be overkill to require `list--inset__item` on all items.

For the headers in your example they are quite different from the normal list headers so I think it might be a better idea to implement them as a separate class.

**Comment by themikem** [comment]
@argelius Yes, the inset__item tag really is overkill, and if you look at the pen I posted, it can easily be solved using either a first-child or just style id combo.

On the headers, there again we have a departure from the expected behavior with Onsen 1 vs Onsen 2.  Notice that with Onsen 1, the header element behaves in the same manner as the native OS screenshot I posted.  It is a shorter-than-item "divider" of sorts that could be used to break up groups in a list view, for example:
http://codepen.io/themikem/pen/BKZPwE

To your point, the header in Onsen2 is more appropriate/better matches the native look when two list blocks appear one after another.  Using the same HTML from the Onsen1 example here: http://codepen.io/themikem/pen/WwpQqZ

However, using the header within the list here does not match the native look at all.  That was my point with my earlier post.  

Perhaps this is a candidate for two separate styles?  A "header" style for the top of the list, and a "divider" style that matches Onsen1 for between elements.  It could also be implemented with modifiers similar to my other suggestion.  Or, could still be done using a single style, but with a secondary modifier for a list title.  One thought: http://codepen.io/themikem/pen/xVqwoe

At any rate, there is an issue here, but I think it is slightly more complicated to resolve.
