### ISSUE TITLE
Manually added $templateCache doesn't work with onsNavigator nor with onsTabbar in 2.0

### ISSUE THREAD

**Issue by cither1** [OnsenUI/OnsenUI#1209]
related issue: #1174

Templates manually added to `$templateCache` don't work with `onsNavigator` nor with `onsTabbar`, although they work fine with `onsSlidingMenu`.

`onsNavigator` : https://jsfiddle.net/0bs5anv2/5/
It doesn't work. The navigator tries to load `home.html` over xhr and results in an error.

`onsSlidingMenu` : https://jsfiddle.net/tzo81exd/1/
It works. 

If I use `ng-template` or `ons-template` they all work fine. However, I want to bundle templates into one js file using angular. Any solution for this?

**Comment by leocaseiro** [comment]
Same issue for me!

I have some plunker to show what I meant.

Working ons-navigation without $templateCache
http://plnkr.co/edit/wnJn2WqIbbSGGNzob4YC?p=preview

Working with $templateCache and ng-include
http://plnkr.co/edit/8GpkSVl5Ywg6YoXfarh3?p=preview

Not working with $templateCache and ons-navigation
http://plnkr.co/edit/1b4awWKUr8ovmFzGv2j3?p=preview

PS: On OnsenUI1 it used to work normally.

**Comment by cskiwi** [comment]
Is there any ETA on this?
Having the same issue

**Comment by IliaSky** [comment]
Hi @cskiwi, and sorry @leocaseiro and @cither1 for the late answer:

This one's on us. It seems we forgot to remap some methods. Generally the way we try to make the bindings work is wrap the initial logic, but keep the old one safe. Here I guess that may not be an option since `$templateCache` is for angular and there is no way for the core to try to access it. `sliding-menu` was working because it's an angular-only component. 

We will probably fix this relatively soon, but until then there's an easy patch to make everything work fine:

    angular.module('app').run(function($templateCache, $onsen, $onsGlobal) {
      $onsGlobal._internal.getPageHTMLAsync = $onsen.getPageHTMLAsync;
      $templateCache.put('home.html', '<h1>Home2.html</h1>');
    });

It's hacky and we should be the ones doing this,  but for now this can help you in your current project.
