### ISSUE TITLE
ons-splitter-side page attribute error

### ISSUE THREAD

**Issue by AlexF12004Roma** [OnsenUI/OnsenUI#1212]
Hello,

I'm developing a new Mobile app with onsenUI 2.

I got an error on ons-splitter.
If i put the attribute page in ons-splitter-side i got an error in javascript (both template id and page url) :
ons.getPageHTMLAsync property not supported.
I have to put html code inside side tag side and all is ok.

The page attribute in ons-splitter-content instead works well.

I'm using onsenui2+angular.

**Comment by argelius** [comment]
Hi @AlexF12004Roma !

Can you please paste the code that triggers this error?

**Comment by rafaelptr** [comment]
I'm getting the same error
When do this
code (not working):
`<ons-splitter>`
`<ons-splitter-side page="pages/menu.html" var="menu" side="left" width="300px" collapse swipeable>`
`</ons-splitter-side>`
 `<ons-splitter-content page="pages/hello.html"></ons-splitter-content>`
`</ons-splitter>`
Instead of this (Works fine):
`<ons-splitter>`
`<ons-splitter-side page="pages/menu.html" var="menu" side="left" width="300px" collapse swipeable>`
		    `<ons-page modifier="material">`
`			  <ons-list modifier="material" >`
`			    <ons-list-header modifier="material" >`
`				   Hello`
`			    </ons-list-header>`
`			  </ons-list>`
`			</ons-page>`
`	    </ons-splitter-side>`
 `  		<ons-splitter-content page="pages/hello.html"></ons-splitter-content>`
`  	</ons-splitter>`


reference js 
onsenui.min.js:15 Uncaught TypeError: ons.getPageHTMLAsync is not a function

**Comment by IliaSky** [comment]
Thank you for the bug report. The bug should be fixed in beta 8.

Here is an [working example](http://codepen.io/IliaSky/pen/qZXXQv?editors=1000) of what you want to do using beta 8. 

Also note that in the case when the `page` attribute is a valid page Onsen will put that page instead of whatever content you have inside the `ons-splitter-side` - that means that if it finds the page then your content inside your second example will be replaced with the page (just so you know).

__Side note:__ I can see that you really tried to put the html inside a proper code tag with indentation - instead of having a single \` backtick at the start and end of each line you can wrap the whole thing with triple \`\`\` backticks. Alternatively if you just put an empty line and then indent the code by 4 spaces you should get the same result. ^_^
