### ISSUE TITLE
Material design is badly displayed on Android 4.1.2

### ISSUE THREAD

**Issue by elbidone** [OnsenUI/OnsenUI#1227]
I've tested material design on Android 4.1.2, it raised very bad results. When I scroll I see following screens on onsenui2-quickstart pages:

Tested on Android 4.1.2 
![screenshot_2016-02-12-12-37-59](https://cloud.githubusercontent.com/assets/9011612/13017625/41fb283a-d1ac-11e5-8d86-521136ff38b9.png)
![screenshot_2016-02-12-12-38-42](https://cloud.githubusercontent.com/assets/9011612/13017626/41fb3546-d1ac-11e5-8119-892e80904f61.png)

My configuration is:
```
  "devDependencies": {
    "onsenui": "2.0.0-beta.5",
    "react": "~0.14.2",
    "angular": "~1.4.8"
  }
```

**Comment by argelius** [comment]
@IliaSky Can you take a look at this when you have time?

**Comment by IliaSky** [comment]
ok

**Comment by IliaSky** [comment]
The source seems to be the `transform: translate3d` - I guess scrolling hardware accelerated elements does not yield good results in earlier versions of Android. This behaviour would still persist even in the newest beta version. Since we don't seem to be taking advantage of it here maybe we can remove it for `ons-list-item`?
What do you think @argelius ?

**Comment by DILEEP-YADAV** [comment]
same issue , I was post to forum.......

**Comment by IliaSky** [comment]
It has been fixed on another branch. The fix will probably be merged and available in either beta 7 or beta 8.
