### ISSUE TITLE
CSS Switch is broken

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1228]
The switch element doesn't work anymore. It only works when using the `<ons-switch>` element but the CSS should work independent of the JavaScript.

Also, `checked` and `disabled` attributes stopped working.

@IliaSky Can you fix this on Monday?

**Comment by IliaSky** [comment]
ok

**Comment by IliaSky** [comment]
Actually it wasn't working simply because the css had changed so that it cared about the properties of the ons-switch element itself rather than the inside input. With the ons-switch element the checked and disabled properties were synced between the two elements. Semantically this made more sense. I didn't think of the option of using only the css classes without the ons-switch element. It feels kinda strange to have two ways to do the same thing. Also there is no way to make the element draggable with css only, so I guess now we have 2 things which are almost identical but one is draggable and the other one isn't. We may want to rethink our strategy imo.

I changed the css back so that it depends on the input. The issues should be gone after the merge.

**Comment by argelius** [comment]
Thanks @IliaSky !

Actually the reason why we want the CSS to be usable without the JS library is that it can be used independently. There are users that only use the CSS and write all the JS themselves and we want them to be able to do that.

This makes sense because the JS is dependent on the CSS, but if the CSS is dependent on the JS we would get a mutual dependency.
