### ISSUE TITLE
<ons-lazy-repeat> broken

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1251]
This element is currently broken. 

To reproduce the bug run the demo in the `examples` directory. It looks like it breaks the compilation of the list items, which probably means that it breaks compilation of most items.

**Comment by IliaSky** [comment]
It was actually the example that had the problem - this part of the implementation has not been changed since before 10cf22968a7e0864daa672857748472b20d698a7. The thing is since the styles before were for the `ons-list-item` itself (it had the `list__item` class) the fact that it was this way wasn't noticeable.

The list item was being compiled and taken as a template, but afterwards we were changing the compiled item. We could think about if this should be the expected behaviour, but it's been this way for a very long time. It's not broken, but it's just different.
