### ISSUE TITLE
Back (button) support within ons-splitter

### ISSUE THREAD

**Issue by bheijns** [OnsenUI/OnsenUI#1274]
Hi!

Great work on Onsen UI 2!

Is there any support on the back actions within the usage of ons-splitter? Or how do I combine this with the ons-navigator?

Thank you in advance,
Bas

**Comment by frankdiox** [comment]
@bheijns Hello! Sorry for the late reply. The splitter navigation pattern is not directly compatible with back-button since it's not pushing/popping pages. If you want this kind of flow in your app it should be done with a `ons-navigator`. In your case you should the splitter as the parent component and then the navigator as a second component directly inside `ons-splitter-content`. From `ons-splitter-side` you need to call navigator methods for pushing pages instead of splitter's load.

I'd recommend you to write this kind of questions in the [forum](https://community.onsen.io/) since we use Github issues mostly for bug reports.
