### ISSUE TITLE
address bar not disappearing when scrolling

### ISSUE THREAD

**Issue by SayOmgPlz** [OnsenUI/OnsenUI#1282]
Address bar and navigation are not disappearing when we scroll the view.

**Comment by IliaSky** [comment]
Since Onsen UI is expected to be used to make mobile applications, after the application is build there won't be an address bar. So if you plan on making an application you shouldn't worry about that. 

The behaviour is currently that way in order to avoid bugs in iOS. Since our toolbars and tabbars are expected to be fixed on the page and `position: fixed` still isn't properly supported on iOS we're doing some hacks with `position: absolute`. If you are just making a mobile website you have 2 options:

- change some things to `position: fixed` if you don't care about iOS.
- do some tricks on the drag event so that you manage the height of the elements and scrolling.

However since that isn't the main focus of Onsen UI I doubt that we would implement such a feature on our side in the foreseeable future.
