### ISSUE TITLE
Onsen2 and Onsen: Ons-list + fab / position fixed

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#1290]
Hey guys. I was working on a list of people and I added my own FAB on the bottom right of the screen (still working on Onsen1 for this project). Now whenever the user scrolls the list the button scrolls along and is replace at the bottom of the list after the user stopped. First I thought this had to do with my CSS so I tried out Onsen 2 and just added a simple ons-list (with ng-repeat) and at the end of the list a ons-fab exactly the way it is shown on the http://components2.onsen.io/ page.
The same thing happend. I think this has something to do with how list elements are scrolled and I would like to help you fix this if you can point me in a direction.
My first idea was to not use position fixed but us JS to determine the amount the user scrolled and calculate the position.
Cheers and hope to hear from you

Edit: Just tested it on Android and it works like a charm so iOS only

**Comment by d3orn** [comment]
Removing -webkit-overflow-scrolling: touch; form page__content resolves this but makes scrolling terrible on iOS (as expected xD)

**Comment by d3orn** [comment]
I have found a fix for this issue what do you guys think? I can try to implement it into Onsen
https://github.com/attitude/scrollPolyfill.js

**Comment by IliaSky** [comment]
Thank you for the bug report @d3orn 
Since `ons-fab` is part from material design we weren't really expecting people to try and use it in IOS. Therefore we felt safe using `position: fixed` in it's development even though we are aware of the bad IOS implementation. In each other component we actually use `position: absolute` with some tricks.

I was going to suggest that you do the exact same hack if you currently need it for a project.
(Have an absolute positioned container which takes up all the available space and has `overflow: auto` and have the `fab` after the container, again with `position: absolute`). You can see the demo [here](http://codepen.io/IliaSky/pen/wGMOzE) - viewing codepen on a mobile device sometimes is buggy, but the code works fine in a normal project.

I don't think this is generally such a big issue, so I'm not sure we need any additional polyfills, if you want you could try and implement it, but I'm not sure if we would merge it, so it would probably be easier if you just fix it in your own project.

**Comment by d3orn** [comment]
Thanks for the feedback. But what do you do with fabs on iOS? Do you plan to have a special representation for those or just consider them not being used at all? (Which wouldn't make much sense, because a App should run on both platforms) I believe fabs are a very nice design principle and they start to show up on iOS as well (Gmail for example).
Well to be honest I hope all the MD principles show up on iOS soon xD

**Comment by IliaSky** [comment]
We would like that too :)

I guess we will fix this, but it's not completely certain when. It may require some changes to the DOM structure of the page in order to make it work.

Since there is no similar component in IOS flat design I guess we cannot do anything other than just fix them. 

If the user wants he can wrap the `ons-fab` inside an `ons-if[platform="android"]` so that they are shown only on android as shown [here](https://onsen.io/blog/auto-style-app-onsen/).

**Comment by d3orn** [comment]
Nice, I will go with your fix for the time being.

**Comment by 2016lalu** [comment]
Css: -- #fab--add{
              position:fixed;
              bottom:50px;
             right:20px;
         }
Html: --   "<ons-button class="fab" id="fab--add">+</ons-button>"

This code work in android and ios.

**Comment by IliaSky** [comment]
@2016lalu `position: fixed` isn't properly supported in iOS and results in buggy behaviour when scrolling. If you swipe to start scrolling then it scrolls the fixed element and restores it to it's place after the scrolling is finished. This whole issue is about a solution which does not use `position: fixed`.

**Comment by peterchibunna** [comment]
On Android the fab button loses its 'click' event handler when position is fixed.
But when position is absolute, the fab scrolls together with the page and list items.

**Comment by csbok** [comment]
+1
