### ISSUE TITLE
ng-device-backbutton not work with popover

### ISSUE THREAD

**Issue by kountouretis** [OnsenUI/OnsenUI#1299]
i try to hide the popover when the android device back button press but is not work however on other pages the ng-device-backbutton work and control the page as i want. Any suggestions? . Thanks in advance

**Comment by IliaSky** [comment]
Sorry for the late response.

It seems that everything is working as it should except for the fact that probably your popover is created outside your page, making it skip the handler of the page.

I just tested this scenario and it's the only one which I can come up with. It's actually easy to do that because of the implementation of `ons.createPopover`, which you may be using. Otherwise everything seems to work fine.

The fix is just to have the popover as an element of the page. You can reference it by using the `var` attribute. :)

I'll keep this issue open until we actually fix the implementation of `ons.createPopover` so that it can be used in this scenario.

**Comment by asial-matagawa** [comment]
For Onsen UI team:
- If you want to some code for reproducing this bug, see #1210.
