### ISSUE TITLE
input box not showing

### ISSUE THREAD

**Issue by puks** [OnsenUI/OnsenUI#1312]
input box not showing on ONSEN 2.0 beta 7

**Comment by frankdiox** [comment]
I can see `ons-input` without any problem. Please add some more information about your problem.

**Comment by IliaSky** [comment]
@puks - @frankdiox is correct that your issue is not very descriptive. It's best if you provide a little more information when you add an issue.

Still I think I can guess what you mean - probably the input is there but you are just unable to notice it because of the default styles. Currently the default view for all onsen ui components is iOS. The default view for `ons-input` is pretty much seamless, so that it doesn't bother the users. Usually people would use the `ons-input` either with a `label` or at least a placeholder. An input without either of those can be considered bad design and if you have at least one of the two then it wouldn't bother you that it has no border/outline. So basically you can just put a placeholder and you should be able to see it fine. Another option is to add `modifier="underbar"` or `modifier="material"` and then you should be able to notice it again.

If you don't know what fran and I are talking about - `ons-input` is a wrapper around `input` with some custom styles for checkbox and radio etc. If what you're talking about is just the normal `input` tag then probably some of the styles from the custom component propagated to the normal input. We might fix that if that's the case, but if you look at most native applications you will see that they rarely have a style like the one which is the default in the browsers. Therefore I suggest that you try out the `ons-input` element with either of the following two lines:
```html
<ons-input modifier="material"></ons-input>
<ons-input modifier="underbar"></ons-input>
```
or alternatively just add either of these for your simple input 
```html
<input placeholder="test">
<input style="border: 1px solid black">
```

@frankdiox - this issue made me notice that actually the docs for `ons-input` haven't been updated in a while - they're even using the old name. I guess we should update them at some point. (^_^)'

**Comment by claudioc** [comment]
It is maybe also worth mentioning that the pre-beta8 `<ons-material-input>` provided the `label` attribute with which you could have the nice "placeholder raising effect". I don't know how to get the same effect now :)

**Comment by frankdiox** [comment]
@claudioc It's been renamed to `placeholder`, actually. Same effect.

**Comment by claudioc** [comment]
Yes, I tried already `<ons-input modifier="material" placeholder="Select country"></ons-input>`. The placeholder shows in the correct place, but when I focus the field the placeholder doesn't raise. I think I am missing something else (beta9)

**Comment by frankdiox** [comment]
@claudioc Oh! You want it to float? Then add `float` attribute :) . It was the default behavior before but now it requires that attribute.

**Comment by claudioc** [comment]
Amazing! Thanks a lot.

Who need documentation when developers are so reactive? :D
