### ISSUE TITLE
AngularJS binding only

### ISSUE THREAD

**Issue by costa974** [OnsenUI/OnsenUI#1317]
I don't understand this in your docs, when on your website I read:

**jQuery users can also take advantage of Onsen UI’s great UI library.**

I would like to use pure vanilla javascript or jquery.
I don't want to learn another framework like angular to do the same things plain javascript can so

**Comment by munsterlander** [comment]
With Onsen 2.x, they are working on removing all Angular bindings.  You see that in the new components.  All new components work with vanilla JS out of the box and almost all features of all the components now work with vanilla JS.

**Comment by frankdiox** [comment]
@costa974 @munsterlander Onsen 2 core is standalone, it doesn't require AngularJS extension for anything.

It's true that in the docs you can find something like "Only available for AngularJS", but these are just  some extra directives that basically allow OnsenUI to be more suitable for Angular developers. For example, you can handle events with attributes `ons-postpush`, `ons-change`, etc. where you can use Angular $scope directly. Or you can assign a component to a variable with `var` attribute. However, we think that Vanilla JS/ jQuery developers have different ways to achieve the same result without this syntactic sugar. `document.getElementById` instead of using `var` attribute`; `document.addEventListener` instead of attribute handlers, etc.

`ons-if` is a new core component, what means it does not require Angular. For Angular we had `ons-if-platform` and `ons-if-orientation` directives.

I know all of this is a bit confusing, hopefully it will all be clarified when the new docs are released :)

**Comment by munsterlander** [comment]
@frankdiox Thanks for the better explanation than I did.  I completely missed the ons-if-"xxxxx" vs just the ons-if when I was writing earlier.  Either way, vanilla all the way!  Go Onsen Team!

**Comment by costa974** [comment]
Thanks for your answers! I'm not a javascript guy, more a java and c++. I was looking at ionic and angular, but I really don't understand them! I'm getting too old! :) Just to know, is angular faster than plain/vanilla javascript? Because I tried some ionic apps on old hardware like samsung galaxy s2 and it's not the best experience.

http://codecanyon.net/item/ionfullapp-ionic-phonegapcordova-full-hybrid-app/10400343

**Comment by costa974** [comment]
Looking forward for a release candidate.
