### ISSUE TITLE
Beta.8 - Status bar displayed on full screen app upon return [Android]

### ISSUE THREAD

**Issue by munsterlander** [OnsenUI/OnsenUI#1326]
I am using the current beta and have full screen enabled.  On initial app launch, everything works as it is supposed too.  The status bar is hidden and the app takes up all the screen.  If you press the home button or switch apps on an Android device and then come back to the app, the status bar is now displayed which chops off the top portion of your app as it is not reduced in size.

**Comment by IliaSky** [comment]
It seems like it's a bug in cordova. If the app was stared in fullscreen mode then when you resume it it should still be fullscreen, which I guess doesn't seem to be the case.

Therefore in order to fix it we would need some additional property (something like `ons.fullscreen = true`) which you could set and then apply the fix if the property is available, since we cannot actually check if it's in a bugged state.

However since this isn't our bug we don't know when it will be fixed and thus when they fix it on their side Onsen will actually become bugged.

So instead of doing this we can just share a fix, but without including it in Onsen - you can just include it in your fullscreen apps until they fix it.

Probably the issue was introduced recently as there was only one other case which was able to find (Feb 1):
http://stackoverflow.com/questions/35126192/phonegap-android-6-status-bar-overlaps-webview
http://community.phonegap.com/nitobi/topics/android-status-bar-overlaps-webview

By the looks of it the app goes into a bugged fullscreen state in 2 cases:
1. when you do some navigation between apps (your case)
2. when you focus an input (the other guy's case)

In that case you can just manually fix it - something along the lines of:
```javascript
if (ons.platform.isAndroid()) { // maybe some other checks too if it happens only in some android versions
  ons.ready(function(){
    var fix = function () {
      document.body.classList.add('fullscreen-bugfix');
      document.removeEventListener('resume', fix);
      document.removeEventListener('focusin', fix);
    };
    document.addEventListener('resume', fix);
    document.addEventListener('focusin', fix);
  });
}
```
```css
body.fullscreen-bugfix {
  top: 30px;
}

body.fullscreen-bugfix ons-popover {
  margin-top: -30px;
  padding-top: 30px;
}
```
Something like this. However this is just from the top of my head - the same way popover checks the screen sizes maybe there are also other components which could become bugged due to incorrect calculations, but I just cannot recall them right now.

Still maybe just publishing a fullscreen app is just not worth it until they fix the problem @cordova since otherwise you will also need to republish it when they fix it, but that's your choice.
