### ISSUE TITLE
Using binding in ons-modal will cause ons.ready to never become ready only in iOS on Beta.8

### ISSUE THREAD

**Issue by RezaRahmati** [OnsenUI/OnsenUI#1334]
Hi 
I have found an issue in Beta.8, which was not exists in Beta.2.
If you use ons-modal with controller and binding, only in iOS the ons.ready will never happen, (it works fine in android)

```
<ons-modal var="modal" ng-controller="ModalController">
    <ons-progress-circular indeterminate></ons-progress-circular>

    <!--NOT WORKING-->
    <span >{{message}}</span>

    <!--WORKING-->
    <!--<span >Wait...</span>-->
</ons-modal>
```

You can see the sample in attachments, I just made some minor changes to reproduce bug on quickstart sample.
[Test2.zip](https://github.com/OnsenUI/OnsenUI/files/201625/Test2.zip)

Even using ons-if-platform doesn't solve the problem

```
    <div ons-if-platform="android">
        <span >{{message}}</span>
    </div>
    <div ons-if-platform="ios">
        <span >Waiting... </span>
    </div>
```

**Comment by RezaRahmati** [comment]
Any response?

**Comment by IliaSky** [comment]
Thank you for the bug report. After testing it seems to be happening only when the modal is outside of any page. The modal expects to find a page parent and reattach itself so that it's over the page contents. For now the easiest solution is just to wrap the application in a page (`ons-page`) and everything should work. Though it's true that something like this shouldn't stop `ons.ready`.
