### ISSUE TITLE
Beta.8 - pushPage is already running onsenui.js 16214

### ISSUE THREAD

**Issue by munsterlander** [OnsenUI/OnsenUI#1338]
This may be a bug or I may need to adjust how I am processing.  The app stores the last page displayed (walkthrough thread on onsen forums) and upon next app start, jumps the user to that page.  The code used to work and with Beta.8, I am getting a new error.

`Uncaught (in promise) pushPage is already running.  {path}/js/onsenui.js:  16214`

I was doing it in ons.ready(), but it would not load, it just popped the subject line error.  The code below does work, but it still pops the error, so I suspect there is a timing (async) issue with the newly implemented promises.

```
<ons-navigator id="mainNavigator" page="home.html">
  </ons-navigator>

document.addEventListener ("init", init, false);
function init() {
    if (localStorage.getItem("currentChapter") !== null) {
document.getElementById('mainNavigator').pushPage(localStorage.getItem('currentChapter'));
    } 
}
```

I have solved this by using: `document.addEventListener("show", function(event){...` which causes home.html to briefly show before loading the appropriate page.

So my question would be is there a better way to hook into app init but be post initial push of the navigator to avoid the error as well as avoid the brief flash of home.html?  Does that make sense?

**Comment by frankdiox** [comment]
@munsterlander Navigator has been changed internally to make it more general for React and Angular2. This is not a issue related to the promises but to other changes. However, I think this is now the expected behavior. Before, we were using a "doorlock" that made a pushPage wait for the previous one to end before running. Now we removed that and it simply alerts that there is another action running.

If I didn't understand wrong, you need to push multiple pages to go back to a saved state, right? Perhaps you can push the last page and `insertPage` to the stack. Or use `pushPage().then(...)` to chain actions without animation.
Would this work for you?

**Comment by munsterlander** [comment]
That makes sense.  The actual problem lies in using navigator with a defined page, such as:

`<ons-navigator page="home.html" id="myNav"></ons-navigator>`

Then on `ons.ready()` or equivalent, doing:

`document.getElementById('myNav').pushPage('newPage.html')`

This generates the error.  I am using a splitter and getting the error, but a navigator should do the same thing.  I have worked around it by using the show event listener with a global first run variable like:

```
if (localStorage.getItem("currentChapter") !== null && Boolean(firstRun)) {
            firstRun=false;            document.getElementById('mainNavigator').pushPage('content/'+localStorage.getItem('currentChapter'));
        } 
```
