### ISSUE TITLE
ons.notification.confirm() is not working in iOS 9.2.1

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1347]
This was reported by a user.

Please confirm and try to fix it.

**Comment by IliaSky** [comment]
Unfortunately I seem to be unable to. I updated `Xcode`, `cordova`, `cordova-ios` and the emulator still reaches only up to 9.2, not 9.2.1. We also have 3 devices with 9.2, but none with 9.2.1. However I'm not sure if it would be ok to upgrade one of the devices, since it seems like downgrading is not really an option for iOS.

I tested in 9.2 and everything is perfectly fine - it requires an options object with a message property, but that is all. Even something like `ons.notification.confirm({message:1})` works. So currently I'm not sure that there is anything we could do about it. Maybe the user can provide some more information.

**Comment by puku0x** [comment]
Hi,

Thank you for your great job.

I started developing an app with Monaca based on "Onsen 2.0 Quickstart" sample.

I noticed that 
- ons.notification.alert
- ons.notification.confirm
- ons.notification.prompt
did't work on my iPhone6s/iOS 9.3.1 when I updated from Onsen UI 2 Beta.9 to Beta.10.

However, they worked fine on my Nexus6/Android 6.0.1.

**Comment by argelius** [comment]
@puku0x : Thanks for reporting. We will take another look at it.

**Comment by IliaSky** [comment]
The fix has been merged, so it should be available when we release beta.10 officially.

**Comment by puku0x** [comment]
Thank you very much !
