### ISSUE TITLE
Show single title of split view page

### ISSUE THREAD

**Issue by anshulgithub** [OnsenUI/OnsenUI#1361]
I am using "Split View" for my app from this example link https://onsen.io/reference/ons-split-view.html . My requirement is to show single title for complete page. How can i provide a single title for complete page.

**Comment by IliaSky** [comment]
The solution is to put the `ons-split-view` inside an `ons-page` with a title. I have provided an example in [this answer](http://stackoverflow.com/questions/36565859/how-to-provide-one-heading-for-complete-page-when-using-split-view-page-in-ons/36588283#36588283) on stackoverflow.

Since this is just a question and not a real issue I am closing it.
