### ISSUE TITLE
Not able to run in Windows Phone 7 - 8.... is there any settings? 

### ISSUE THREAD

**Issue by dev20881** [OnsenUI/OnsenUI#138]

**Comment by bheijns** [comment]
Hi!

Our company is also waiting for the WP support of Onsen UI. Since you can't give an exact date of support. Can you give some direction? Will it be in (Q?) 2015 or is there no roadmap planned yet?

Thank you so much in advance and please keep up the good work @ Onsen UI!!

Regards,
Bas

**Comment by vbuyakov** [comment]
Dear, Sirs! In fact windows phone support is very important. I see a lot Lumia devices in  hands of people on the street. So, our company seeking a  framework that support WP8-8.1, and i hope it will Onsen UI! 
Regards, Vik.

**Comment by bheijns** [comment]
I completely agree to @vbuyakov ! Is there any roadmap for Onsen UI or some information/news from the development team regarding Onsen UI on Windows phone?

Thank you in advance.

**Comment by sebastianbk** [comment]
@anatoo and @argelius do you need some Windows Phone devices? I would very much like to see Onsen UI fully supporting Windows Phone. Please let me know a status of the progress, then I will be able to help you with some test devices. Shoot me an email at sbrand[a]microsoft.com.

**Comment by masahirotanaka** [comment]
Hi all, I'm Masa somewhat participating in Onsen UI development. Thank you guys for the requests to tWindows support, and I realized there are so many demands.

In short: Yes, we would like to support Windows (or Internet Explorer to be precise)

However since Onsen UI is a WebKit (or Blink) optimized product, we need to solve quite a few fundamental problems. Also, when it comes to the development of the Windows Store Apps, not only the CSS but some JavaScript codes like `eval` needs to be replaced.

I first like to try Onsen UI running on Spartan, and on the latest Windows Phone 8.1, to see how much effort would be necessary to support those platforms. Unfortunately we're in Japan where there's no Windows Phone sold in this country, @sebastianbk offer is so appreciated.

If anybody knows, does Windows 10 (and Windows 10 Phone) run on Spartan engine for both Website and the Store app? Appreciated if some of you guys can join us and work on together for supporting Windows platforms.

**Comment by vbuyakov** [comment]
Hi, Masa! I can join you to work with Windows Phone :)

**Comment by bheijns** [comment]
Me too! If there is anything I can do let me know. I have a Nokia Lumia 920 so I can test on an older device.

**Comment by Wouter33** [comment]
Don't have a windows phone device, but just wanted to add my voice to this thread. For me it's also very important that Windows Phone is supported in the future. Thanks for working on this Masa.

**Comment by masahirotanaka** [comment]
Just for a quick update, we are digging into the problems occurring on Windows devices. Will start pushing IE supported code to another branch.

**Comment by digitsinmotion** [comment]
Great to hear, Masahirotanaka. Thanks for all your efforts!

**Comment by masahirotanaka** [comment]
Hi guys,

We finished supporting Windows 8.1 and Windows Phone 8.1 (so-called Windows Universal). It is already on the [master](https://github.com/OnsenUI/OnsenUI/tree/master) branch.

Our team have done some tests based on the basic scenarios, and they are already passing. But since our test cases are limited, it is really appreciated if you guys take a look at the latest `master` branch and report us issues if you find any.

Thank you!

**Comment by argelius** [comment]
@vbuyakov @bheijns 

To use the latest version you can either clone the repository and do

```bash
$ npm install
$ gulp build
```

or you can download the latest build here: http://onsen.io/download.html#latest-build

**Comment by digitsinmotion** [comment]
I'm experiencing the same issues as before - are there any changes I need to make to the index.html? Perhaps a viewport or other meta tag change?

**Comment by FragCoder** [comment]
I've partially resolved this issue removing querystring from ttf font uri in font-awesome.css/min.css
