### ISSUE TITLE
Question - how to compile stylus

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/OnsenUI#1386]
Please, excuse me for asking this here, but how stylus files should be compiled? 

I would like to compile all onsen styles into one file, like this:
`
stylus node_modules/onsenui/stylus/blue-basic-theme.styl -o server/www/onsenui.css --import node_modules/onsenui/stylus/components/**/*`

However, this produces error:

> stylus node_modules/onsenui/stylus/blue-basic-theme.styl -o server/www/onsenui.css --import node_modules/onsenui/stylus/components/**/*
> 
> /Users/Misho/Work/domo8/domoticOS/node_modules/stylus/bin/stylus:662
>               throw err;
>               ^
> 
> TypeError: /Users/Misho/Work/domo8/domoticOS/node_modules/onsenui/stylus/components/button-bar.styl:28:87
>    24| var-button-bar-margin = 0
>    25| var-button-bar-border-top = 1px solid var-button-bar-color
>    26| var-button-bar-border-bottom = 1px solid var-button-bar-color
>    27| var-button-bar-border = 0px solid var-button-bar-color
>    28| var-button-bar-active-background-color = alpha(var-button-bar-color, var-alpha-lighten)
> ---------------------------------------------------------------------------------------------^
>    29|
>    30| /*! topdoc
>    31|   name: Button Bar
> 
> Cannot read property 'r' of undefined
> 
>     at Evaluator.alpha (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/functions/alpha.js:29:27)
>     at Evaluator.invokeBuiltin (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/visitor/evaluator.js:1051:30)
>     at Evaluator.visitCall (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/visitor/evaluator.js:516:16)
>     at Evaluator.Visitor.visit (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/visitor/index.js:28:40)
>     at Evaluator.visit (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/visitor/evaluator.js:160:18)
>     at Evaluator.visitExpression (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/visitor/evaluator.js:644:26)
>     at Evaluator.Visitor.visit (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/visitor/index.js:28:40)
>     at Evaluator.visit (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/visitor/evaluator.js:160:18)
>     at Evaluator.visitIdent (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/visitor/evaluator.js:551:22)
>     at Evaluator.Visitor.visit (/Users/Misho/Work/domo8/domoticOS/node_modules/stylus/lib/visitor/index.js:28:40)

__Environment__
Onsen 2 beta 13

**Comment by IliaSky** [comment]
Well as you may have noticed in the issue template - [stackoverflow](stackoverflow.com/tags/onsen-ui) or the [community](https://community.onsen.io) is a better place for questions rather than github issues. 

Now for the answer:

The command which is generally used to compile the css is `gulp build` inside the `css-components` folder. You can also take a look at the `gulpfile.js` if you're interested. Also the result is multiple files because you don't want all themes at once - you can use the one which you like. They're basically the same, the only difference being the color variables.

Sorry if it's rude, but I will close the issue. Feel free to ask about more info on the community or SO.
