### ISSUE TITLE
Small fix for ons-toolbar in Android

### ISSUE THREAD

**Issue by claudioc** [OnsenUI/OnsenUI#1387]
OnsenUI 2 Beta 15

Android 5.x (WebView and Chrome)

__Encountered problem__
`ons-toolbar` with left, center and right elements (the center one is a `ons-progress` but it doesn't matter).
The right element goes after the screen and become almost invisible.

__How to fix__
I'd open a PR for that, but I am pretty sure there'd be some side effects I cannot test.

My solution was to reduce the `.navigation-bar .left` min-width to 18px.

Thanks

**Comment by IliaSky** [comment]
Thank you for the report.

Unfortunately I seem to be unable to grasp your actual problem.
Here's a [codepen](http://codepen.io/IliaSky/pen/dMgbGb?editors=1000) of what I seem to be understanding from your description, however that doesn't sound like an actual issue to me. 

Also we are not setting the `min-width` property of the left side but rather the `width`. So if I understand correctly your solution is just to change the defaults, but with other values those defaults would also be insufficient. 

If that is the issue then we may think about improving the default behaviour, but right now it's probably best if you just modify the values in your project as you see fit. 

Sorry if I am being rude - maybe I don't quite understand your problem. If the codepen doesn't seem to be the issue which you want to describe then please tell me what is the difference. :)

**Comment by claudioc** [comment]
Rude? You're perfectly reasonable, and this is also why I didn't open a PR: I probably have something going on with my setup, so I will try to create a minimal case for this issue a send you a screenshot.

Thanks for looking into it!

**Comment by IliaSky** [comment]
Ok. Thank you.

**Comment by claudioc** [comment]
I have removed all the custom HTML and CSS and stripped everything, except JavaScript (which would a bit harder at the moment). I am not doing any DOM manipulation in JS though.

This is an Android Chrome remotely debugged. You can see how the progress-bar expands too much, compressing `.right`.
![screen shot 2016-04-27 at 19 57 27](https://cloud.githubusercontent.com/assets/166692/14862584/60633b82-0cb2-11e6-8626-b8c328a117a5.png)

This is how the same code looks in Chrome desktop (and in Safari iOS)
![screen shot 2016-04-27 at 19 59 53](https://cloud.githubusercontent.com/assets/166692/14862636/a471870c-0cb2-11e6-91f4-1da0726eeef1.png)

Here you can find all the code I use for this test: https://gist.github.com/claudioc/f32ebf9cb1572077f450db5b8cf2d18b

As I mentioned, I can easily fix this with a `min-width: 18px` on the `.left`, but _maybe_ this can help you find a small glitch.

**Comment by munsterlander** [comment]
I also can confirm this causes a weird glitch on the device.  I have also found a way to override it that is odd in its own right:

This code makes the center div too big and the right div too small (I used no CSS nothing but onsen tags in a new project with the nightly but also confirmed on beta 9 with the same issue):

`<ons-page id="page-email">
               <ons-toolbar>
                   <div class="left"><ons-icon icon="md-close" size="24px"></ons-icon></div>
                   <div class="center"><ons-progress-bar></ons-progress-bar></div>
                   <div class="right"><ons-icon icon="md-close" size="24px"></ons-icon></div>
               </ons-toolbar>
            </ons-page>`

Then by adding a simple style tag to the right div, it fixes the issue:

`<ons-page id="page-email">
               <ons-toolbar>
                   <div class="left"><ons-icon icon="md-close" size="24px"></ons-icon></div>
                   <div class="center"><ons-progress-bar></ons-progress-bar></div>
                   <div class="right" style="background-color:red"><ons-icon icon="md-close" size="24px"></ons-icon></div>
               </ons-toolbar>
            </ons-page>`

I was using the background color to see the divs without the progress bar as my first thought was the progress bar had a min-width that was overriding the other css, but leaving the progress bar in and then just adding the background-color to the right div also fixes it without even adjusting any div's width via css.

**Comment by IliaSky** [comment]
Update:
It turned out that the material design has a different layout than the flat one. However it turns out that if the bug which you are reporting is the one in the first picture - currently that seems to be the expected behaviour. It does shrink but it doesn't actually hide the content. 

And I guess I was actually wrong earlier - the MD toolbar left has `min-width: 72px`. However it seems like we got it from the [MD spec](https://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing), so I guess we won't be changing it.

However I agree that the current result seems to look really bad. So I guess instead what we can do is just add the same styles for the `right` as the ones for the `left`. That means:

__MD toolbar styles__
```
.left, .right { min-width: 72px; }
.left:empty, .right:empty { min-width: 16px; }
```

In that case it will look ok. And if you don't like the default values you can change them accordingly for your app. Even though technically according to the MD spec these should be the correct values.

The other case which I can think of is if your right side is bigger than `50%` then you can just remove the `max-width`, but I guess that's probably not your case.

And the final thing which comes to my mind is if it somehow glitches after some animation - the animation `slide-ios` does some things with the toolbar, however after testing on an android device I was unable to reproduce a case where the `.right` becomes hidden as a result of the animation.

So just to make sure - does the glitch which you guys are seeing hide part of the `.right` or just makes it smaller, but with the content still visible?

If it just shrinks it without hiding content (which the currently provided case I think) then I guess in the next version the styles will be as described above, you can change them for your app if they don't fit your design.

If it shrinks in a way which hides it then I would be happy if you could provide a case in which it can be reproduced :)

**Comment by claudioc** [comment]
Oh, sorry, I forgot to tell you: the issue about the right part disappearing was actually my fault: on android the mix of MD + my CSS resulted in the right icon to be white on white :D (I use white as the bg color of the toolbar). I got confused by the progress bar stretching!

Thank you for the fix!

**Comment by IliaSky** [comment]
Oh ok. In that case I'm glad that everything is solved. :)
