### ISSUE TITLE
pushPage fails with <ons-splitter>

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#1400]
__Environment__
Onsen 2 rc4
Angular

__Encountered problem__
If I launch my main page with navigator and push another page with pushPage, everything is ok.

```
myNavigator.pushPage('main.html', { animation: "none" });
...
myNavigator.pushPage('second-page.html', { animation: "none" }); => ok
```

But if I launch the main page with splitter, the second page is not shown.
(but initialization seems ok)

```
<ons-splitter>
	...
	<ons-splitter-content page="main.html"></ons-splitter-content>
</ons-splitter>

myNavigator.pushPage('second-page.html', { animation: "none" }); => page not shown
```

**Comment by munsterlander** [comment]
I don't know what all your code is as you haven't posted it; however, this is valid code verified on the RC.

`  <ons-navigator id="mainNavigator" page="splitter.html">
  </ons-navigator>
  <ons-template id="splitter.html">
    <ons-splitter id="mainSplitter">
      <ons-splitter-side page="content/menu.html" side="left" swipeable collapse="portrait" width="200px">
      </ons-splitter-side>
      <ons-splitter-content page="home.html">
      </ons-splitter-content>
    </ons-splitter>
  </ons-template>`

**Comment by IliaSky** [comment]
As @munsterlander said - the code which you have provided isn't enough to replicate the issue.
Here's a working [demo](http://codepen.io/IliaSky/pen/rePgbp?editors=1000) of what I and munsterlander seem to be understanding.

If you have an `ons-navigator` it should work properly regardless of the contents of the pages (whether there is a splitter inside should make no difference). If you are trying to use the `pushPage` method on the `ons-splitter` itself then here it's time to mention that it doesn't have such a method. The `ons-splitter-content` only has a `load` method.

According to what I understand from your explanation - you say that the page is pushed successfully, but just isn't shown (as in `display: none`) or am I misunderstanding?

If that's the case then maybe somehow onsen wasn't initialised for angular. To do that you need:

1. `['onsenui.js', 'angular.js', 'angular-onsenui.js']` in this order
2. Either `ons.bootstrap()` or `angular.module('myAppName', ['onsen'])`

If somehow you forgot `2` then I am sort of able to reproduce the issue. However if you want to use onsen with angular you should always have one of those two expressions.

Anyway if none of these answers helped then we would be grateful if you could modify the codepen given above to your case, so that we can fix it.

**Comment by bdedardel** [comment]
Thanks guys,

My mistake was : 
- to not embed  <ons-splitter> inside <ons-template id="splitter.html">
- to not set page attribute with navigator <ons-navigator page="splitter.html">

Without your help, I wouldn't have find the solution with the current documentation, especially https://onsen.io/v2/docs/js/splitter.html page that doesnot speak about navigator.

Thanks again...

**Comment by IliaSky** [comment]
@bdedardel the thing is if you don't need a complex page stack but rather just want to change the main page you can do that just by `mySplitter.content.load('second-page.html')`. 

About the templates - they're just handy to use, but you don't need to. You can always just put the an `ons-page` inside the navigator and not use the `page` attribute and it will have the same effect. I updated the demo to show that. I guess you were just putting the `splitter` directly inside the `navigator` - I think from the next version we are throwing a warning in that case.

Anyway I'm glad that the problem is solved.

**Comment by meisam3322** [comment]
i use this address http://codepen.io/IliaSky/pen/rePgbp?editors=1010
but splitter only work for first page. is there any idea to make splitter globally ??

thank you lliaSky for that cool demo
