### ISSUE TITLE
ons-bottom-toolbar does not utilize left, center, right classes

### ISSUE THREAD

**Issue by munsterlander** [OnsenUI/OnsenUI#1424]
__Environment__
Onsen 2 RC 4

__Encountered problem__
Ons-bottom-toolbar does not implement the left, center, and right classes as described in the docs.  It is discussed here:  https://community.onsen.io/topic/438/ons-bottom-toolbar-doesn-t-work/3

__How to reproduce__
Codepen demonstrates the issue:  https://codepen.io/anon/pen/PNrroB?editors=101

**Comment by argelius** [comment]
@munsterlander 

Hi!

Thanks for reporting. Actually this is intentional, we don't add any special padding to the bottom toolbar since there are lots of different ways to populate it and we don't want to try anticipating what the developer wants to use it for.

I will close this for now but maybe we should add some clarification to the docs.

**Comment by munsterlander** [comment]
@argelius No problem.  The docs do need to be corrected because they appear to indicate that it works for top and bottom.
