### ISSUE TITLE
ons-navigator and ons-init

### ISSUE THREAD

**Issue by khuongcomputer** [OnsenUI/OnsenUI#1425]
This strange issue happened on ver 2rc5.

I have ons-navigator A on index.
ons-navigator B inside A.

Page C and D with ons-init on every page.
MakeB load C and D with bringPageTop/resetToPage. Only ons-init on C are fired, ons-init on D is not.
If I do a pushPage, ons-init is fired as normal.
**Only happens on mobile's browsers** (tested with iOs 9.2 and Android 4.2), on desktop ons-init works normally.

Please take a look at it.

**Comment by argelius** [comment]
@frankdiox Can you take a look at this when you have time?

Maybe there is a difference with native web components and the polyfill?

**Comment by frankdiox** [comment]
@argelius @khuongcomputer I only have Android 5.1.1 here and cannot reproduce this issue. I made this [pen](https://codepen.io/frankdiox/pen/WwVzwm?editors=101) but I'm not sure if this is the right way to reproduce it. @khuongcomputer next time please provide a working example so we can skip this step.

In any case, `bringPageTop` relies on `pushPage` for the first push. If the page already exists then it just bubbles to the top, what should **not** fire `init` event. However, this event should be fired always for `resetToPage`.

**Comment by khuongcomputer** [comment]
@frankdiox please get the example here: http://www.mediafire.com/download/bqsmbd94ozk0win/bug-ons-navigator.zip

Tested with Chrome and Safari on iOS 9.2 and it's not showing any alert. On desktop it works as intended.

**Comment by frankdiox** [comment]
@khuongcomputer I tried that one and still works. I guess it does not happen in Android 5.1.1.
Let's see if @IliaSky has time to test this with iOS 9.2.

**Comment by IliaSky** [comment]
I tested it and it seems that in iOS `attachedCallback`, `contentReady` and `setImmediate` are all being executed before angular view's constructor is called. So even in much simpler cases our `init` event is fired before the angular view starts working. That's why the `ons-init` just misses the event (the even is fired normally, only the attribute doesn't work).

On another note: it seems that angular itself fires `pageinit` after it loads - I guess it's for backwards compatibility with Onsen 1, but it doesn't seem to be documented. Also I guess after this issue is fixed we can just listen for one event and fire the other one accordingly, as right now it has some hack to ensure that it's properly attached which is not really needed I guess. The other thing is maybe it would be better if we either document it or remove it, but maybe leaving it is also fine.
