### ISSUE TITLE
iOS flushing pages

### ISSUE THREAD

**Issue by awajda** [OnsenUI/OnsenUI#1484]
Onsen 1.3.8
Angular 1.4.3
iOS 9.2
My team is working on the mobile application using ons-navigation, some pages use ons-tabbar. 
Once we deployed application to iOS (iPhones and iPad too) devices for testing purposes, we noticed that some pages get flushed after loading. Some of these affected pages are just standard ons-page, w/o ons-tabbar. 

Other platforms (Android/WP 8.1) work and there is no flushing (at least we can't see it).

**Comment by frankdiox** [comment]
@awajda I'm not sure if I get what you mean. Are the pages reset after loading? Is there any flickering? If you have issues both with and without tabbar, probably the real problem is in the navigator. However I cannot think about anything else with this information :/

Anyway, we are now focused in version 2.0. It's release candidate and I think is better for production than 1.x right now, specially after we release rc.15.
We made a [migration guide](https://onsen.io/v2/docs/guide/angular1/from-v1-to-v2.html) recently, check it out if you are interested.
