### ISSUE TITLE
Dynamically change theme

### ISSUE THREAD

**Issue by rtholmes** [OnsenUI/OnsenUI#1489]
**Environment**
Onsen 2 beta 14

**Feature Request**

The theme roller pattern page is pretty great (http://components2.onsen.io/patterns) and demonstrates the flexibility of the Onsen theme system. It would be great to be able to ship multiple themes with an app to give users the ability to dynamically change their theme (e.g., light and dark).

**Comment by argelius** [comment]
@rtholmes This is a good suggestion. Most modern browsers already support injecting and removing styles by adding and removing tags from `<head>`. You could probably implement this yourself with just a few of lines of code.

It's also possible to disable and enable stylesheets with the `documents.styleSheets[idx].disabled` property.

So basically I don't think this needs to be implemented in the core library, especially since we don't know how the stylesheets are being loaded.

**Comment by rtholmes** [comment]
Actually that works great; might be worth adding to the theme roller docs or the guide for anyone thinking about this. Thanks for the tip!

**Comment by MortezaT** [comment]
I'm using version `2-rc.15` with phonegap on android. the only themes that works for me is default and dark is there any problem with my code or this is android restriction?
