### ISSUE TITLE
ons-list with ons-dialog : A scrolling issue.

### ISSUE THREAD

**Issue by jamesst20** [OnsenUI/OnsenUI#1490]
Onsen 2 RC15
Android 6.0

Hi,

I have a ons-list on my ons-page and also a dialog. The problem is that even when the dialog is open, I can still scroll and the dialog will not follow. Also, let's say I scroll down and click an item to open the dialog, the dialog will appear at the top of the page so I have to scroll to the top to see it

Before scrolling (fine) http://i.imgur.com/JQWW0Nr.png
After scrolling (oops) http://i.imgur.com/a6x5LcL.png

Here is a sample code to test : http://pastebin.com/J5ZKLGPn

Thank you

**Comment by argelius** [comment]
@jamesst20 Thanks for reporting!

The reason why it's scrolling with the page is that it's inside the `<ons-page>` element. Can you move it outside the element?

Since it's a modal dialog that covers the whole screen you can normally attach it directly to the body without any problem. Only difference is that the semi-transparent mask will also cover the toolbar but that is normally preferred behavior.

I will close this but please feel free to open it again if you are still having trouble. Thanks!

**Comment by jamesst20** [comment]
@argelius 

Thank you!! I will test once I get back to work on monday :)

Your answer makes sense ! 

Thanks :)

**Comment by argelius** [comment]
I hope it works out!

**Comment by jamesst20** [comment]
It worked ! Thank you ! :)
