### ISSUE TITLE
I can't install Onsen UI 2 + Angular 2

### ISSUE THREAD

**Issue by davidNieves** [OnsenUI/OnsenUI#1494]
I all and thanks in advance.

I have a problem with angular 2 + onsen ui 2. I follow this steps:

1. Install Angular 2 with Node.js following the official documentation. All perfect. https://angular.io/docs/ts/latest/quickstart.html
2. After I follow onsen ui 2 install from official documentation: https://onsen.io/v2/docs/guide/angular2/index.html

    2.1.- Run command to install onsen ui + onsen ui 2 "npm install onsenui angular2-onsenui" now in my node_modules folder has 2 news folder "onsenui" and "angular2-onsenui".  
    ![](http://puu.sh/pPN0O/198a837ec0.png)
    2.2.- Modified app.component.ts to include onsen ui directives: 
    ![](http://puu.sh/pPN47/15c8319332.png/2dca7d41bd.png) I follow this of section "Loading Onsen UI in Angular 2" of official documentation of onsen ui 2.
    2.3.- Also changed my systemjs.config.js to "map" onsen ui: 
    ![](http://puu.sh/pPMYW/3f7112f1be.png)

3.- When I start app I get this errors: 
![](http://puu.sh/pPN7M/4687979cb7.png)

What did do wrong here? I take a few days with this and I can't find solution! please help!!

**Comment by IliaSky** [comment]
Hi @davidNieves. 

First I would like to mention that (as you may have noticed in our issue template) - we like using github issues only for bugs and feature requests only. Questions should be asked in either [stackoverflow.com/tags/onsen-ui](http://stackoverflow.com/tags/onsen-ui) or [community.onsen.io](https://community.onsen.io).

But anyway here's your answer:

There are 2 things which should be noted here:

1. Make sure that you installed onsen 2 instead of onsen 1. We recommend installing onsen ui with `npm install onsenui@latest`.

2. Since you are using `systemjs`there is one more line which you need to add in order to import `angular2-onsenui` - mentioning the location of the main file of the module, as well as the default extension.

  That line would be 
  ```packages['angular2-onsenui'] = { main: 'dist/src/angular2-onsenui.js',  defaultExtension: 'js' }```

  We prefer using `webpack` as importing things with it is a little bit easier. It takes the main file's location from `package.json` automatically and is also able to import the other files without specifying the extension.

Anyway make sure you confirm these 2 points and you're good to go.
