### ISSUE TITLE
icons not showing at all

### ISSUE THREAD

**Issue by cyclops24** [OnsenUI/OnsenUI#1498]
Hi guys,
I start using OnsenUI 2 and your awesome package in Meteor 1.3.2.4 but I have small issue with them.
Icons not showing at all in my project. You can reproduce and see this here: https://github.com/MeteorDemoApps/OnsenUI2JS-demo/commit/64b49bc04ceeeb79375f04ba03a304682b03baa1 and below image:
![onsenui_2](https://cloud.githubusercontent.com/assets/8266479/16625787/6b91d73a-43bb-11e6-879a-4ebb7d0ce811.png)

I try many things but it's still not working. What is the problem? Is it a bug for CSS references?

**Comment by frankdiox** [comment]
@cyclops24 Hello! Probably the fonts are not loaded. Try to import them here: https://github.com/MeteorDemoApps/OnsenUI2JS-demo/blob/be29cd85d9bd75983c3eb680851a12e3eb382330/imports/ui/layouts/app-body.js

I think it should be something like:
```
import 'onsenui/css/font_awesome/css/font-awesome.min.css';
import 'onsenui/css/ionicons/css/ionicons.min.css';
import 'onsenui/css/material-design-iconic-font/css/material-design-iconic-font.min.css';
```

At least if you have the whole onsenui package in the same directory.

**Comment by cyclops24** [comment]
@frankdiox Hi man,
I see these files imports in `/onsenui/css/onsenui.css` like below:
```
@import url("font_awesome/css/font-awesome.min.css");
@import url("ionicons/css/ionicons.min.css");
@import url("material-design-iconic-font/css/material-design-iconic-font.min.css");
```
Why need import it again in JS when I import `onsenui/css/onsenui.css`? :anguished: 

Anyway I added what you said in `app-body.js` and it seems something happens but still not working completely. You can see my output now in below image and compare previous in above comment:
![onsen_4](https://cloud.githubusercontent.com/assets/8266479/16642663/7622288c-4422-11e6-8429-a87a298bc7af.png)

**Comment by cyclops24** [comment]
Guys are you any idea about this?

**Comment by munsterlander** [comment]
How did you create the Onsen project?  This usually appears when the Onsen directory is messed up.  If the project is created via the CLI or Cloud, then the project is imported/created correctly.  Usually, I see problems like this when projects are being manually created.  Can you confirm that the Onsen directory has the aforementioned files in their appropriate path?

**Comment by frankdiox** [comment]
@cyclops24 Finally I got some time to check it. This problem is due to the way Meteor imports CSS when you write it in a JavaScript file. They simply copy the content of the file you import into a `<style></style>` tag in the `<head>` of `index.html`. However, they don't resolve the imports inside that file! Even if you manually include the icons CSS manually it won't work because those files also import the fonts at the same time, and that's not resolved by Meteor.

I've set up a simple application using React Onsen UI and Meteor 1.4 (it's actually [their ToDo app tutorial with React](https://www.meteor.com/tutorials/react/creating-an-app)) working in this repo: https://github.com/frankdiox/OnsenUI-Meteor-ToDo

Heroku link [here](https://onsenui-meteor-todos.herokuapp.com/).

The workaround is simple, just copy the fonts to the public folder in Meteor and it will be able to import them in client side.
