### ISSUE TITLE
ons-sliding-menu shows white status bar on iOS

### ISSUE THREAD

**Issue by alegauss** [OnsenUI/OnsenUI#1500]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 beta 15
Angular 1.5.2
iOS 9.2

__Encountered problem__

Using ons-sliding-menu on iOS appears white rectangle on status bar

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)
![screen shot 2016-07-06 at 23 16 35](https://cloud.githubusercontent.com/assets/331174/16640830/cef63558-43d1-11e6-9e18-cd672f927990.png)

**Comment by IliaSky** [comment]
Hi @alegauss. Looking at your DOM structure the fact that the sliding menu page has a `status-bar-fill` attribute is expected behaviour. As for the reason why it's white - that's just the default color.

The status bar fill itself as you can see is not an element, therefore it just adds padding on top of the page (and doesn't have a specific background). If there is a toolbar then the toolbar fills that distance. If there is no toolbar, then the background of the page is visible. So to change that you can just change `#side-page .page__background`'s background and you're good to go.
