### ISSUE TITLE
Whole-screen wiggling in iOS

### ISSUE THREAD

**Issue by tommy0311** [OnsenUI/OnsenUI#1502]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

**Environment**
"onsenui": "^2.0.0-rc.15",
"react-onsenui": "^0.6.2"
iOS 8.4.1
Meteor 1.3.3.1

**Encountered problem**
Whole-screen wiggling in iOS
http://imgur.com/1p0uSwq

**How to reproduce**
Run example on iOS device
https://github.com/OnsenUI/react-onsenui-kitchensink

**Comment by IliaSky** [comment]
Does this happen only when there is a tabbar in the page or always? If it only happens when there is a tabbar then it may have been fixed together with #1501. Otherwise I guess it's possible to be a react issue where react is trying to restore some previous state and ends up in some kind of loop because of that.

I just tested it and was unable to reproduce it with
`react-onsenui-kitchensink`, `onsenui@2.0.0-rc.15`, `react-onsenui@0.6.2`, iOS versions 8.4 and 9.3.

I did find a similar bug with the pull-hook, it might be related. However that bug seems to be `react-onsenui` only, so probably the one which you are reporting is too.

We would be thankful if you could confirm whether this bug persist in RC.16 when we release it. If it does then maybe @philolo1 or @argelius should take a look at it.

**Comment by philolo1** [comment]
A minimal example would be good to reproduce this issues.

**Comment by tommy0311** [comment]
@IliaSky I observe it always happens.
@philolo1 Please reproduce the issue via this
https://github.com/tommy0311/issue-1502

**Comment by argelius** [comment]
@tommy0311 Does this happen only when using Meteor? It doesn't happen when I run it in Mobile Safari.

**Comment by tommy0311** [comment]
@argelius Meteor build app with cordova.
I observe It only happens on real iOS device like iPhone or iPad.
The other platform like android, web and simulator are fine.

**Comment by argelius** [comment]
@tommy0311 Does it also happen for you if you open the app in Safari on the real device?

**Comment by tommy0311** [comment]
@argelius  Open the app in Safari on the real device does not happen this issue.
