### ISSUE TITLE
Onsen2 - 100% CPU when 2+ ons-modals are on the page

### ISSUE THREAD

**Issue by erikcw** [OnsenUI/OnsenUI#1511]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 rc-15
Angular 1.5.7
OSX - Chrome 51

__Encountered problem__

CPU gets pegged at 100% when an `ons-page` contains 2 or more `ons-modal` components.  

Here is a screenshot of the JS Profile from Chrome Dev Tools.

![screen shot 2016-07-15 at 10 30 58 am](https://cloud.githubusercontent.com/assets/113129/16883124/4dab63e0-4a77-11e6-8851-130b6c834eb1.png)

When I look at the DOM elements in the Chrome DevTools, I can see the `<div class="page__extra"...>` contents continually changing with new `ons-modal` elements.  Looks like they are stuck in some sort of render loop.

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)

```html
<ons-template id="item-details.html">
  <ons-page ng-controller="MyController">
    <ons-modal >
        <div>test 1</div>
    </ons-modal>
    <ons-modal >
        <div>test 2</div>
    </ons-modal>    
  </ons-page>
</ons-template>

```
vs No problems with just:

```html
<ons-template id="item-details.html">
  <ons-page ng-controller="MyController">
    <ons-modal >
        <div>test 1</div>
    </ons-modal>   
  </ons-page>
</ons-template>

```

**Comment by munsterlander** [comment]
Modals don't need to be inside a page as they are callable templates.  Have you tried moving them outside and just be stand alone snippets?

**Comment by argelius** [comment]
@erikcw Thanks for reporting!

I tried this and it looks like it keeps attaching and detaching the element if you put two modals in the page.

We will take a look at this and fix it.

**Comment by thisar** [comment]
hi, I have the same problème in my projet.
I have div= page__extra turn always for data-device-back-button-handler-id to find an id. It autoincrement always. how you solved ?

**Comment by IliaSky** [comment]
@thisar what version are you using exactly - all `.page__extra` logic should already be removed, so you should not have such an element with RC 16-17. If you update your onsen version the bug should also disappear :)

**Comment by thisar** [comment]
Hi, I Use onsenui v2.0.0-beta.8 - 2016-03-25 . is'nt the laster,

**Comment by argelius** [comment]
@thisar Can you try updating to the latest version?

**Comment by thisar** [comment]
I am , I 'll let you know if it solves the bug

**Comment by thisar** [comment]
It's ok. Thank U

**Comment by thisar** [comment]
Hi, 
In fact I have a big edge effect.
Yes I do not have the problem of extra page.
But I can not use my application because loggin no longer works with the update of onsen.

all over the page , I can click on anything and I can not write .

**Comment by thisar** [comment]
<ons-toolbar>
    <div class="center" id="infoApp">Apizee<br /><em>{{labels.communicationService}}</em></div>
</ons-toolbar>
<ons-page ng-controller="LoginController" id="login_zone" ng-init="init()">
    <div class="background">
        <div class="login_form">
            <p id="infoApp">

            </p>
            <ons-row class="logo">
                <ons-col>
                    <img src="img/login.png" alt="Login" />
                </ons-col>
            </ons-row>
            <ons-row>
                <ons-col>
                    <input type="text" ng-model="email" class="text-input--underbar" placeholder="{{labels.Login}}" value="">
                </ons-col>
            </ons-row>
            <ons-row>
                <ons-col>
                    <input type="password" ng-model="password" class="text-input--underbar" placeholder="{{labels.Passwd}}" value="">
                </ons-col>
            </ons-row>
            <ons-row class="selectLanguage">
                <ons-col>
                    <select class="text-input--underbar" ng-change="translate(culture)" ng-model="culture" >
                        <option value="en" >English</option>
                        <option value="fr" >Français</option>
                    </select>
                </ons-col>
            </ons-row>
            <ons-row class="buttonLogin">
                <ons-col>
                    <ons-button class="{{connectLabel}}" id="login_button" ng-click="doLogin();" type="button">
                        {{labels.Connect}}
                    </ons-button>
                </ons-col>
            </ons-row>
            <ons-row class="LinkUtil">
                <ons-col align="left">
                    <button class="button large black-btn button--large" ng-click="createAnAccount()" >
                        {{labels.createAnAccount}}
                    </button>
                </ons-col>
                <ons-col align="right">
                    <button class="button large black-btn button--large right"  ng-click="lostPassword()" >
                        {{labels.forgotPassword}}
                    </button>
                </ons-col>
            </ons-row>
        </div>
    </div>
</ons-page>
<ons-modal var="modal" >
    <ons-progress-circular indeterminate></ons-progress-circular>
    <br><br>
    <span>{{labels.waitMessage}}</span>
</ons-modal>

**Comment by thisar** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/20967348/17767224/be8cef36-6537-11e6-9ef9-113f8609ee09.png)

**Comment by IliaSky** [comment]
@thisar The code seems pretty much fine. The problem comes from the `background` class - Onsen uses 2 classes for its pages - `page__background` and `page__content` - Since for some other frameworks it's better for the users to be able to create those themselves we decided to add these classes automatically if we find either `.background` or `.content` children directly in `ons-page`. So what is happening is your element became a background which is why you are unable to click on it. If you change your class to `my-background` or something similar it will be fine. Here's a [demo](https://codepen.io/IliaSky/pen/OXqZjQ?&editors=101) of the login in french (for people who don't know the words :D).

PS: when posting code in github issues you can wrap it in triple backticks ``` on both sides and it will be fine :)

**Comment by thisar** [comment]
Thank you very much. It works.
But if 

> <ons-toolbar>
    <div class="center" id="infoApp">Nom<br /><em>{{labels.communicationService}}</em></div>
</ons-toolbar>
<ons-page ng-controller="LoginController" id="login_zone" ng-init="init()">

it work.
And if 
<ons-page ng-controller="LoginController" id="login_zone" ng-init="init()">
  <ons-toolbar>
    <div class="center" id="infoApp"> _{{labels.communicationService}}</em></div>
  </ons-toolbar>

I have an error util.js:150 Uncaught (in promise) Error: "html" must be one wrapper element.
    at Object.util.createElement (http://localhost:8000/browser/www/onsen/js/onsenui.js:3885:14)
    at http://localhost:8000/browser/www/onsen/js/onsenui.js:8923:27

**Comment by IliaSky** [comment]
@thisar - it sounds like somewhere you are providing 2 sibling elements where onsen expects only one. Maybe if you can post something like a codepen where we reproduce the issue it will be simpler. (For example modifying the one above.) 

From what I see:
- Having the `ons-toolbar` inside the `ons-page` is actually the expected behaviour, which you can also see in the codepen provided above. 
- In the non-working example you have a closing `em` tag without opening it. Browsers have been trying to deal with invalid html structures for a long time and in some cases having one extra opening or closing tag may actually result in many tags like that one appearing across the whole dom. 
Unfortunately I don't have a tool to recommend for this issue - while there is a W3C validator I also don't use it so I would just suggest being careful or having some extra feature on your editor of choice warning you about such errors.

Also since this isn't related to the original issue and it seems to be a discussion rather than a bug I would suggest continuing the conversation in the onsen [forum](https://community.onsen.io)
