### ISSUE TITLE
Expose animators

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1524]
@OnsenUI/members It should be possible to import animators so they can be extended more easily.

What do you think is a good API for importing the animators?

**Comment by frankdiox** [comment]
Right now creating a new animator is done [like this](https://codepen.io/frankdiox/pen/kXJvQL?&editors=101) (in ES5). I think we should also have a `extend` method to make this easier.

For the core API, perhaps we can move the element classes to `ons` object instead of `window`:
* `ons.OnsNavigatorElement.registerAnimator`
* `ons.OnsNavigatorElement.animators.iOSSlide`
* `var customAnimator = ons.OnsNavigatorElement.animators.iOSSlide.extend({ constructor: ..., push: ..., pop: ...})`

For ES6 imports:
* `import { OnsNavigatorElement } from 'onsenui';`
* `OnsNavigatorElemet.animators.iOSslide`
* `OnsNavigatorElemet.registerElement`

Maybe we can drop `Ons` prefix.

The common use case is to change 1 or maybe 2 animations, so I guess it's not necessary to put all the animators togethers in only one object, although it's also a possibility.

**Comment by philolo1** [comment]
Should animators depend on the object? I think it would make more sense to
make them more general and expose them in an ons object if its possible.

**Comment by IliaSky** [comment]
@philolo1
Basically they don't really depend much on the object - the question is more like where would they feel natural to be accessed from. 

The splitter, tabbar and navigator animations are special since they operate on different objects.

In theory if we put them in the same place I think we may get users confused a little.

You are correct that the animations for `ons-modal`, `ons-popover`, `ons-dialog` and `ons-alert-dialog` should be interchangeable since they have the same methods and arguments.

Maybe a similar option to what you suggest would be to put them in `ons.animators`, but still group them there like
`ons.animators.navigator` `ons.animators.general` etc,
but I'm not sure whether this makes more sense than just `ons.OnsNavigatorElement.animators`.

@frankdiox 
For the "ons object instead of window" +1 I also think that.

I would be fine with dropping either Ons or Element from `ons.OnsNavigatorElement`, but maybe it seems more explicit and readable for some people.
I think it would be best if we could do
```import {Navigator} from 'onsenui.elements'```
but I don't think that is possible. Anyway I think both any change and no changes in this regard would be fine.

For `ons.OnsNavigatorElement.animators.iOSSlide.extend` I guess it's still much better to give them something like this rather than forcing them to extend it the normal ES5 way. Even though technically if they override all of the methods they won't be using anything from the original (-_-)'.

I think in general it would be better if some aspects of the animators are more general before we export them though.

Something like making our methods just take a single options argument where we would provide everything needed. Right now we have some methods taking 4 arguments already and i think we may need to add a fifth maybe, which doesn't sound nice.

Also maybe having a default constructor and having a simple way for a method to take the animationOptions into consideration. I'm not sure our users would be able to handle our settings properly most of the times.

I would personally like some option like to add a basic animator where they only provide the css values they would want and we could make/have an animator with their custom options. This idea may be a little radical though and may require some additional coding on our side, so it would understandable if it's rejected.

Sidenote: I think I would prefer `addAnimator` rather than `registerAnimator`. 

Other than this I guess Fran's suggestions seem ok.

**Comment by argelius** [comment]
I think @frankdiox's suggestion looks good and it isn't a big change from what we currently have.
