### ISSUE TITLE
Feature request: behaviour of ons-button to submit form

### ISSUE THREAD

**Issue by philolo1** [OnsenUI/OnsenUI#1538]
Some user in react-onsenui wants the `ons-button` to behave like in a form, meaning if you click the button it will submit the form. Here is the related issue? https://github.com/OnsenUI/react-onsenui/issues/105. Lets discuss this feature here

**Comment by philolo1** [comment]
@frankdiox @argelius @IliaSky @anatoo opions are appreciated

**Comment by IliaSky** [comment]
I agree that it makes sense. When I initially looked at Onsen UI I was also expecting the same behaviour. 

Implementing it shouldn't be too big of an issue. Though if the others don't like the idea I guess it doesn't sound very important.

**Comment by munsterlander** [comment]
I guess I am on the opposite side of this.  I do not want this feature as a default, because then I am going to have to disable it 99% of the time.  If it was an attribute to set to true, then fine, but I would prefer to just code the form submit in JS because of user input validation.  Just my opinion.

**Comment by munsterlander** [comment]
On mobile so I can't edit my previous post, but I guess I could see the user of the type attribute so you could set it to submit or button.

**Comment by frankdiox** [comment]
I don't have a strong opinion on this. In case we implement it I guess it should be optional with `type="submit"` or `type="button"` as the normal HTML5 buttons. Too bad that we cannot extend `HTMLButtonElement` in CustomElements :sweat_smile:

**Comment by IliaSky** [comment]
@munsterlander 
The way I see it it shouldn't make any problems most of the time. This feature will do something only when the `ons-button` is inside a `form` tag. (I may be wrong, but I think most of our users just use the `ons-button` without putting it in a form.) If you have a form tag it's usually better to change the form submission in the first place, so button clicks shouldn't be a problem since you can actually submit the form only when it's valid.

Something like
```
form.addEventListener('submit', function(e) {
  if (!isValid) {
    e.preventDefault();
  }
});
```

But I do agree that maybe adding functionality like that in theory may cause some issues in some cases. If the others think so too I guess if we enable it via `type="submit"` or sth similar it won't be a problem. :)

**Comment by munsterlander** [comment]
I would prefer the type attribute, this way the default behavior is just a markup button.  Default submit - in a form or out of a form - raises security issues that I avoid.

**Comment by argelius** [comment]
I don't really want to do this since we would have to add a custom click event listener to every button that submits the parent form. Better to just let the user add their own click event handler for the cases where they want to submit a form.
