### ISSUE TITLE
readyLock is undefined

### ISSUE THREAD

**Issue by jvillamor-visp-net** [OnsenUI/OnsenUI#1539]
**Environment:**
Onsen 2.0.0-rc.17
Meteor 1.4.0.1
Angular-Meteor 1.3.11
es5-shim 4.6.13

**Problem:**
After importing onsen in a fresh Angular-Meteor project, I get `TypeError: ons._readyLock is undefined` in Firefox and `Uncaught TypeError: Cannot read property 'lock' of undefined` in Chrome. 

**Reproduction:**
Here's a meteor project repository that produces the error. Click [here](https://github.com/jvillamor-visp-net/meteor-onsen-lock-bug).

I was hoping to use onsen with angular-meteor. It would be great to get this fixed.

**Comment by frankdiox** [comment]
@jvillamor-visp-net Looks like there's a problem with the import timing. Try this:

```javascript
window.ons = require('onsenui/js/onsenui');
require('onsenui/js/angular-onsenui');
```

**Comment by jvillamor-visp-net** [comment]
@frankdiox the error is gone when I used require. However, after requiring the libraries, a new error pops up. 

`Onsen UI require jqLite. Load jQuery after loading AngularJS to fix this error. jQuery may break Onsen UI behavior.`

I'm using angular from npm and not from atmosphere. Even if I get the package from atmosphere, the same error pops up, ending with a blank page.

Are there any plans for Onsen to create a meteor package?

**Comment by frankdiox** [comment]
@jvillamor-visp-net I think you can safely ignore that warning. Looks like Meteor is including jQuery and Angular also includes its own jqLite. If you know a way to change the dependency order in Meteor you can try to load AngularJS before jQuery.

I don't think we need to release a meteor package since using NPM seems to be enough.
By the way, there is a OnsenUI-Meteor application [here](https://github.com/frankdiox/OnsenUI-Meteor-ToDo), although it's made with React instead of AngularJS.

Closing this for now, feel free to open it again if you encounter any other issue.
