### ISSUE TITLE
lazy list feature

### ISSUE THREAD

**Issue by boomfly** [OnsenUI/OnsenUI#1555]
List works well only when the server is very heavy forms each time a large list. It would be possible to implement the infinite list like this with two properties and loadMoreData and moreDataCanBeLoaded to load data portions

**Comment by IliaSky** [comment]
Hi - we actually already have 2 features like that. 

The first one is `ons-lazy-repeat` - it focuses on also keeping the dom relatively clear, showing only a set amount of items at any point. [docs](https://onsen.io/v2/docs/js/ons-lazy-repeat.html)

The second one has an API almost identical to the one which you suggest. It's a property or attribute of `ons-page` - (`on-infinite-scroll` attribute or `onInfiniteScroll` property). You just need to provide a function which loads the data. It's first argument is a callback to show when the data can be loaded again - if your data has all been loaded then you just don't need to call the callback. [docs](https://onsen.io/v2/docs/js/ons-page.html#usage)

If you already have your 2 variables you can do something like this:
```
var loadMoreData = function(){...}, moreDataCanBeLoaded = true;
myPage.onInfiniteScroll = function (done) {
  if (moreDataCanBeLoaded) {
    loadMoreData.then(done);
  }
};
```

The big difference between the two ways is that the first one keeps the dom relatively small, while in the second one you handle loading the data and therefore has a simpler API.

Anyway I will close this issue since we already have the feature.
