### ISSUE TITLE
OnsPage is not bound/exported in Angular2 bindings

### ISSUE THREAD

**Issue by Dynalon** [OnsenUI/OnsenUI#1602]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
git master
Angular 2.0 final

__Encountered problem__
The `ons-page` element is not found when used in angular2 as it is not bound/exported from Onsen.

__How to reproduce__

When looking at the Sourcecode at <https://github.com/OnsenUI/OnsenUI/blob/master/bindings/angular2/src/angular2-onsenui.ts> which is the main module entry point for angular2, there is no `OnsPage` element exported and it is not within the `declarations` array (which would be required to register it as a custom component in  an angular2 `NgModule`). Since `<ons-page>` is required to build any Onsen application, I think it is currently not possible to use Onsen in production together with angular2. Angular2 support should be considered broken ATM.

**Comment by asial-matagawa** [comment]
@Dynalon 
Thank you for reporting!
`OnsPage` directive has been removed since Onsen UI RC.16 ([CHANGELOG](https://github.com/OnsenUI/OnsenUI/blob/master/CHANGELOG.md#v200-rc16)) because of some reasons.
Since Angular 2 RC.5, when using Custom Elements-based library such as Onsen UI, you must put `CUSTOM_ELEMENTS_SCHEMA` into NgModule metadata.
With `CUSTOM_ELEMENTS_SCHEMA`, it will work.

Here is a sample using `<ons-page>` without `OnsPage` directive:
https://github.com/monaca-templates/onsenui-v2-angular2-tabbar/blob/master/src/main.ts

**Comment by Dynalon** [comment]
That worked. It is very confusing, since the docs are outdated (see my issue #1598 on that)
