### ISSUE TITLE
General icon alignment and sizing problems

### ISSUE THREAD

**Issue by Wieltje** [OnsenUI/OnsenUI#1641]
Note: related to [#1636](https://github.com/OnsenUI/OnsenUI/issues/1636) but since this seems to be broader I made a new issue.

**Environment**
Onsen 2.01
Android 6

**Encountered problem**
Vertical alignment and sizing of the different icons is not the same (correct me if I'm wrong, but I would expect them to be the same). Can anybody have a look at this or explain me how this is meant to be used?

**How to reproduce**
See [this codepen](https://codepen.io/Wheelie/pen/Xjxrgd) and paste it to the [tutorial page](http://tutorial.onsen.io/) to see it in android.

**Comment by argelius** [comment]
You can reset the alignment with:

```
.ons-icon--ion {
  line-height: initial;
  vertical-align: initial;
}
```

I don't think we can remove this rule because it would cause icons to display incorrectly in a lot of apps.

About the size of the icons in the toolbar buttons, I think we can adjust them to be consistent regardless of the icon pack used. You can use `size` attribute to change it manually.

**Comment by Wieltje** [comment]
Thanks. I thought that one of the reasons for using ons-icon was consistency between the different icon sets but apparently at least the vertical alignment is just meant to be inconsistent by historic means?
