### ISSUE TITLE
Receiving a lot of errors for `stopAll`

### ISSUE THREAD

**Issue by claudioc** [OnsenUI/OnsenUI#1672]
__Environment__
Onsen 2.0.3
iOS 10.x.x
WKWebView

__Encountered problem__
Using Track.js, I am seeing a lot of `undefined is not an object (evaluating 'n.stopAll')` apparently in iOS 10.x. The "undefined" in this case seems to be `this.animator`.

The application is running inside a WKWebView

Is this something known?

__How to reproduce__
I don't know, at the moment

**Comment by asial-matagawa** [comment]
@claudioc 
Thank you for reporting!
I will investigate this issue.

**Comment by claudioc** [comment]
Amazing, guys. Thanks for the quick fix :D

Looking forward to the deployment

**Comment by anatoo** [comment]
@claudioc Sorry, I just mistook issue number. That commit(66eeb48) fix #1654 not this issue.

**Comment by davidmathlogic** [comment]
I'm trying to run the Onsen UI v2 JS Navigation template on the Monaca Cloud IDE with no modifications. I'm running the app in the Monaca Debugger on Android 4.4.2. 

When I press the "Push Page" button, the phone logs the error "Uncaught TypeError: Cannot call method 'stopAll' of undefined," citing onsenui.min.js:11. 

In case it's related, on initialization I also get the following error: "Uncaught TypeError: Object #<PageElement> has no method 'matches'." This error is caused by the event listener that listens for 'init'. The error is that event.target returns "HTMLUnknownElement," which has no "matches" method. (But event.target.id still correctly returns the id of the page.)

**Comment by claudioc** [comment]
In my case the problem is triggered by using the `ripple` effect on buttons. Removed the effect, removed the problem

**Comment by frankdiox** [comment]
Example for this error: https://community.onsen.io/topic/1106/ripple-attribute-does-not-work-on-safari
