### ISSUE TITLE
Event handling is centralized

### ISSUE THREAD

**Issue by nodefish** [OnsenUI/OnsenUI#1697]
The docs for `ons-tabbar` events are a bit misleading: https://onsen.io/v2/docs/js/ons-tabbar.html#event-prechange.

Someone who reads these docs will assume that `prechange` is an event that occurs in a specific `ons-tabbar` and would do something like `my_tabbar.addEventListener('prechange', function(){...})`. In fact, this will work when you only have 1 tabbar.

But the event listener actually fires for *all* instantiated tabbars. So the proper approach is more like `document.addEventListener('prechange', function(){...})` and inside the handler, you have to check the `event.target.id` to make sure which `ons-tabbar` fired the event.

This model is quite different to standard html/js, where each element would have its own `onclick` for example.

The same can be said for `ons-page`, etc. Alternatively, wouldn't decentralizing events be a good idea to pursue? I feel like it's better practice than centralized events (and if you really want it to be centralized, with a decentralized architecture you can simply assign the same handler to multiple elements).

**Comment by frankdiox** [comment]
@nodefish Do you mean you'd like to have something like `'init:pageID'` event names? Is there any limitation with the current approach?

I think adding a listener to every element could be troublesome (especially speaking about pages in a navigator). It's simpler to just set the listener in the navigator itself or the document and then filter by ID or something else.

Same for the other events, if you just want a listener to be triggered by a specific tabbar, then add the listener to that tabbar instead of the document. You can also stop propagation there so the event does not bubble.

I guess it could be possible to fire both `init` and `init:pageID` (for example) at the same time and let the developer choose, but I don't see it as a necessary feature/fix. What do you think, @argelius ?

**Comment by nodefish** [comment]
@frankdiox 

* for `ons-page`: in theory, what I'm saying is the event name could still be `init` but the listener would be definable on the `ons-page` itself - key word being `definable`. And then if you want to centralize all pages' `init` events on the `navigator` which I agree is a good practice, then you would define the handler on `navigator` and the events would bubble up from `ons-page`. However, I don't have a problem personally with `ons-page` being like this. It's more of a "devil's advocate" question involving events overall.

* I'm not 100% sure if a code change or a documentation change is what I want to suggest. I just recall being a bit confused when I had more than 1 `ons-tabbar` in my app (nested), and I wanted an event handler for only the outer one. It wasn't a huge problem to fix it (just use `event.target.id` in a `switch` statement), but it seemed to work a bit differently than I expected.

What's unclear to me is if I write `my_tabbar.addEventListener('prechange', function(){...})`, then this event also fires for any other `ons-tabbar` in my project that is nested under the first tabbar (i.e. inside one of the tabbar's pages), even if I didn't assign a listener to the nested `ons-tabbar`. So it behaves exactly the same as if I wrote `document.addEventListener('prechange', function(){...})`. That's what's confusing to me, I thought I could set a listener on the outer `ons-tabbar` only.

As far as I know, bubbling should only happen if both the nested element and its parent have handlers registered for that event, and yet I only assigned a handler in one of them (outermost one in my case). I guess now, thinking about this, that even if I didn't specify a handler in both elements, Onsen UI probably adds handlers to all `ons-` elements behind the scenes, and these events bubble.

In that case, I'm not sure if anything needs to be done.

Some additional thoughts:

What if you have different kinds of elements which use the same event names? For example, if we have an `ons-carousel` nested inside an `ons-tabbar` page: both of them have a `postchange` event, so if the `ons-carousel` fires postchange by default (just like my inner tabbar for which I did not define a handler) and it bubbles up, would that fire the `tabbar` postchange? That seems a bit messy.

**Comment by frankdiox** [comment]
@nodefish Sorry for the late reply. I'll try to answer here:

>for ons-page: in theory, what I'm saying is the event name could still be init but the listener would be definable on the ons-page itself - key word being definable. And then if you want to centralize all pages' init events on the navigator which I agree is a good practice, then you would define the handler on navigator and the events would bubble up from ons-page. However, I don't have a problem personally with ons-page being like this. It's more of a "devil's advocate" question involving events overall.

`ons-page` is a template (just a string) until it is actually created, so there is no way to set a handler before that. The only possibility would be to pass a "controller" or "initializer"  function to things like `pushPage` or setting an attribute in the template that points to a global function (`<ons-page init="window.fn">`. I don't like too much any of those solutions and I don't really see why that could be better than using bubbling events as we have always done in HTML/JS. The only thing you need to know is that `event` object contains the target element that originally fired the event, so you can check its ID, tag name or use the element itself directly.

>I'm not 100% sure if a code change or a documentation change is what I want to suggest. I just recall being a bit confused when I had more than 1 ons-tabbar in my app (nested), and I wanted an event handler for only the outer one. It wasn't a huge problem to fix it (just use event.target.id in a switch statement), but it seemed to work a bit differently than I expected.

I think in all the examples of `init` event with more than 1 page we check `event.target.id`. For the other components it should be similar. I guess you can also do something like `event.stopPropagation()` in the inner tabbar.

>As far as I know, bubbling should only happen if both the nested element and its parent have handlers registered for that event, and yet I only assigned a handler in one of them (outermost one in my case). I guess now, thinking about this, that even if I didn't specify a handler in both elements, Onsen UI probably adds handlers to all ons- elements behind the scenes, and these events bubble.

I think bubbling should always happen, otherwise the components need to be aware of all their parents/children and we don't want to have this kind of dependency. They should be completely independent from each other in general. In normal HTML/JS, events bubble regardless the parents/children so I don't really see the need of changing this. Also, Onsen UI is not adding listeners for the common exposed events, only for inner stuff.

>What if you have different kinds of elements which use the same event names? For example, if we have an ons-carousel nested inside an ons-tabbar page: both of them have a postchange event, so if the ons-carousel fires postchange by default and it bubbles up (just like my previous example's inner tabbar, for which I did not define a handler, fires and bubbles up prechange) , would that fire the tabbar postchange event? That seems a bit messy.

I agree on the fact that having similar event names for different components is not very nice (I guess it's late to change that due to BC). However, this is again handled exactly in the same way: by checking the `event` object. I mean, we expect developers to use that object like in any normal event, it's not just a "trick" (these are ["normal" events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) as well).

If you think any particular item in the docs is unclear after this, please indicate it or open a PR. Thanks!

**Comment by nodefish** [comment]
It's been a while since this post and I've since come to realize that what confused me was the simple fact that one usually would explicitly specify when events fire (e.g. `onclick='whatever'`), whereas Onsen UI elements would implicitly fire events. This is normal since Onsen UI is a library of premade components, but somehow it eluded me that things would emit events without me specifying them (temporary brain fail :)). That and the event names being the same for different components threw me off a bit.

But your explanation makes perfect sense and I think you're right, there's no issue here. The lack of event namespacing is a limitation of js, not Onsen UI (unless you want to rename same-name events to like `carousel-postchange`, but that's entirely up to you and Onsen UI is correct either way).

Thanks for your well thought out reply. I'll close this issue.

**Comment by iTiaNex** [comment]
i click a link or button to a new page, when  swipe (or click back button) to return former page,it will always trigger the click event  again,could anyone tell me how to resolve it ?
thanks

**Comment by asialgearoid** [comment]
@iTiaNex Please don't comment on very old closed issues. If there is a bug, please open a new issue. Otherwise you can try posting on the [Onsen Community](https://community.onsen.io/).
