### ISSUE TITLE
Sending custom data to new page issue

### ISSUE THREAD

**Issue by TheSegfault** [OnsenUI/OnsenUI#1793]
Example: [Sending custom data to a new page]( https://onsen.io/v2/docs/angular1/ons-navigator.html#tutorial) data isn't available in the controller but only in the DOM.

>    controller:  console.log("Data:", app.navi.topPage.data); // undefined
>     html:  {{app.navi.topPage.data}} //display my data

I think I'm missing something (💃  💃 )

Angular 1.5.8
Onsen v2

**Comment by puku0x** [comment]
You should use 'pushedOptions' to get the page arguments when you are using Angular 1.

```
var args = navi.topPage.pushedOptions; // Not documented yet
var title = args.title;                // For example
```

Moreover, you should **not** use Onsen UI 2.0.5 with Angular 1.
It has a terrible bug in the navigator component, it's better to use **2.0.4** with Angular 1.

**Comment by frankdiox** [comment]
@TheSegfault That's probably because probably the page is not ready by the time you print it. Try to use `$timeout(..., 0);` just to check it. The page will be ready on `init` event, so you could use `ons-init` handler. It would be nice if the controller runs once the page is ready, like in v1 I think.
@puku0x What's the terrible bug? Also, `pushedOptions` is not documented because it could be removed, that's why `data` is there. Isn't it enough?

**Comment by puku0x** [comment]
Thank you @frankdiox for your advice.

Unfortunately, I could not find  the `data` field in `topPage` object  in angular-onsenui since  **Beta.10** .

And have you ever tried 2.0.5 with Angular 1 ?
- `<ons-template>` is broken (since **RC.18** ?)
- `topPage.pushedOptions` returns previous page's one (in **2.0.5**)

I wrote a pen, this will show the reason why I said it terrible.
http://codepen.io/puku0x/pen/OWyQry
(It does not work well on Chrome because of the `<ons-template>` bug, please use **Firefox**)

**Comment by frankdiox** [comment]
@puku0x The bug with `ons-template` is due to the fact that Codepen inserts the external files at the bottom of the BODY rather than in the HEAD. We fixed this some time ago but perhaps something has changed in Chrome and it's broken again.

About the other issues, it's all related to what I answer to the original post. It's a timing issue, you are saving something into `vm.title` that doesn't exist in that moment. If you use `ons-init` handler you can make sure everything is there.We should delay the controller somehow until the page is ready, though. I fixed everything here: https://codepen.io/frankdiox/pen/ZLrzvN

**Comment by puku0x** [comment]
A-ha ! That's what I wanted !
Thank you very much, @frankdiox !

**Comment by frankdiox** [comment]
@puku0x Glad I could help! :)

**Comment by TheSegfault** [comment]
Thanks for the ons-init advice ! Problem solved =)

**Comment by frandiox** [comment]
From next release (probably 2.3.0), this behavior will be changed back to 2.0.4 :)

**Comment by puku0x** [comment]
@frandiox Wow, it sounds good !

Sometimes I stacked because ons-init called my initialize function two or three times when a page was loaded.
