### ISSUE TITLE
"lift" & "lift-ios" animation affects current page's toolbar

### ISSUE THREAD

**Issue by nodefish** [OnsenUI/OnsenUI#1795]
__Environment__ 

```
[Core]
    Onsen UI 2.0.5

[Platform]
    Mobile - iOS 10.1.1 + Cordova
    Desktop - Windows 10 + Chrome or Firefox
```
__Encountered problem__

Using `navigator.pushPage` with the `lift` or `lift-ios` animation specified causes the toolbar of the current page to move upwards. This looks particularly buggy when using colored toolbars and a colored iOS status bar, in which case this issue becomes quite apparent.

__How to reproduce__

Simply use `lift` or `lift-ios` in the basic `navigator` tutorial code, and note that the `Page 1` toolbar moves upwards upon changing pages.

https://codepen.io/anon/pen/dNdGvL?&editors=101

**Comment by frankdiox** [comment]
@nodefish I believe the animation was made like that on purpose. The whole previous page moves upwards, not only the toolbar. To be honest I haven't seen it with colored iOS status bar. In any case, since 2.0.5 it's quite easy to [make new animations or extend existing ones](https://onsen.io/v2/docs/guide/js/#extending-animations), so you can simply make your own lift animation if you don't like the current one. Probably it's easier to extend `lift-md` and modify the background mask.

**Comment by nodefish** [comment]
I see. I checked out some native iOS apps and their animation isn't like that, so I figured it was a bug.

I'll look into custom animations. Thanks for the tip!

**Comment by frankdiox** [comment]
@nodefish Oh, maybe we should check how's the native one then. I haven't seen may "lift" animations in iOS actually so I'm not sure about it. I'm opening this again as a reminder :)

**Comment by ldenoue** [comment]
it's actually ugly the way it's implemented now. on iOS when a new viewcontroller appears, it slides above the current view without moving the views underneath. How could I achieve that with onsen? Perhaps using a modal dialog?
