### ISSUE TITLE
ons-splitter in ons-navigator bug on Safari

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#1801]
__Environment__ 

```
[Core]
    Onsen UI 2.1.0

[Framework]
    Angular 1.5.9

[Framework binding]
    angular-onsenui 2.1.0

[Additional libraries]
    None

[Platform]
    Mobile - iOS 10.1.1
    Desktop - macOS Sierra

[Browser]
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__

`<ons-splitter-content>` and `<ons-splitter-side>` are broken when they are in `<ons-navigator>` .

__How to reproduce__

Please refer to this.
http://codepen.io/puku0x/pen/JEvpQP

**Comment by asial-matagawa** [comment]
@puku0x 
Thank you for reporting.

Actually I think this is not a bug since `ons-template` cannot be nested, that is, `ons-template` elements cannot include child `ons-template` elements:

>However, having multiple pages declared in the same file is sometimes more convenient.
ons-template component is the solution for this.
>You can create as many pages as you need **in your index.html (there and only there)** by using this component.

https://onsen.io/v2/docs/guide/js/#templates

Once you move inner `ons-template` elements to outside of the root `ons-template`, it will work fine.

But we should warn a user when `ons-template` is located in `ons-template`, so I will add `console.warn` to `ons-template` in the core.
Thank you!
