### ISSUE TITLE
Vue | Page issue: This is just a test issue.

### ISSUE THREAD

**Issue by frandiox** [OnsenUI/OnsenUI#1813]
__Environment__

```
[Core]
  onsenui 2.1.0
  
[Framework]
  vue 2.1.10

[Framework binding]
 vue-onsenui 2.0.0-alpha.0

[Platform]
  Desktop - Linux 64-bit

[Browser]
  Desktop - Chrome 55.0.2883.75 on Linux 64-bit
```

__Encountered problem__
  
  This is just a test. Please ignore it.

__How to reproduce__

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<template id="main">
  <v-ons-page>
    <v-ons-toolbar>
      <div class="center">My app</div>
    </v-ons-toolbar>

    <p style="text-align: center">
      <v-ons-button @click="alert">Click</v-ons-button>
    </p>
  </v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
new Vue({
  el: '#app',
  template: '#main',
  methods: {
    alert() {
      this.$notification.alert('Hello World!');
    }
  }
});
```

**Comment by frankdiox** [comment]
@anatoo @asial-matagawa @misterjunio @masahirotanaka I'm testing a new way to report issues. This is an issue generated from the [tutorial app](https://tutorial.onsen.io/). We should redirect users to the tutorial app if they want to report a bug so they can reproduce the error there first. It gets the latest released version so we ensure the bug wasn't already fixed in new versions.

This generated issue has a link to the tutorial that **only** works when the issue has been created, not when it's still a template.

Opinions?

**Comment by masahirotanaka** [comment]
Yes, I think this is a good way for reporting issue. Thanks @frankdiox!

**Comment by anatoo** [comment]
![image](https://cloud.githubusercontent.com/assets/59784/22962105/37343450-f38e-11e6-9e97-af91ad95ae81.png)

**Comment by misterjunio** [comment]
@frankdiox That's very cool. A suggestion though: maybe we should create a "sandbox" page in the tutorial app, just to guarantee users don't get confused about having to reproduce their issue in a "tutorial"

**Comment by frankdiox** [comment]
@misterjunio Maybe just writing `Select template` in the title instead of `Select tutorial` is enough... I think it's easier if they start from an existing template than from a specific empty page to report bugs. But yeah, it could be confusing...

**Comment by misterjunio** [comment]
@frandiox Close this maybe? 😏

**Comment by frandiox** [comment]
;_;
