### ISSUE TITLE
Proposal: Removing <ons-template> and prefer <template> elements.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1814]
`template` elements can nest HTML templates properly but `ons-template` is inconvenient on nested templates. 
Why did we add ons-template? 
I want to make `ons-template` deprecated and prefer `template` elements.

@masahirotanaka @frankdiox @asial-matagawa @misterjunio Any thoughts?

**Comment by frankdiox** [comment]
I've mentioned about this several times so I completely agree.

>Why did we add ons-template?

I guess Android < 4.4 and IE have something to do with it: http://caniuse.com/#feat=template

We can use a polyfill for those versions if it's completely necessary, although we don't officially support them anymore.

Furthermore, I've tested it and looks like possible to do:

```
<template>
  elements here
  <script>
     code here
  </script>
</template>
```

I think that could be very nice in some situations. Many users are confused because `<script>` tag doesn't work in `<ons-template>` or separate files.

**Comment by BusinessLoader** [comment]
Possibility for include `<script>` in the template will be very useful!

**Comment by frandiox** [comment]
Implemented in master branch. `<script>` tags are supported through page life-cycle hooks :+1:
