### ISSUE TITLE
angular2 karma start, PhantomJS error

### ISSUE THREAD

**Issue by Seraphims** [OnsenUI/OnsenUI#1825]
hello,
I use angular2-onsenui,when I use npm test, I use karma, browsers is PhantomJS, I get the error:
<img width="880" alt="error" src="https://cloud.githubusercontent.com/assets/6078029/23060747/07cdcf52-f53a-11e6-8862-392c331251f9.png">
17 02 2017 17:48:00.391:WARN [karma]: No captured browser, open http://localhost:9876/
17 02 2017 17:48:00.407:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
17 02 2017 17:48:00.408:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
17 02 2017 17:48:00.467:INFO [launcher]: Starting browser PhantomJS
17 02 2017 17:48:01.211:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket z1KnlHQIkS9fiVeDAAAA with id 73086834
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: Attempting to define property on object that is not extensible.
  at node_modules/onsenui/js/onsenui.js:44

PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: Attempting to define property on object that is not extensible.
  at node_modules/onsenui/js/onsenui.js:44

How do I solve，thanks

**Comment by frandiox** [comment]
@Seraphims PhantomJS does not implement recent web APIs so it's not possible to test things like Web Components with it. If you want to try a headless browser, try the new [headless chrome](https://developers.google.com/web/updates/2017/04/headless-chrome). It is supported in Karma since v2.1.0. We are [using it](https://github.com/OnsenUI/OnsenUI/blob/master/core/test/unit/karma.conf.js#L88) for unit tests in Onsen UI core.
