### ISSUE TITLE
Running "monaca preview" on windows doesnt load css into the website

### ISSUE THREAD

**Issue by vajura** [OnsenUI/OnsenUI#1975]
__Environment__ 

```
[Core]
    onsenui 2.1.0

[Framework]
    angular2 2.2.4

[Framework binding]
    angular2-onsenui 1.0.0-rc.5

[Additional libraries]
    none

[Platform]
    Desktop - Windows 10

[Browser]
```

__Encountered problem__
Following this tutorial https://onsen.io/getting-started/ trying to run a sample project on windows 10 after creating a preview of it the site doesnt load the correct css on the button http://imgur.com/a/efegB , on internet explorer the site isnt shown at all. It works fine if its run in linux or ios. Also if i use remote build for android and install the android app the app is in a wrong design yet again.

__How to reproduce__
Follow the tutorial on windows

**Comment by asial-matagawa** [comment]
@vajura 
Thank you for reporting!

Since Onsen UI is a UI framework for mobile browsers, Internet Explorer is not supported in the current version (`2.2.5`).
Please check `Browser Support` section of README.md:
https://github.com/OnsenUI/OnsenUI#browser-support

>Also if i use remote build for android and install the android app the app is in a wrong design yet again.

We would like to investigate this problem but it requires more information about your environments such as Android OS version.
Note that Android 4.4.3 and older versions are not supported.
