### ISSUE TITLE
Obsolete FastClick.

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#2000]
@frandiox @anatoo @misterjunio 
`onsenui@2.2.6` uses [FastClick](https://github.com/ftlabs/fastclick) 1.0.6 but FastClick is no longer maintained and causes numerous issues on newer versions of Android and iOS.
We must replace FastClick with a library which has the same functionality.

**Comment by anatoo** [comment]
How about using [native solutions](https://patrickhlauke.github.io/touch/tests/results/#suppressing-300ms-delay)?  For instance, we can use `touch-action: manipulation`. 
It should be OK for newer versions of Android and iOS.

**Comment by asial-matagawa** [comment]
@anatoo
It sounds good but we have to support at least iOS 8+ and Android 4.4.4+.
Can we support those old browsers with that native solutions?

**Comment by anatoo** [comment]
For older versions, we can use FastClick as before.

**Comment by frandiox** [comment]
There is also [HammerTime](https://github.com/hammerjs/hammer-time), which ""polyfills"" `touch-action`. However, it has to be added to the style attribute so I'm not sure if we can use it.

**Comment by anatoo** [comment]
I investigated about this problem and `touch-action: manipulation` and so on.

### Android

In Android4.4+ WebView and browser, we can remove click delay by setting viewport properly(`user-scalable=no,width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1`). It's the same on newer versions.

So we can drop FastClick and it does not needed `touch-action` CSS property in Android platform.

### iOS

`touch-action` is introduced in iOS9.3. In iOS, things are a bit complicated.

 * UIWebView: UIWebView on iOS11 can parse `touch-action` CSS property, but that has no effect. Viewport settings also have no effect. So we have to use FastClick **always** on UIWebView. 
 * WKWebView: We can use `touch-action: manipulation` or viewport settings if it's supported. Otherwise we have to use FastClick.
 * Safari: We can use `touch-action: manipulation` if it's supported. Otherwise we have to use FastClick.
   * iOS9.3: But if the web page is launched from the home screen and have `<meta name="apple-mobile-web-app-capable" content="yes">`, the page is loaded by UIWebView and `touch-action: manipulation` and viewport settings to remove click delay has no effect. So we have to use FastClick in this case.

### Conclusion

In most cases, we can cover `touch-action: manipulation` and viewport settings to remove click delay.

On Android, it's OK to set viewport correctly. On iOS, we can use `touch-action: manipulation` and viewport settings that remove click delay if it's supported. But on UIWebView, we have to use FastClick as before.

@asial-matagawa @frandiox How do you think? If there are no problems, I will try to implement these logic.

**Comment by asial-matagawa** [comment]
@anatoo 
Thank you for investigating!
It is a pity that the problem still remains on iOS 11 UIWebView.

From my point of view, I think your suggestion is fine 👍

**Comment by frandiox** [comment]
@anatoo Thanks! I think it's fine to do that, yes. iOS makes everything so complex :sweat_smile: 

@asial-matagawa I think WKWebView can be used in Cordova since iOS 9. It was bugged in iOS 8 if I don't remember wrong...

**Comment by asial-matagawa** [comment]
>I think WKWebView can be used in Cordova since iOS 9.

**Comment by asial-matagawa** [comment]
@frandiox

**Comment by asial-matagawa** [comment]
@frandiox 
>I think WKWebView can be used in Cordova since iOS 9.

Yes, but the problem is most Cordova users don't know WKWebView and will use UIWebView as same as before...

**Comment by anatoo** [comment]
Ok I will create pull-request that fix this problems.

@asial-matagawa FYI: By the way, if FastClick cause a trouble in some cases, I think there is no needs to use `fastClick.destroy()`. You can just add `needsclick` to class attribute on the target element that have troubles. `needsclick` value disable FastClick on the target element. 
https://github.com/OnsenUI/OnsenUI/blob/master/core/src/vendor/FastClick%401.0.6%2Bmod/fastclick.js#L253

**Comment by asial-matagawa** [comment]
@anatoo

**Comment by asial-matagawa** [comment]
@anatoo 
Actually `needsclick` did not work in some environments 😓 
So I always recommend using `ons.fastClick.destroy()`

**Comment by anatoo** [comment]
@asial-matagawa Oh... 😇
