### ISSUE TITLE
Splitting "ons-input" component.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#2013]
Summary:

We should split `ons-input` component into several components.

Background:

We have `ons-input` component to handle user input  and developers can switch appearance and behavior by setting `type` attribute.

```html
<ons-input type="text" />
<ons-input type="checkbox" />
<ons-input type="search" />
```

But this does not make sense in Onsen UI because some components have unique feature (e.g label feature on `float` attribute and type=text) and these should not be mix together in `ons-input`. Current design of `ons-input` make hard to add unique feature on individual `ons-input` appearance.

Also `ons-input` name make hard to find when developers want to find Onsen UI checkbox element or radio button element or search input element.

So I think we should make individual input components as below like `ons-range` component and deprecate `ons-input` component.

*  `ons-text-input` that accept normal text, password and email format. 
*  `ons-checkbox`
*  `ons-radio-button`
*  `ons-search-input`

@frandiox @misterjunio @asial-matagawa @masahirotanaka Any thought?

**Comment by misterjunio** [comment]
I think that makes sense, my only concern is the name `ons-text-input` because there are [other types of inputs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_<input>_types) such as `file` or `image` that maybe users are making use of `ons-input` for and `ons-text-input` may be a bit misleading.

**Comment by anatoo** [comment]
@junio In that `type=file` or `type=image` cases, can it be just `input` elements instead of `ons-input`?

**Comment by anatoo** [comment]
@misterjunio  In that type=file or type=image cases, can it be just input elements instead of ons-input?

**Comment by misterjunio** [comment]
@anatoo sure but a user who is not aware of that may be looking for an `ons-input`. Idk, maybe I'm being pessimistic 😄  I guess it's fine

**Comment by frandiox** [comment]
I don't mind having `checkbox`, `radio` and `text` together in `ons-input` like until now (they have the same DOM). We could make `ons-search-input` in a different component.

Otherwise, if you really want to split them, I'd say `ons-checkbox`, `ons-radio`, `ons-input` and `ons-search`/`ons-search-input`.
