### ISSUE TITLE
Ons Modal Transitions?

### ISSUE THREAD

**Issue by tehg00se** [OnsenUI/OnsenUI#2021]
[Core]
    onsenui 2.1.0

[Framework]
    vue 2.1.10

[Framework binding]
    vue-onsenui 2.0.0-alpha.0

[Additional libraries]
    none

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)

__Encountered problem__
When attempting to add a Vue transition to a v-ons-modal component, the transition is ignored due to modal.show(), and the JS core functionality of Onsen.  Is there a way to add a transition to the v-ons-modal component, without digging into the core and modifying underlying code?

__How to reproduce__
Wrap <v-ons-modal> in a vue <transition>

**Comment by frandiox** [comment]
@tehg00se First of all, please try to update to a recent version of `onsenui` and `vue-onsenui`. Methods API is deprecated since `alpha.1`.
I the new API a modal can be shown with `:visible="modalVisible"`. This simply sets `display: table` or `display: none` to the modal. If you want to use a Vue transition, I think you can use something like `:visible="true" v-show="modalVisible"` and toggle `modalVisible` boolean variable.

**Comment by tehg00se** [comment]
Thank you frandiox, that worked.
