### ISSUE TITLE
Unexpected behavior of ons-lazy-repeat

### ISSUE THREAD

**Issue by cyciopes** [OnsenUI/OnsenUI#2031]
```
[Core]
    onsenui 2.3.0

[Framework]
    javascript

[Browser]
    Desktop - Chrome 58.0.3029.110
```

Hi guys, i found a unexpected behavior for me, it is about ons-lazy-repeat.
It will run createItemContent one time, even countItems return 0.
I am not sure if it is a bug or not, but it really bring me some trouble.

![2017-05-25 16_07_02-html5application - netbeans ide 8 2](https://cloud.githubusercontent.com/assets/21193224/26441747/474f001c-4164-11e7-96f8-08ae4f2fa9ef.png)

**Comment by frandiox** [comment]
@cyciopes Yes, it does. It tries to pre-calculate the height of the items by loading the first item and unloading it at the beginning. If you provide `calculateItemHeight` function it won't do this. This function should return an approximate value of the items height, it doesn't need to be 100% precise.

Apart from that, I think initializing the lazy repeat to 0 items is quite uncommon. Can't you want to initialize it  until you have something to display?
Also, instead of `ons.ready`, which only happens once in the app, you might prefer using [page's `init` event](https://onsen.io/v2/docs/guide/js/#page-lifecycle).

Feel free to open this again if you have anything else to add :)

**Comment by cyciopes** [comment]
@frandiox  Thanks your quick reply. I will hardcode something when pre-calculate. Thank you.
