### ISSUE TITLE
Core | Input issue: `transparent` modifier with `material`

### ISSUE THREAD

**Issue by misterjunio** [OnsenUI/OnsenUI#2077]
__Environment__

```
[Core]
  onsenui 2.4.0
  
[Platform]
  Desktop - OS X 10.12.5 64-bit

[Browser]
  Desktop - Chrome 58.0.3029.110 on OS X 10.12.5 64-bit
```

__Encountered problem__
The `transparent` modifier together with the `material` one causes a green background to appear on focus of the text input. I guess this is not the expected behavior?

__How to reproduce__
Link below. Check the `Android View` and tap the text input.

  [__Demo link__](https://tutorial.onsen.io/?issue)

- __HTML__

```html
<ons-page>
  <ons-toolbar>
    <div class="center">Input</div>
  </ons-toolbar>
  
  <ons-input modifier="transparent" placeholder="Text input" float></ons-input>
</ons-page>
```

- __JS__

```javascript

```

**Comment by frandiox** [comment]
@misterjunio I thought the autostyling should remove `transparent` but it actually doesn't. https://github.com/OnsenUI/OnsenUI/blob/master/core/src/ons/autostyle.js#L24

Perhaps it should remove it, I don't know how is a transparent input in MD...
Also, now that I think about it, `transparent` modifier doesn't make sense right now because it's the default style on iOS...

**Comment by misterjunio** [comment]
@frandiox yep the problem seems to originate from [this line](https://github.com/OnsenUI/OnsenUI/blob/master/css-components/src/components/text-input.css#L172) in the `material` modifier definition.

I agree the `transparent` one doesn't make sense. Looking at that same file all it does is applying the regular `--text-input`❓

**Comment by frandiox** [comment]
@misterjunio I removed `transparent`. Originally, the default input was different and the `transparent` modifier made sense, but not anymore.
