### ISSUE TITLE
VueJS tabbed example does not change title

### ISSUE THREAD

**Issue by italomaia** [OnsenUI/OnsenUI#2087]
Just created a clean project with the vue 2 tabbed template and, by the code, it seems the page title should change with the tab. It does not. The problem seems related to "@update" at v-ons-tabbar.

**Comment by italomaia** [comment]
Yeap, @update should be updated to @update:index. If I knew where the vuejs tabbed template is hosted, I could provide the PR.

**Comment by misterjunio** [comment]
@italomaia actually the preferred way is to `sync` the `index` prop, as done in the tutorial example that you can check in the [`<v-ons-tabbar>` reference page](https://onsen.io/v2/docs/vue/v-ons-tabbar.html). Please make sure you are using the latest version of `vue-onsenui`, or at least `2.0.0-beta.4`.

**Comment by frandiox** [comment]
@italomaia It's here: https://github.com/monaca-templates/onsenui-v2-vue-tabbar/blob/master/src/App.vue#L11

Looks like we forgot to update that template. As @misterjunio says it's enough with `:index.sync="activeIndex"` and completely removing `@update`. That's why we changed all the events from `update` to `update:propName`, to support the new `sync` modifier.

**Comment by frandiox** [comment]
It's been already fixed :)

**Comment by italomaia** [comment]
Thanks guys. Sorry for the late reply. 

Noted:

`:index.sync="activeIndex"`
