### ISSUE TITLE
Knockout binding ons-switch

### ISSUE THREAD

**Issue by Wieltje** [OnsenUI/OnsenUI#2095]
I'm using onsen combined with knockout.js, which works like a charm. There is however an issue with the ons-switch element, of which I think it's an issue in onsen.

I created a binding on the checked property of the switch. This does work when the switch is toggled by clicking, but it doesn't update when the switch is toggled by swiping.

See this codepen https://codepen.io/anon/pen/JJrvEY?editors=1010

**Comment by frandiox** [comment]
@Wieltje Hi! I've looked at how Knockout.js implements the `checked` binding and looks like they are using `click` event instead of `change`, I'm not sure why they do that. There is not `click` event when `ons-switch` is dragged and thus the model is not updated. I think this is something that should be fixed in KO, not in `ons-switch`.

As a workaround, try to use the [`event` binding](http://knockoutjs.com/documentation/event-binding.html) instead (`data-bind="event: { change: updateSwitch }"`) and manually apply the new value to the switch. Hope this helps!

**Comment by Wieltje** [comment]
@frandiox Many thanks for your suggestion. I'll have a look if there's a reason for this behaviour in knockout or if they just did not anticipate on programmatically controlled changes like the ons-switch does.

For now, the following workaround does exactly what I want:
`data-bind="checked: variable, event: { change: function(d,e){ variable(e.detail.value); } }"`
