### ISSUE TITLE
Page lifecycle hooks inside <template> are not running when calling onsNavigator.pushPage() for a same page more than once

### ISSUE THREAD

**Issue by frosdqy** [OnsenUI/OnsenUI#2122]
__Environment__ 

```
[Core]
    onsenui 2.5.0

[Framework]
    none

[Framework binding]
    none

[Additional libraries]
    none

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome 59.0.3071.115
```

__Encountered problem__
Page lifecycle hooks (`onInit` and `onShow`) inside `<template>` are not running when calling `onsNavigator.pushPage()` or `onsNavigator.resetToPage()` for a same page more than once. The script inside `<template>` is still running, but the lifecycle hooks are not running.

__How to reproduce__
Please try this fiddle: https://jsfiddle.net/xs0u83zp/
1. Open the Side Menu, then click "Reset to Page 2". We'll see 3 alerts ("Run Script", "Init", "Show")
2. Click "Reset to Page 2" or "Push Page 2". We'll only see 1 alert ("Run Script")

**Comment by frandiox** [comment]
@frosdqy Hi! This doesn't look like a bug, explanation here: You cannot have the same ID twice in the DOM because you'll only get the first match with `document.querySelector('#page2')`. Basically, you are setting `onInit` and `onShow` always on the same page (the first one). Try to use a class selector and get the last one. Or, alternatively if you are always using `ons-navigator`, `document.querySelector('#myNavigator').topPage.onInit...`.

**Comment by frosdqy** [comment]
Thanks so much @frandiox, it's working now. My bad, I wasn't realized that the first one is still there.
