### ISSUE TITLE
[vue]when <style> set scoped,can not set style in page__content

### ISSUE THREAD

**Issue by baixiaoyu2997** [OnsenUI/OnsenUI#2173]
vue:2.4.2
vue-onsenui:2.1.1
onsenui:2.5.3

dont's work:
```
<style lang="scss" scoped>
.page__content{
  color: blue;
}
```
work:
```
<style lang="scss">
.page__content{
  color: blue;
}
```
this is a Bug? (sorry for my english)

**Comment by frandiox** [comment]
@baixiaoyu2997 That would only work if you provide `<div class="page__content">...</div>` yourself. Otherwise, when Vue creates the random attributes to simulate scoped CSS, it won't find any `.page__content`. So no, it's not a bug :sweat_smile: 

Full version would be:

```
<v-ons-page>
  <v-ons-toolbar>...</v-ons-toolbar>

  <div class="page__content">
    Content here
  </div>
</v-ons-page>
```

You can also use `div class="content"`  and style `.content` instead of `.page__content.

**Comment by baixiaoyu2997** [comment]
@frandiox thanks for your time
