### ISSUE TITLE
Request: Replace ons-icon material font

### ISSUE THREAD

**Issue by bringmethecode** [OnsenUI/OnsenUI#2208]
Have you consider replacing the material design font used by ons-icon? I feel _Material Design Iconic Font_ is outdated and last update was 2 years ago, it is missing alot of new icons created by Google.

Google's icon font is more recent:
https://github.com/google/material-design-icons

Material Design Icons also has a webfont:
https://materialdesignicons.com/

Also, what are your thoughts of using SVGs over css fonts?

**Comment by frandiox** [comment]
@bringmethecode We certainly should update it. However, this is a breaking change for most apps using md icons because all the class names would be changed. For example, `md-edit` should be renamed to `md-pencil` and so on. I guess it's not something we can do for a minor version :/
Same for SVG, we cannot do it without huge breaking changes :sweat_smile:

**Comment by frandiox** [comment]
@bringmethecode In v2.8.0 you can remove default icon fonts by including `onsenui-core.css` instead of `onsenui.core`. Therefore, you can use your own icon packs and we don't make any breaking change :)

[More info](https://onsen.io/v2/guide/faq.html#how-can-i-use-custom-icon-packs).
