### ISSUE TITLE
Onsen UI can be loaded twice (via UMD and via ESM) since vue-onsenui 2.4.0

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#2259]
@frandiox (Cc: @masahirotanaka )

In the current version of `vue-onsenui` (2.4.2), this code loads only `onsenui/esm` and works well:
```js
import ons from 'onsenui/esm'
import VueOnsen from 'vue-onsenui' // loads `onsenui/esm` internally
```
but this code loads both of `onsenui` and `onsenui/esm` (and causes some unexpected problems):
```js
import ons from 'onsenui'
import VueOnsen from 'vue-onsenui' // loads `onsenui/esm` internally
```

For example, if both of `onsenui` and `onsenui/esm` are loaded, `ons-page#_deriveHooks` is called twice and this error happens:
![onsen_vue_error](https://user-images.githubusercontent.com/19771915/33125625-9a3a419e-cfc4-11e7-96b0-2591dff2f954.png)
)

This problem might have broken many existing projects using `vue-onsenui`.
Could you fix this problem when you can work on Onsen UI?

**Comment by frandiox** [comment]
@asial-matagawa I think that since the very beginning we have specified that `import ons from 'onsenui'` is not necessary:

>// JS import
import Vue from 'vue';
import VueOnsen from 'vue-onsenui'; // This already imports 'onsenui'
Vue.use(VueOnsen);

Therefore, I don't think this can be considered a breaking change?

>Could you fix this problem when you can work on Onsen UI?

In order to support ESM, every component must import its corresponding Custom Element. If we go back to using `onsenui` instead of `onsenui/esm` internally, Custom Elements would be imported twice (and that throws errors).
