### ISSUE TITLE
Custom Elements: `Element#attachShadow` was not patched

### ISSUE THREAD

**Issue by acrixl** [OnsenUI/OnsenUI#2268]
[Core]
    onsenui 2.8.2

[Framework]
    none

[Framework binding]
    none

[Additional libraries]
    none

[Platform]
    Mobile - Android 4.4.4

[Browser]
    Mobile - Android WebView (Cordova 7.1.0)

__Encountered problem__
   
Custom Elements: `Element#attachShadow` was not patched
Uncaught SyntaxError: Unexpected identifier

__How to reproduce__

run Kitchensink app on Adroid 4.4.4

i try to polyfilling it, but unsuccess

so i thing onsenui 2.8.2 not work on android 4.4.4 without some advanced polyfilling?

**Comment by asial-matagawa** [comment]
@acrixl 
>Custom Elements: Element#attachShadow was not patched

This is just a warning from the Custom Elements polyfill, so I do not think this is an issue.

`Custom Elements: Element#attachShadow was not patched` appears because Onsen UI does not load [Shadow DOM](https://www.w3.org/TR/shadow-dom/) polyfill before loading Custom Elements polyfill, but Shadow DOM is not needed for Onsen UI, so we are not going to include any Shadow DOM polyfill.

>Uncaught SyntaxError: Unexpected identifier

I think this error is caused by another reason. We will check it soon.

**Comment by acrixl** [comment]
this error from Node.js:74

**Comment by asial-matagawa** [comment]
@acrixl 
`Node.js` is a content of the Custom Elements polyfill.
https://github.com/webcomponents/custom-elements/blob/6ad9993949a4f25c05b50b27a031a2ebfc49df89/src/Patch/Node.js

**Comment by acrixl** [comment]
this trash come from onsenui.js

**Comment by acrixl** [comment]
i think polyfils trashers itsef not compatible with 4.4.4 anymore

**Comment by acrixl** [comment]
also about weakmap

from https://github.com/paulmillr/es6-shim

It is not possible to implement WeakMap in pure javascript. The es6-collections implementation doesn't hold values strongly, which is critical for the collection. es6-shim decided to not include an incorrect shim.

WeakMap has very unusual use-cases, so you probably won't need it at all (use simple Map instead).


so it time to crosswalk?
