### ISSUE TITLE
Bug of derived Hooks: onInit, onShow, onHide, onDestroy

### ISSUE THREAD

**Issue by oarsheo** [OnsenUI/OnsenUI#2270]
Vue + OnsenUI 
on version 2.7.2 - ok 
on version >2.8.0 - Bug of derived Hooks

![image](https://user-images.githubusercontent.com/26067179/33514972-cf66b8a0-d764-11e7-95a0-f2508c4c3ad6.png)

main.js
```
 new Vue({
                el: '#app',
                render: h => h(navigator),
...

```
navigator.vue
push page1

page1.vue
what could be the problem ?

**Comment by frandiox** [comment]
@oarsheo I think I know the problem. Your app is including Onsen UI twice (and trying to overwrite onInit, etc).

From vue-onsenui 2.4.0 to 2.4.2, it includes `onsenui/esm` instead of `onsenui` (different modules), so you should not manually include `onsenui` in your app. In Vue apps there is no need of including `onsenui` manually since it's done by `vue-onsenui`. You can use `this.$ons` instead of `ons` object, if that's what you need.

This will be restored in 2.4.3 and there will be a proper warning when Onsen UI is included twice (already in master branch). However, as I said before, there is still no need to manually include `onsenui`.
