### ISSUE TITLE
Landscape iPhone X

### ISSUE THREAD

**Issue by Ralpharoo** [OnsenUI/OnsenUI#2279]
Onsen fails to detect the iPhone X platform if the app is started in Landscape.

The ons.platform.isIPhoneX() function should include both portrait and landscape options ((h 812 && w 375) || (w 812 && h 375)).

Note; I was following [this](https://onsen.io/v2/guide/iphonex.html) and applying the setAttribute during the initial boot of my app. At the moment if the device is in landscape it does not add the setAttribute.

**Comment by asialgearoid** [comment]
@Ralpharoo Thanks for the report. I cannot reproduce this either in emulator or device. `ons.platform.isIPhoneX()` returns true for me on an iPhone X (11.2) whether started in portrait or landscape mode.

The `isIPhoneX()` function checks `window.screen.width === 375 && window.screen.height === 812`, but these do not change with orientation.`window.screen.width` will always equal `375` on an iPhone X, regardless of its orientation. So, I would expect this function to work correctly in both portrait and landscape.

Could you try reproducing this in a basic Cordova / Onsen UI project and see if it happens there?

**Comment by Ralpharoo** [comment]
Hi again. Thanks for looking at this.

You are right, I was testing this in Chrome's basic 'Emulated Devices' as an iPhone X. I've checked again and this reports the window.screen.width differently in portrait and landscape. 

I now have the physical device and it always shows correctly in the original code. 

I guess this depends how strict you want this check to be. For me, I've kept this patch in as I develop 80% browser, 20% on the device - therefore need to see the browser act as an iPhone X in all cases.

Cheers,

**Comment by asialgearoid** [comment]
Interesting, I can see the issue happening in Chrome now. The [CSS spec](https://drafts.csswg.org/cssom-view/#the-screen-interface) for `window.screen.width` and `window.screen.height` does not actually seem to specify what should happen when the screen orientation changes. I don't trust that Apple won't at some point decide to change this behaviour on iOS, since it isn't part of the spec.

I will add a check for landscape dimensions. It's a quick fix and will certainly be helpful for development scenarios, and cover us if Apple do change the behaviour of `window.screen`.
