### ISSUE TITLE
iOS Accessory Bar Tabbing

### ISSUE THREAD

**Issue by Ralpharoo** [OnsenUI/OnsenUI#2316]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
 iOS Safari + UIWebView + WKWebView
```

__Encountered problem__
When the keyboard accessory bar is available on iOS, you can tab between inputs on previous pages in the page stack. 

For inputting data into our application I was looking to use the Accessory bar for quicker / easier jumping between fields. 

For now I have hidden the bar instead on iPhone.  This bug is always present on iPad which always shows the tab icons in the top right of the keyboard.

__How to reproduce__
1. Navigate here on an iOS device in safari (or the PhoneGap developer app); [code](https://codepen.io/anon/pen/RxeWaQ)
2. Click the push page button
3. Click on the second input. When the keyboard opens you will have the accessory bar with the tab options to the left. They should be disabled as only one input is present however, you can tab back to the previous page's input and enter / edit text.

**Comment by asialgearoid** [comment]
Thanks for your detailed report as always, @Ralpharoo. It is much appreciated!

It looks like this issue was actually fixed yesterday while fixing #1992 and #2286. The usual behaviour of the navigation stack is that after the animation, the previous screen would be hidden. However, at some point in the past, this was changed to not hide them. I believe this was to help with the use of React time-travel debug tools. So, in your example, the input field on page 1 is still technically visible, just hidden behind page 2. That is why it is possible to tab to it.

Yesterday, @frandiox changed the behaviour back to set `display: none` on inactive pages (see https://github.com/OnsenUI/OnsenUI/pull/2311). From my testing, this fixes the tab issue as it correctly hides the inputs.

**Comment by Ralpharoo** [comment]
Hey @asialgearoid - Just checking this now and it seems to still be apparent when using inputs within ons-tabbar pages. iOS still lets you tab to an input on the next or previous page.

**Comment by asialgearoid** [comment]
Oh I didn't consider that scenario. I don't think we hide the tabs when they're not active, so the inputs would still be tabbable. Any ideas, @frandiox?

**Comment by Ralpharoo** [comment]
Whether it is of value or not, I applied a patch our end get this working. Beside disabling the control (which led to styling requirements), I couldn't find any way to disable an element through plain CSS so that the Accessory bar would not tab to it.

Best I could find was setting the element attribute 'tabindex' to -1 when their tab page was not active. You'll probably find a much better way :+1:

**Comment by frandiox** [comment]
@Ralpharoo You can try it with the latest development build :)

**Comment by Ralpharoo** [comment]
Thanks @frandiox - I have tried this but am getting some pretty ugly glitching when pushing pages containing a tabbar. 

Also when swiping back from a tabbar page, to a page with a tabbar - the page is blank during the swipe. When progamatically popping a page back, the page is always blank for a split second too and subsequently appears with a flicker.

Cheers

**Comment by frandiox** [comment]
@Ralpharoo Can't see flickerings anymore after the last commit :)

**Comment by Ralpharoo** [comment]
Working perfectly. Thanks @frandiox
