### ISSUE TITLE
ReactJS libraries don't seem to be up-to-date on npm

### ISSUE THREAD

**Issue by priand** [OnsenUI/OnsenUI#2321]
Environment: ReactJS

__Encountered problem__
The whole issue comes from onInfiniteScroll not working with the <Page> component. So I wanted to debug the problem. Here is what I found:

1- OnsenUI/react-onsenui master branch seems to be an old one, using onsen 1.x, and not onsen 2.0 as the readme.md says. Here is what the package.json contains:
  "name": "react-onsenui",
  "version": "1.0.3",

2- The core  OnsenUI/OnsenUI master branch also contains react related code. This one seems up-to-date. Is it the actual source code for react? It is currently confusing.
But it does not seems to be the one pushed to npm

3- The react-onsenui pulled from npm does not seem to be the latest
Example, in Page.js
From Github: OnsenUI\OnsenUI\bindings\react\src\components\Page.jsx
```
  componentDidMount() {
...    if (this.props.onDeviceBackButton instanceof Function) {
      node.onDeviceBackButton = this.props.onDeviceBackButton;
    }
    if (this.props.onInfiniteScroll instanceof Function) {
      node.onInfiniteScroll = this.props.onInfiniteScroll;
    }
  }

```
From npm:
```
  componentDidMount() {
...
    if (this.props.onDeviceBackButton instanceof Function) {
      node.onDeviceBackButton = this.props.onDeviceBackButton;
    }
  }

```
=> The infinite scroll code is not available.

__How to reproduce__
`npm i react-onsenui`
Look into node_modules\react-onsenui\src\components\Page.jsx
=> The code for infinite scroll is missing in componentDidMount(). Not surprisingly, it is also not in the packaged files under /dist.

**Comment by frandiox** [comment]
@priand Hi! As the readme of `OnsenUI/react-onsenui` says: `This package has been moved to the main Onsen UI repository.`. So yes, `OnsenUI/OnsenUI/bindings/react` is the current code. Now, have a look at the changelog: https://github.com/OnsenUI/OnsenUI/blob/master/bindings/react/CHANGELOG.md

`onInfiniteScroll` is the only change in master branch since the last release, hence the difference with the last version of NPM. We will release a new version for everything probably next week. If you want something 'now', then check the latest development build: https://github.com/OnsenUI/OnsenUI#get-onsen-ui :+1:
