### ISSUE TITLE
Spec: ons-list-item accordion

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/OnsenUI#2380]
Related issues: #1955 

@OnsenUI/members 

This is a proposal for adding an accordion feature to ons-list-item, so that a list item can be expanded to show hidden content.

# DOM Structure

At the moment, ons-list-item is composed of three inner divs (left, center and right):

```HTML
<ons-list-item>
  <div class="left">left stuff</div>
  <div class="center">center stuff</div>
  <div class="right">right stuff</div>
</ons-list-item>
```

One option would be to add a fourth div for the accordion content:

```HTML
<ons-list-item>
  <div class="left">left stuff</div>
  <div class="center">center stuff</div>
  <div class="right">right stuff</div>
  <div class="accordion">accordion stuff</div>
</ons-list-item>
```

This has the advantage that it is very similar to the way ons-list-item currently works.

Alternatively, we could have a new accordion attribute for ons-list-item and specify the accordion content in a new custom element:

```HTML
<ons-list-item accordion>
  Normal content
  <ons-list-item-accordion>Expanded content</ons-list-item-accordion>
</ons-list-item>
```

The expanded content should be basically free-form.

# API

I think we need to at least have `show` and `hide` methods, similar to the dialog methods. The dialog methods also fire `prehide`, `posthide`, `preshow`, and `postshow` events, although I don't know whether they would be useful or not for an accordion.

# Other

The accordion will need animation when it gets expanded or contracted.

I'll also need to add a way to put an arrow on the list item to indicate whether the item is expanded or contracted.

**Comment by asialgearoid** [comment]
To me, the name `accordion` applies to a whole list in which each item is expandable. Since this will be per-item, I suggest we use the name `expandable`.

For implementation, I like a combination of the two approaches you mentioned. `ons-list-item` would have an attribute called `expandable`. Then inside this, we have `div.expandable-content`, which is shown and hidden as necessary.

```
<ons-list-item accordion>
  <div class="left">left stuff</div>
  <div class="center">center stuff</div>
  <div class="right">right stuff</div>
  <div class="expandable-content">accordion stuff</div>
</ons-list-item>
```

For the arrow, you could use `div.right`. In the case that the user already has that element, it should not be modified.

I don't think we need events for this, but the `show` and `hide` methods would be useful.

Something else to consider is how this will typically be used. The user will tap on the item to expand the panel. But to close it, clicks inside `expandable-content` should not do anything.

Overall, I think this component would be quite useful. :+1:
