### ISSUE TITLE
【Rookie for help】Error using esm

### ISSUE THREAD

**Issue by moonlitnighta** [OnsenUI/OnsenUI#2397]
![image](https://user-images.githubusercontent.com/22231630/38716212-1b295a9e-3f12-11e8-94e7-5f0d4576cae5.png)

![image](https://user-images.githubusercontent.com/22231630/38716478-97ce795c-3f13-11e8-8440-1c53d7b5248d.png)

First of all, thanks to the author, let me this kind of rookie can create a beautiful and efficient application. I introduced ESM in my project and he got an error while compiling, Is my practice wrong?

**Comment by asialgearoid** [comment]
@moonlitnighta What tool are you using to import the modules? Is it Webpack? Perhaps there is an error with your configuration there.

**Comment by moonlitnighta** [comment]
@asialgearoid Thank you

I use 'webpack'.

It seems that because my babel forbids 'node_modules', I should add 'node_modules/onsenui' to babel, but at the same time I have to exclude other things from 'node_modules' and now I don't know how to write.
![image](https://user-images.githubusercontent.com/22231630/38856239-7f737324-4258-11e8-8805-bcf0153ec87c.png)

This write does not take effect '0--0'

**Comment by asialgearoid** [comment]
@moonlitnighta I don't think that is the correct section to change. Babel is used to transpile your code, but it does not actually handle the importing. The `exclude` in that section just means that Babel won't transpile any files in `node_modules`.

You probably need to add a `resolve` section to your webpack configuration so that it will look for imports from there. For example, to build our Angular 2 bindings, we have this in our configuration:

```
  resolve: {
    modules: [
      'node_modules',
    ],
    extensions: ['.js', '.ts']
  },
```

I am not a Webpack expert, but I think this should do it. However, since this is not specifically an issue with Onsen UI, I am going to close the issue. If you need more help, take a look at our [Community forum](https://community.onsen.io/) and [Discord channel](https://discordapp.com/channels/415288814475542540/415288814911619084).
