### ISSUE TITLE
expandable ons-list-item with ng-repeat not working

### ISSUE THREAD

**Issue by pixelgroup-israel** [OnsenUI/OnsenUI#2434]
__Environment__

Onsen UI Version:
2.10.0
- 

Framework:
AngularJS 1.6.9
- 

Framework binding:
None
- 

Additional libraries:
None
- 

Platform:
Windows 10 Chrome 
- 

__Encountered problem__
When using the new expandable options on ons-list-item, ng-repeat will no longer work.
The cause is the new div inside the item: <div class="expandable-content">
When you remove this div the ng-repeat will work again (off-course without the expandable option)

In the console I'm getting the following error:
TypeError: Cannot read property 'childNodes' of undefined

__How to reproduce__
Just create an expandable list with ng-repeat.

**Comment by asialgearoid** [comment]
@pixelgroup-israel Thanks for the report. It turns out this is not specifically an issue with the binding, but the core itself. If an expandable list item's `compile` is called more than once, it causes issues. `ng-repeat` is an exact scenario where this happens. I have fixed it and will release it with `2.10.1` which should be out later today.
