### ISSUE TITLE
v-ons-lazy-repeat is user-hostile

### ISSUE THREAD

**Issue by mamcx** [OnsenUI/OnsenUI#2437]
I'm evaluation onsen/vue for a new project. I try to show data dynamically from a sqlite database, so I pick v-ons-lazy-repeat . However, it clearly is not user friendly. It have a weird API that is not on-par with rest of onsen.

I try this:

```
  	<link rel="stylesheet" href="css/onsenui.css">
  	<link rel="stylesheet" href="css/onsen-css-components.css">
    
    <script src="js/vue.js"></script>
    <script src="js/onsenui.js"></script>
    <script src="js/vue-onsenui.js"></script>

const cellcustomer = {
  template: '#cellCustomer',
  props: ['title']
};

const ListCustomersPage = {
  key: 'ListCustomersPage',
  template: '#ListCustomersPage',
  components: { toolbar, cellcustomer },
  data() {
    return {
      title: 'Select Customer',
    }
  },
  methods: {
    push() {
      
    }
  }
};

<template id="cellCustomer">
  <v-ons-list-item modifier="chevron" tappable>{{title}}</v-ons-list-item>
</template>

<template id="ListCustomersPage">
  <v-ons-page>
    <toolbar :title="title" :action="push"></toolbar>

    <v-ons-list>
       <cellcustomer title="Hello"></cellcustomer>
    </v-ons-list>

  </v-ons-page>
</template>
```

Is feel weird that I need to compile manually the template into a new VUE instance, instead of refer to a template and use v-for or similar.

The setup for render function is super-weird for me. I can't figure how inject data/render into the component without break the compilation. The sample expect to work in the root Vue instance.

The expectation is just have in "data" in the page the array or similar and then a render that pass the position on the list. Similar how UITableView work on iOS.

**Comment by asialgearoid** [comment]
@mamcx Your example doesn't use `v-ons-lazy-repeat` at all?

Generally speaking though, `v-ons-list` is recommended unless you have many hundreds of items. The performance difference is typically not noticeable, and it is much more flexible.

**Comment by mamcx** [comment]
> Your example doesn't use v-ons-lazy-repeat at all?

The thing is that I don't know how do that without pass the template as a string and not using components.

**Comment by asialgearoid** [comment]
Each item in `v-ons-lazy-repeat` must be a separate component. It is not possible for use `v-for`. For a list of 20,000 items, `v-for` would generate all 20,000 items and put them in the DOM. In the case of a normal `v-ons-list-item`, that would work, but would be incredibly slow.

The purpose of `v-ons-lazy-repeat` is to only put as many elements in the DOM as are required to fill up the screen. So, it puts maybe 10 items in the DOM instead of 20,000. When an item scrolls off screen, it is removed from the DOM. If you used `v-for`, it would not be possible to do this. When an item is about to appear on screen, `renderItem` is called with the index of the item. You then can use this index to determine which item to render.

I suggest taking a look at the [example on the Playground](https://onsen.io/playground/?framework=vue&category=reference&module=lazy-repeat), and editing it to see how you can apply it to your case.

**Comment by mamcx** [comment]
I understand the purpose of this. I say that is not the best API to use it, IMHO.

Take for example:

https://vuetifyjs.com/en/components/data-iterator

---

I try to take the playground example already. I not make it work. Probably if try harder... but this is the point. Ideally, the API must look alike a regular list, with minimal differences.

**Comment by asialgearoid** [comment]
Ah, I see. Unfortunately we don't have any plan to implement that kind of functionality at the moment, as it would take some time and increase the complexity of `v-ons-lazy-repeat`. However, PRs are always welcome if you are interested!
