### ISSUE TITLE
Empty angular-onsenui.min.js in 2.10.2

### ISSUE THREAD

**Issue by niboan** [OnsenUI/OnsenUI#2468]
I'm not sure if this is the right place, but I can't open issues in the OnsenUI-dist
 repo.

In the latest release, 2.10.2, the file `angular-onsenui.min.js` is empty.
In 2.10.1, it seems OK.

You could argue that it's just very well minified, but I doubt it will work ;-)

**Comment by emccorson** [comment]
I can confirm that `angular-onsenui.min.js` is indeed empty.

Thanks for the issue - that's a great spot.

Not sure why this happened yet. I'll look into it further.

**Comment by asialgearoid** [comment]
@niboan I have released onsenui@2.10.3 with the Angular bindings correctly minified. I have checked manually to make sure of it!

I'm not sure why 2.10.2 has an empty file. It could have been due to an error in the release process which was not caught. I have updated our release scripts to make it much more likely that we'll catch an issue like this in the future.

**Comment by niboan** [comment]
Nice, thanks.
