### ISSUE TITLE
fab class conflict with fontawesome v5.x

### ISSUE THREAD

**Issue by FREEZX** [OnsenUI/OnsenUI#2491]
Hi,
I'm trying to use fontawesome with OnsenUI, but i'm having an issue with the .fab class. FontAwesome is using this class since v5.0, so whenever i try to insert an icon it takes the style of the onsen's fab button.

Here's a sample demonstrating the conflict: https://codepen.io/anon/pen/ejRYjg?&editors=101
Is there any possibility to rename the fab class? Perhaps ons-fab?

Thanks and best regards

**Comment by puku0x** [comment]
Thank you!
I'm trying to solve the problem!

**Comment by emccorson** [comment]
This issue should be fixed by #2502 for this specific case with `.fab`.

I think we'll need to look for a general way of avoiding these conflicts in the future. Possibly we could prefix all the classes with `ons-`, or maybe do `ons-fab .fab` like it is for the fix in #2502.

Any thoughts or suggestions about what direction we should take would be appreciated!
