### ISSUE TITLE
isIPhoneX()

### ISSUE THREAD

**Issue by grinmax** [OnsenUI/OnsenUI#2555]
isIPhoneX() - Returns whether the device is iPhone X.
What about Iphone XR, XS, XS Max?
Thanks!

**Comment by puku0x** [comment]
Hi @grinmax 

According to https://github.com/OnsenUI/OnsenUI/issues/2540 and https://github.com/OnsenUI/OnsenUI/pull/2545, `isIPhoneX()` returns `true` when the platform is iPhone X, Xr, Xs and Xs Max recently.

The updated API is available since Onsen UI v2.10.5.
https://github.com/OnsenUI/OnsenUI/blob/master/CHANGELOG.md

Cheers.

**Comment by grinmax** [comment]
@puku0x Thanks!
