### ISSUE TITLE
Core | Lazy-repeat issue: problems if ons-lazy-repeat inside a sized div

### ISSUE THREAD

**Issue by bobOnGitHub** [OnsenUI/OnsenUI#2561]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Firefox 62.0 on Windows 10 64-bit
```

__Encountered problem__
  
having various issues with ons-lazy-repeat when inside resized container divs - here is a basic one ; there are no scrollbars and the list is not the full height of its container ( which it defaults to when div removed / page is container ).

Example of what I'd expect is [here](https://codepen.io/bobongithub/pen/NOwLBL/) when done with plain ons-list-item(s)  ( with ons-lazy-repeat I'd expect the list to be the size of the container and have it's own scrollbars / the container's bars to not display ) 

__How to reproduce__
  

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<ons-page>
  <ons-toolbar>
    <div class="center">Lists</div>
  </ons-toolbar>

  <div id="listHolder" style="margin:2% 0px 0px 2%;overflow:auto;background:green;width:90%;height:50%">
    <ons-list>
      <ons-lazy-repeat id="infinite-list"></ons-lazy-repeat>
    </ons-list>
  </div>
  
</ons-page>
```

- __JS__

```javascript
ons.ready(function() {
  var infiniteList = document.getElementById('infinite-list');

  infiniteList.delegate = {
    createItemContent: function(i) {
      return ons.createElement('<ons-list-item >Item ' + i + '</ons-list-item>');
    },
    countItems: function() {
      return 20;
    }
  };

  infiniteList.refresh();
});
```

**Comment by wcmhc** [comment]
Container Height: `ons-lazy-repeat` inherits its height from its parent. Since `#listHolder` is set to 50%, `#infinite-list` inherits 50% and becomes half the height of its parent.
No scrollbar: OnsenUI hides scrollbars for the most part since that takes away from the mobile experience, and `ons-list` is no exception since it is a native-like component.

To overcome these issues, use CSS similar to this. If you do not want to use set pixel amounts, I would suggest having an outer wrapper at 50% height, and an inner wrapper at 100% height that contains the `ons-list` so that it inherits 100% of the parent height:
```css
<style>
  #listHolder {
    height: 200px;
  }
  
  #listHolder > ons-list {
    overflow-y: visible;
  }
</style>
```
