### ISSUE TITLE
Vue | Input issue: Ok/Enter does not submit form if more than one input

### ISSUE THREAD

**Issue by 4lyn** [OnsenUI/OnsenUI#2580]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  vue 2.4.1

[Framework binding]
 vue-onsenui latest

[Platform]
  Desktop - Linux 64-bit

[Browser]
  Desktop - Chrome 68.0.3440.106 on Linux 64-bit
```

__Encountered problem__
  
If a form contains more than one input, pressing Ok on mobile keyboard (or Enter on desktop) does not submit the form. It works if there is only one input in the form

__How to reproduce__
  
Just remove the password input and press Enter on the email input, the submit method is triggered

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<template id="main">
<v-ons-page>
  
  <form @submit.prevent="login" style="text-align: center; margin-top: 30px;">
    <p>
      <ons-input type="text" modifier="underbar" v-model="username" placeholder="Username" float></ons-input>
    </p>
    <p>
      <ons-input type="password" modifier="underbar" v-model="password" placeholder="Password" float></ons-input>
    </p>
  </form>
  
</v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
new Vue({
  el: '#app',
  template: '#main',
  data() {
    return {
      username: '',
      password: ''
    };
  },
  methods: {
    login(){
      this.$ons.notification.alert('Form submitted !');
    }
  }
});
```

**Comment by UnKnoWn-Consortium** [comment]
I have encountered the exact same problem.

**Comment by emccorson** [comment]
I think this is expected for behaviour for forms and not an Onsen UI problem.

On Firefox, pressing the return key in a form with a single input submits the form. If the form has multiple inputs, pressing return does not submit the form unless there is also a `button` or an `input type="submit"` in the form. Chrome appears to behave the same way.
https://stackoverflow.com/a/24690917

If you want to submit on the return key, your best bet is probably to add a `button`. You may also be able to do it by listening to the `keydown` event.

In any case, I'll close this now since it isn't an Onsen UI bug. If anyone thinks this should be the default behaviour in Onsen UI, please continue the discussion.

**Comment by UnKnoWn-Consortium** [comment]
Wait. It seems it does not work if the <ons-button> component is used instead. Indeed it works with the raw <button> element but not the <ons-button>. I think I will open another issue for it.

**Comment by emccorson** [comment]
@UnKnoWn-Consortium Good spot. Yes, `ons-button` probably should allow form submission like `button` does. The reason it doesn't currently is that `ons-button` does not wrap `button` (whereas `ons-input` _does_ wrap a regular `input`).
