### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Chromo0511** [OnsenUI/OnsenUI#2581]
__Environment__

Onsen UI Version: 

- 2.10.5
- 2.10.x

Framework:

- None

Framework binding:

- None

Additional libraries:

- None

Platform:

- Safari 12.0.1
- Chrome 70

__Encountered problem__

Memory leak on the navigator.
When you return to the previous page, a lot of components stay in memory.

__How to reproduce__

- Put this html file on your local machine, 
- Do heap snapshot
- Click on "Push page 2" 
- Click on the "Back button"
- Do another snapshot
- Compare the snapshot

You can repeat these operations many time, and the memory usage grow.

[page-sample.html](https://github.com/OnsenUI/OnsenUI/files/2569526/page-sample.txt)

Thanks for you help.

**Comment by wcmhc** [comment]
I can't seem to reproduce a memory leak with Chrome Version 68.0.3440.106 (Official Build) (64-bit), Chromium V8 6.8.275.26.

![profiler image](https://i.imgur.com/trx92c3.png)

I used your exact code plus a small script addition to cycle in and out of Page 2 which resulted in a 3MB fluctuation in the heap that was garbage collected fairly regularly with a mass collection near the start of the profiling. The flat line at the end corresponds to Chrome opening the captured profile, hence the large spike in CPU (not sure why that portion is included in the profiling timeline, but it's there). The timeline shows 70 seconds (70000ms on the timeline) of running which means 70 cycles of pushing and popping the navigator. My tests used the heap profiling tool in Chrome.

Extra code:
```html
<script>
setInterval(function() {
	myNavigator.pushPage('page1.html');
	setTimeout(function() {
		myNavigator.popPage();
	}, 500);
}, 1000);
</script>
```

Are you able to point me to a specific portion of the heap snapshot, otherwise?

**Comment by Chromo0511** [comment]
If you look your JS Heap that grow. Very light because it's a very small content. But if you have a more big content is really more significant.
If you make comparaison between 2 snapshots,  you can see a lot of nodes not released.
