### ISSUE TITLE
Vue | Don't have a method to access the mode property of the v-ons-splitter-side component

### ISSUE THREAD

**Issue by hidekatsu-izuno** [OnsenUI/OnsenUI#2597]
__Environment__

Onsen UI Version:
2.10.6
- 

Framework:
Vue 2.5.18
- 

Framework binding:
vue-onsenui 2.6.1
- 

Additional libraries:
None
- 

Platform:
Windows 10 Chrome
- 

__Encountered problem__

I want to get mode property of the v-ons-splitter-side. It's a readonly property.
FYI: https://onsen.io/v2/api/vue/v-ons-splitter-side.html

But update:mode event is not defined. Alternatively it has a modechange event.
The modechange event cannot get a initial value. So this event don't use to 
get a current collapsed state.

__How to reproduce__

I want to write the  following code. But we don't have a event like this.

```
<v-ons-splitter-side v-on:update:mode="$store.commit('menu/mode', $event)">
```

**Comment by emccorson** [comment]
I think what you want to do is have a two-way binding the splitter side's mode. You can't use v-model here because as you said the `update:mode` event does not exist, so instead you will need to use `v-bind` and `v-on`. If you use the `collapse` as the prop for `v-bind` and `modechange` as the event for `v-on`, you should be able to achieve the two-way binding.

I'm going to close this for now as specific support for `v-model` here is not something we will add at the moment, but if there is any further discussion I will look at re-opening.
