### ISSUE TITLE
ons-carousel breaks when ons-carousel-item too large

### ISSUE THREAD

**Issue by wonder75** [OnsenUI/OnsenUI#2639]
When adding too much content to an ons-carousel-item, the carousel breaks.
There seems to be a limit of about 5000 lines of HTML. I realized this problem, because
I am developing an app with many select and option fields.
When the limit is reached, the carousel breaks on current Chrome and Android. 

The carousel-items which follow the large item are displayed directly below the large item and
are not accessible via next() prev() or index() anymore.

Sorry wasn't able to autopost to Github from the playground, probably because the code is too large. I attached a file with the copyed and pasted code from the playground:

[carousel_item_too_large.txt](https://github.com/OnsenUI/OnsenUI/files/2981256/carousel_item_too_large.txt)

In this example the third carousel item isn't accessible anymore.

**Comment by wonder75** [comment]
Update: It really seems to be about the number of lines the HTML is consuming inside the container.
I removed the linebreaks in my form. A single very large line of invisible HTML seems to be no problem.

This is a workaround for me, but I guess it would still break for people who want to display large visible content inside a carousel-item.

**Comment by wonder75** [comment]
Sorry, but i need to *bump* this. Anyone there? :)

**Comment by emccorson** [comment]
@wonder75 Thanks for the detailed bug report :+1: 

Interestingly, I can still access the third item on Firefox 68, but not on Chrome 74. However, on both the first item gets shrunk but the whole page becomes as long as the longest page.

I'll look into it more this week.

**Comment by wonder75** [comment]
Thank you very much!

**Comment by wonder75** [comment]
Another friendly *bump*. Any news on this issue?

**Comment by emccorson** [comment]
@wonder75 
Sorry for the delay - when I said "I'll look into it more this week" perhaps I should have said "this year" :man_facepalming: 

Not fixed yet, but here's a little progress:

---

I can see three issues (using the playground carousel example for testing):

**1. When the second carousel item is too big, the third one can't be accessed.**

- This occurs for me on Chrome 74. However, I couldn't reproduce it on Firefox 68.
- If there are no line breaks in the carousel item's contents, the third item can be accessed. That's file line breaks (`\n`), *not* HTML lines breaks (`<br />`). If there are lots of `\n`s but no `<br />`s, the third item still can't be accessed.

**2. When the second carousel item is too big, the first and third items shrink, but the total height becomes as long as the second item.**

- This occurs for me on both Chrome 74 and Firefox 68.
- Because the first and third items shrink, the colour background doesn't fill the screen like it should.

**3. When the second carousel item is too big, the total height of the first and third items becomes as long as the second item.**

- This occurs for me on both Chrome 74 and Firefox 68.
- Because the total height increases for all carousel items, I can scroll down past the first and third items, which I shouldn't be allowed to do.

![Notice: blue area is too small; total height is too big (as indicated by scrollbar)](https://user-images.githubusercontent.com/13696952/65147121-57940e80-da15-11e9-8144-97fafddace1b.png)
*Notice: blue area is too small; total height is too big (as indicated by scrollbar)*.

[carousel_item_too_large_no_linebreaks.txt](https://github.com/OnsenUI/OnsenUI/files/3626288/carousel_item_too_large_no_linebreaks.txt)
*The same example as before but with no linebreaks. Copy into HTML half of [carousel example](https://onsen.io/playground/?framework=vanilla&category=reference&module=carousel) to reproduce.*

---

That's as far as I've got just now. I'll keep working on it but it might take some time to clear all three issues. If you have noticed anything I've missed, please let me know.

**Comment by maico910** [comment]
try this, add or edit this css, maybe will solve:

> ons-swiper-target > * {
>     overflow: auto;
> }

**Comment by wonder75** [comment]
@maico910 I added your suggestion to onsen.css but it did not fix the issue for me.

**Comment by wonder75** [comment]
Hello, does the @FIX label mean this issue is fixed now?

**Comment by emccorson** [comment]
@wonder75 Hey, sorry for the delay. I've had a chance to look into this a bit more.

(By the way, the FIX label just means the next action on this issue is to fix the bug i.e. I've already reproduced it and have enough information.)

Firstly, I was wrong about the `\n` characters mattering. Actually it looks like the carousel breaks with or without the new lines. It seems the only thing that matters is how much text is inside the carousel item.

I can still only reproduce the bug on Chrome, not on Firefox. Even then, the bug is intermittent on Chrome - sometimes the carousel works properly, but mostly it doesn't.

The actual bug is this:

Before the carousel is compiled, it is:

```html
<ons-carousel>
  <ons-carousel-item>Black</ons-carousel-item>
  <ons-carousel-item>Blablabla</ons-carousel-item>  <!-- lots of text in here -->
  <ons-carousel-item>Orange</ons-carousel-item>
</ons-carousel>
```

Then in the `_compile` method, it should get transformed. All of the `ons-carousel-item` child elements are supposed to go in `div.ons-swiper-target` so the result looks like:

```html
<ons-carousel>
  <div class="ons-swiper-target">
    <ons-carousel-item>Black</ons-carousel-item>
    <ons-carousel-item>Blablabla</ons-carousel-item>  <!-- lots of text in here -->
    <ons-carousel-item>Orange</ons-carousel-item>
  </div>
  <div class="ons-swiper-blocker"></div>
</ons-carousel>
```

But on Chrome occasionally the last carousel item does not get moved:

```html
<ons-carousel>
  <div class="ons-swiper-target">
    <ons-carousel-item>Black</ons-carousel-item>
    <ons-carousel-item>Blablabla</ons-carousel-item>  <!-- lots of text in here -->
  </div>
  <div class="ons-swiper-blocker"></div>
  <ons-carousel-item>Orange</ons-carousel-item>
</ons-carousel>
```

Furthermore, calling `this.childNodes.length` in the carousel's constructor (before `_compile` compiles the child elements into the two swiper divs) will return the wrong number of child elements in Chrome. It should be 3 but on the times where it breaks, it returns 2.

The upshot of all this is, this looks like a bug in Chrome and I'm not sure what the workaround is. Any suggestions would be helpful.
