### ISSUE TITLE
Some optimizations for OnsenUI core

### ISSUE THREAD

**Issue by devWaleed** [OnsenUI/OnsenUI#2642]
**Separating Components As Per Platform** 

I am guessing that when we build our apps, both Android/iOS components are baked into app which are used and determined on run time which style to show. 

Is it possible to separate components for Android and iOS ? So that if I am building an Android only app, it should only contain components (html, css, js, etc) for Android only and there should be no extra logic to determine theme. Wouldn't this reduce load time and rendering speed?

**OnsenUI core only!**

I think OnsenUI should only contain basic components having transitions, animations and structure with very minimal design. Material design and other styles should be a part of separate theme project.

Also we have 3 icon sets in OnsenUI, shouldn't they be a separate repository under OnsenUI as well to include icons? If I am using custom made icons or if I am using icons from icons8.com, for me those 3 icon sets built into the core are useless and introducing unwanted code.

**Comment by emccorson** [comment]
Separating the Android and iOS themes would speed up load time but I think the effect would only be marginal since most of the overhead is just extra CSS rules. The same goes for app size I would also guess. Benchmarking would need to be done to verify, but my feeling is the speed up would not be much.

There is already a version of Onsen UI without the fonts. Include `onsenui-core.css` in your project instead of `onsenui.css` to get Onsen UI without the fonts. There is also `onsenui-fonts.css` which contains _only_ the fonts. These files are included in each Onsen UI release.
