### ISSUE TITLE
Is it possible to remove unwanted section in mobile view?

### ISSUE THREAD

**Issue by limjinsun** [OnsenUI/OnsenUI#2672]
![IMG_0151](https://user-images.githubusercontent.com/11390856/61579067-17d5a700-aaf8-11e9-9b9c-6e994ae9edba.jpg)

Very top and bottom, I got this area not that I wanted to show to the user. 
Would it be possible to hide this?

Another website's this area is automatically hidden when you scroll. but Onsen UI is not.

**Comment by emccorson** [comment]
That's down to the browser, not Onsen UI. You need to look for a JS solution for that browser.

The area is probably not automatically hidden on scroll because it isn't the entire body that scrolls with an Onsen UI app, just the content area. That's just a guess, but it will depend on the browser.

If you have questions, you can try the community forum or the discord channel. Both are linked in the README.
