### ISSUE TITLE
Export the ESM modules in ES6 format with no transpilation/compilation

### ISSUE THREAD

**Issue by nik-christou** [OnsenUI/OnsenUI#2731]
First of all I would like to say thanks for all the effort that went into creating and maintaining this library. In my search it provides a missing piece in mobile web development and now with PWAs on the rise I suspect it will be used even more. 

I would like to ask if It is possible to have exported the web component elements in ES6 format instead of ES5. In my project everything is executed on the browser and I am using ES6 modules since all browsers have support for it. Also I believe it is recommended that when publishing Web Components to export the ES6 format elements so that consumers can apply their own building/bundling logic on top.

Right only the elements are transpiled/compiled into ES5 format and then exported. This is OK because of the need of maximum portability. However it should be very easy to also export in ES6 (since the elements are written in that way) and thus cover consumers that are targeting modern browsers.

**Comment by emccorson** [comment]
This sounds like a good idea.

Would you be able link to a library that already does this so I can see what the config is doing? @nik-christou

**Comment by nik-christou** [comment]
In general the guide from Justin Fagnani [https://justinfagnani.com/2019/11/01/how-to-publish-web-components-to-npm/](url) is a good way to ensure maximum usage by people/libraries.

As for a library I would recommend to have a look at [https://github.com/ing-bank/lion](url). If you manage to publish your elements in this way + keep the theming CSS files for mobile Android & iOS separate as you do now onsenui will be in a unique place in the community.

**Comment by emccorson** [comment]
I think this issue can be split into two separate parts:

**1. Distributing in ES6 instead of ES5**

From a quick glance, [support for ES6](https://kangax.github.io/compat-table/es6/) looks good enough to justify distributing only in ES6.

Before moving forward with this, we should double-check that ES6 is supported by: 1. all major browsers; 2. Android and iOS webviews (since a lot of our users use Cordova).

ES2017 as suggested in the Justin Fagnani article is not well supported enough at the moment on iOS.

**2. Distributing unflattened ES modules**

We currently distribute the ESM version by flattening the imports in `index.esm.js` (i.e. removing the import statements and inlining the imported code).

The question is whether we need to flatten the ESM version or not. I've been using the [Angular Package Format document](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#) as a reference for this. Angular packages are distributed as both flattened (FESM) and unflattened (ESM) ES modules. However, the `module` key in `package.json` points to the *flattened* version, for the following stated reason:

> As of webpack v4 the flattening of ES modules optimization should not be necessary for webpack users, and in fact theoretically we should be able to get better code-splitting without flattening of modules in webpack, but in practice we still see size regressions when using unflattened modules as input for webpack v4. This is why "module" and "es2015" package.json entries still point to fesm files. We are investigating this issue and expect that we'll switch the "module" and "es2015" package.json entry points to unflattened files when the size regression issue is resolved.

I suggest two possibilities:

1. Follow the Angular Package Format and distribute both flattened and unflattened versions. Once Angular stops distributing the flattened version, we will also stop.
2. Investigate further to find out why the flattened version works better, and whether this is also the case for webpack v5. I haven't been able to find an answer to that yet.

**Comment by emccorson** [comment]
Note to self when implementing this:

The way I think this should be done is to import all components into `index.esm.js` and then re-export them, the same was as `index.umd.js` currently does. That way we can simplify the syntax for importing components when using ES modules to something like:

```
import { page, toolbar, button, navigator } from 'onsenui'
```

One problem we will run into is getting tree shaking to work. Each component file contains the class defining the component and a call to `customElements.define` to register the component. The call to register the component is a side-effect, so just by importing the component, it will be registered. This means that it won't be tree shaken. However, if we set `"sideEffects": "false"` in package.json, the bundler _should_ tree shake the component if it is not imported. I will have to test whether this actually works in practice (with both rollup and webpack).
(Solution came from [here](https://stackoverflow.com/a/56552840/6413710).)

As far as I can tell there's no need to bother with bundling or flattening the ESM version because it's up to the library user to do what he wants with it.

**Comment by emccorson** [comment]
Related important comments: #2840

**Comment by emccorson** [comment]
Will be included in the next minor release `onsenui@2.12.0`.
