### ISSUE TITLE
Fastclick conflicts with WKWebView

### ISSUE THREAD

**Issue by JamalAPI** [OnsenUI/OnsenUI#2732]
FYI, FastClick was designed for use with UIWebView and is no longer needed with WKWebView, and the only way to stop it from interfering with button and hyperlink tap delay or not functioning is to use: 

```
ons.fastClick.destroy();

```
in oDeviceReady()

I suggest that owners of this library, create another branch that removes ALL FastClick code and call it OnsenMobile or OnsenFramework or any other meaningful name . This will keep current iOS AppStore installations that use  UIWebView working, reduce the code size, and prevent conflicts as explained above.

**Comment by nickredding** [comment]
I'm not seeing this. In fact, on my WKWebView apps removing fastClick makes my button response go from 50ms +/- to 100ms +/-. Here is my test button:
`
<ons-button tabindex="0" modifier="outline" id="clickspeedbutton" data-button="clickspeed" class="button button--outline">Click Speed<span id="clickspeedresult"></span> </ons-button>
`
And here is the supporting Javascript:
`
var clickStartTime;

function startClickTimer() {
    clickStartTime = new Date().getTime();
}

$('#clickspeedbutton')[0].ontouchstart = startClickTimer;

oxBindAnchorButton('clickspeed',
        function () {
            var elapsed = new Date().getTime() - clickStartTime;
            $('#clickspeedresult').html('&nbsp;&nbsp;&nbsp;' + elapsed + ' ms.');
            return false;
        });
`
FYI the function oxBindAnchorButton associates the function with the attribute data-button="clickspeed".

I haven't taken the time to investigate why fastClick delivers click events from taps twice as fast as without it, but there is little doubt from my testing.

**Comment by JamalAPI** [comment]
This nothing to with do with button clicks alone! It has to do with tap and double tap and the 300ms delay in UIWebView which FastClick tried to eliminate. Now, with WKWebView this not an issue and been resolved since iOS 9.3. 

More info here: https://cordova.apache.org/docs/en/latest/guide/next/index.html#2-performance-considerations.

Also, FastClick has other side effects when used with Google Address Auto Complete where input focus would not work unless some JavaScript hacks were implemented. In WKWebView, I don't have any issues with clicks or input focus.

We don't need another library that's not maintained and not needed anymore with WKWebView. If you want FastClick to still available to you, it should be a separate (detached) library that you can use at your risk. 

Quoting FT: 
"FastClick is developed by FT Labs, part of the Financial Times.

**Note: As of late 2015 most mobile browsers - notably Chrome and Safari - no longer have a 300ms touch delay, so fastclick offers no benefit on newer browsers, and risks introducing bugs into your application. Consider carefully whether you really need to use it.**" 

Source:
https://github.com/ftlabs/fastclick/blob/master/README.md

**Comment by nickredding** [comment]
I realize it it not just about button clicks. The purpose of my post was to illustrate how I test for the effect of fastClick.

I can confirm that on modern Android, fastClick makes no difference--the button tap response is consistently around 100ms with or without fastClick.

However, as I pointed out, with iOS and WKWebView the tap response is consistently around 50ms with fastClick and 100ms without fastClick. So fastClick is definitely not a "no-op" with WKWebView and frankly I'll take 50ms over 100ms every time.

In my experience the side effects with fastClick are few and far between, and it can easily be locally disabled by adding "no-fastclick" to an element class list. For iOS my vote would be to stick with it because I want my apps to be as snappy as possible.
