### ISSUE TITLE
document.querySelector("#myNavigator").pushPage("another_page.html"); works but $("#myNavigator").pushPage("another_page.html"); doesn't

### ISSUE THREAD

**Issue by BracerJack** [OnsenUI/OnsenUI#2817]
This probably have nothing to do with OnsenUI, I wonder how come JQuery's version doesn't work.

**Comment by emccorson** [comment]
I think you need to check if `$("#myNavigator")` is actually returning the correct object. I would guess not but we'll need a working sample to investigate further.

I'll close this since we don't support jQuery directly but discussion can continue here if there's more to add. If you want to provide a minimal working example I will debug it.
