### ISSUE TITLE
<div class="center"> works inside <ons-toolbar> but doesn't work for <p> inside main content area and also <div class="center"> inside <ons-toolbar> doesn't work in chrome/opera mobile browser, example file provided along with how to replicate it.

### ISSUE THREAD

**Issue by BracerJack** [OnsenUI/OnsenUI#2819]
[New folder.zip](https://github.com/OnsenUI/OnsenUI/files/5716290/New.folder.zip)
```
<ons-toolbar>
<div class="center">Main</div><!-- class="center" doesn't work for things inside the main content section -->
</ons-toolbar>

<p style="text-align:center">main</p><!-- Because class="center" doesn't work even though it works for content inside <ons-toolbar> -->
```
shouldn't ```<p class="center"></p>``` work in main content as well ? Because it presently doesn't, no big deal, just wondering about consistency of implementation.

Second issue: Copy the files into your mobile phone and navigate to it via file:///csdard/~ inside your mobile chrome/opera browser, you will notice that:
```
<ons-toolbar>
<div class="center">Main</div>
</ons-toolbar>
```
Isn't centered at all.

**Comment by emccorson** [comment]
The reason it doesn't work is just that the `ons-page` compilation process doesn't handle `div.center`. I don't think it's an oversight; I think it just wasn't part of the original spec. `ons-toolbar` does define a special `div.center` child element (which will be created as part of the compilation process if your don't already specify it), but `ons-page` does not. I think the reasoning is that a toolbar will always have a centre element for the title, but a page may not necessarily have anything centred.

Concerning the second mobile problem, this suggests that either `onsenui.js` or the CSS is not being loaded properly. This is most likely due to the method of opening the files or something specific to your device rather than a problem with Onsen UI.
