### ISSUE TITLE
Can't preload React component?

### ISSUE THREAD

**Issue by mark-night** [OnsenUI/OnsenUI#2833]
__Environment__

Onsen UI Version: 2.11.1

- 

Framework:

- 

Framework binding: react-onsenui 1.11.3

- 

Additional libraries:

- 

Platform:

- 

__Encountered problem__ 
Performance is a big issue when pushing page that request other pages (e.g. pushing a page that contains a tabbar...). The official guide recommends utilizing ons.preLoad() for the case. However, it looks like ons.preLoad() expects HTML file only? How do I preload React component (which does render a Ons.Page)? 

I read from the official documentation ( vanila js version ), there is another possible solution which utilizes <ons-navigator>'s bringPageTop() method, but how do I do this with React component? React Ref (ref prop is simply not implemented on Ons.Navigator) doesn't give me the DOM but rather an undocumented object which doesn't have the method at all. I guess I could call document.querySelector inside useEffect hook to do the job, but it really doesn't feel the like the React way... Besides, I tried playing with the method in browser dev tool, when calling bringPageTop(), animation has to be customized to give a pushing/popping feeling, but how do I customize animation? 

I might be raising too many questions, but the documentation is really missing too much information and it seems not all features have been implemented in React binding. Have being struggled with onsen-ui for a while, always feel exploring a maze. I had to keep guessing/testing to keep going, wasting too much time which should be avoided with a standard documentation. Is onsen-ui ready for React or not? 
 
I tried to post this in the community, where only registered user is allowed to post but couldn't find a entrance for registration.

__How to reproduce__

**Comment by emccorson** [comment]
What about using a general React solution instead of `ons.preload`? Something like `React.lazy` might work for your use case, as you could [lazy load](https://hackernoon.com/lazy-loading-and-preloading-components-in-react-16-6-804de091c82d) the content of the tab, while normally loading the tab itself. I don't have a lot of time to try this out right now, so if you do go ahead and try it, please let us know your results.

For `bringPageTop`, I just checked and it appears not to have been implemented in the React bindings for some reason. I created a new issue to track that (#2834).

The React bindings documentation could also do with improvement, as you said. It is on the list of things to do but not at the top of the priorities currently. If you would like to help improve it, feel free to discuss it here or create a PR.

By the way, you can still register on the forum, but you need to do it via Facebook, GtiHub etc. Click the Login button and choose one of the icons under Alternative Login.

Since this issue is mainly a question, I will close it.

**Comment by mark-night** [comment]
@emccorson Thanks for the response. It's OK to leave it closed. Just wanted to comment a little bit more.

If I'm understanding it correctly, `React.lazy` is to 'postpone' loading (load when needed) while `ons.preLoad` is to load before needed. The thing is, I need to have tab page loaded before navigator.pushPage() is called so when user get smooth slide in animation instead of waiting for background loading. I don't think they are the same case.
I managed to have tab pre-loaded by setting up `initialRouteStack` for navigator, it will only work if `bringPageTop` is available and pushing/popping animation could be customized...
