### ISSUE TITLE
Core |  issue: ionicons not rendering

### ISSUE THREAD

**Issue by Freedmores** [OnsenUI/OnsenUI#2890]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - OS X 10.15.7 64-bit

[Browser]
  Desktop - Chrome 90.0.4430.72 on OS X 10.15.7 64-bit
```

__Encountered problem__
  

__How to reproduce__
  

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<p style="text-align: center;">Run your project!</p>
<ons-icon icon="ion-home"></ons-icon>
```

- __JS__

```javascript
console.log('Run your project!');
```

**Comment by emccorson** [comment]
Onsen UI uses Ionicons v4 which uses a dfferent syntax. Instead of `ion-home`, you need `ion-ios-home` or `ion-md-home` to specify the platform (`ion-ios` for iOS, `ion-md` for Material).

I've just updated the examples with the new syntax:
https://onsen.io/playground/?framework=vanilla&category=reference&module=icon

Related: #2867
