### ISSUE TITLE
ReferenceError: Can't find variable: ons using requirejs with jquery and onsenui

### ISSUE THREAD

**Issue by zeshanb** [OnsenUI/OnsenUI#2935]
__Environment__

Onsen UI Version:
2.11.2
- 

Framework:
Cordova , jquery, and requirejs

- 

Framework binding:

- 

Additional libraries:
Jquery 3.6.0
- 

Platform:
iOS 14.5 , Safari Web Browser 14.1.2
- 

__Encountered problem__

ReferenceError: Can't find variable: ons

__How to reproduce__

1. Once you have npm installed and cordova

2. create app
cordova create onsenuieval org.apache.cordova.onsenuieval onsenuieval

3. add plugins
cordova plugins:
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-whitelist 1.3.5 "Whitelist"

Add plugins:
cordova plugins add cordova-plugin-device
cordova plugins add cordova-plugin-whitelist

4. Replace the www folder with the attached zip archive
[www.zip](https://github.com/OnsenUI/OnsenUI/files/7026374/www.zip)

5. add platform and run
For iOS cordova iOS 6.2.0:
cordova platform add ios && cordova platform build ios && cordova run ios

For browser:
cordova platform add browser && cordova build browser && cordova run browser

**Comment by emccorson** [comment]
As it currently is, this issue is not something I can look into, since it is a full project with multiple other libraries. It sounds like this is not a problem with Onsen UI and probably either a problem with your code or with jQuery/requirejs.

The `ons` variable is defined as soon as you have imported Onsen UI (or if using a script tag, as soon as the `onsenui.js` script has executed). You might try adding a `console.log` into `onsenui.js` to check it is actually being run.

I'll close this for now. If you are able to show that it is an Onsen UI problem and/or can recreate it in the [playground](https://onsen.io/playground/), I will reopen the issue. If you need general Onsen UI help you can try the [Discord](https://discord.gg/JWhBbnE).

**Comment by zeshanb** [comment]
Hi there,

Ons variable should load and it's not loading. The attached www zip archive is the simplest boilerplate configuration. 

Here is my requirejs config:

````
requirejs.config({
    baseUrl: 'js',
    paths: {
        // the left side is the module ID,
        // the right side is the path to
        // the jQuery file, relative to baseUrl.
        // Also, the path should NOT include
        // the '.js' file extension. This example
        // is using jQuery 1.9.0 located at
        // js/lib/jquery-1.9.0.js, relative to
        // the HTML page.
        
        jquery: 'jquery/jquery-3.6.0.min',
	onsenui: 'OnsenUI-dist-2.11.2/js/onsenui'
       
    }
});

//first require onsenui then jquery
requirejs(['jquery'], function($) {
    
    requirejs(['onsenui'], function(ons) {
        
        console.log("supposedly onsenui loaded");

                // Cordova APIs are ready
                document.addEventListener("deviceready", ondeviceready, false);

    }, function(error){
        
        var failedId = err.requireModules && err.requireModules[1];
        
        if (failedId === 'onsenui') {
            
            console.log("onsenui failed to load");
            
        }
        
    });

});

```

I've also tried loading onsenui before jquery. Onsenui loads except for the ons variable. Is there a reason why you are not allowing the ons variable to load?

Maybe the ons variable is tied to your propitiatory product and not required for other users.

Here is your documentation about the ons variable:

https://onsen.io/v2/api/js/ons.html

**Comment by emccorson** [comment]
I have no idea how requirejs works, but have you tried referencing
`window.ons`? In normal JS, Onsen UI registers `ons` as a global variable.
I don't know what the `ons` variable in your callback is supposed to be -
the default export?

**Comment by zeshanb** [comment]
Thank you, this must be a joke. The onsenui library's ons variable can't be found.

Seems to be buried in line 31125 to 31127:

````

// Add and register Custom Elements
setup(ons$1); // Setup initial listeners
window._superSecretOns = ons$1;

````

This was the issue. RequireJS wasn't the issue. Thank you and have a nice day.

**Comment by emccorson** [comment]
Onsen UI does define the super secret ons but it should also define
`window.ons` so if that is not defined then something is not loading
correctly.

**Comment by zeshanb** [comment]
I've verified by searching in onsenui v2.11.2 - 2021-01-12. 

````
window.ons
````

..is not defined anywhere in onsenui.js file.

````

// in lines 31125 to 31127
// Add and register Custom Elements
setup(ons$1); // Setup initial listeners
window._superSecretOns = ons$1;


````

Anyway, my issue is resolved. I'm grateful for your communication and appreciate the response to my case. Thank you, and have a delightful day.

**Comment by emccorson** [comment]
I've investigated this a bit more, and I was able to get Onsen UI mostly working with Requirejs. However, I did find one important bug which I'll detail below.

Firstly, `ons` _is_ defined in `onsenui.js`. The lines to look at are at the top of the file:

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.ons = factory());
```

In this case, `factory` is a function that returns `ons`. Requirejs uses AMD so `ons` is defined globally using the `define` function.

---

I used the following to get Onsen UI working with Requirejs:

```
// Project structure
.
├── index.html
├── main.js
├── onsenui.js
└── require.js
```

```html
// index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <script data-main="main" src="require.js"></script>
</head>
<body>
</body>
</html>
```

```js
// main.js
requirejs(["onsenui"], function(ons) {
  console.log(ons); // check your console to see that the ons object is logged
});
```

The only problem I had was that `ons.ready` does not work. That's because `ons.ready` waits for the `DOMContentLoaded` event but RequireJS loads Onsen UI _after_ `DOMContentLoaded` so `ons.ready` will never run its callback. I will file a bug for this, but in the meantime, you can safely use Onsen UI with RequireJS without using the `ons.ready` function as there is no need for it (everything should already be loaded by the time RequireJS loads Onsen UI).

Thanks for the report. It helped uncover a bug we probably wouldn't have seen otherwise.
