### ISSUE TITLE
the app crash when push a page that not exists

### ISSUE THREAD

**Issue by happyi** [OnsenUI/OnsenUI#2964]
__Environment__

Onsen UI Version:
v2.11.1
- 

Framework:
angularjs
1.4.7

Framework binding:
v1.0.0
- 

Platform:
all

use  ons-navigator  

1 :   push a a page that not exists  
 ```
     appNavigator.push('app/home/log.xml')
```
2:  then push or pop a normal  page  it get's

```
     framework.min.js:297 Uncaught (in promise) popPage is already running.
     framework.min.js:297 Uncaught (in promise) pushPage is already running.

```

it's look like crashed  by the end-user。

suggest：
      set a timeout let appNavigator return Initial State anyway

**Comment by emccorson** [comment]
I guess the fix here is to provide a better error message.
Although angularjs is mentioned in the issue, this is actually a problem with the core.

I have provided an example to reproduce that can be pasted in the playground.

```html
<ons-navigator swipeable id="myNavigator" page="page1.html"></ons-navigator>

<template id="page1.html">
  <ons-page id="page1">
    <ons-toolbar>
      <div class="center">Page 1</div>
    </ons-toolbar>

    <p>This is the first page.</p>

    <ons-button id="push-button">Push page</ons-button>
  </ons-page>
</template>
```

```javascript
document.addEventListener('init', function(event) {
  document.querySelector('#push-button').onclick = function() {
    document.querySelector('#myNavigator').pushPage('page2.html');
  };
});
```

**Comment by yong-asial** [comment]
@emccorson I'd like to attempt solving this issue. I am appreciated if you could point out where (related files) should i look at?

**Comment by emccorson** [comment]
@yong-asial Thanks for choosing this issue. The place to look is onsenui/esm/elements/ons-navigator.js, and specifically the `pushPage` function. That function calls the page loader to load the page, and I think an error is returned there when the page is not found.

You can also paste the example from my previous comment into onsen.io/playground and follow the stack trace in the console to find the source of the error.

I would adding that example to the `onsenui/examples` directory during development, then run `npm run serve` so you can see the problem locally. When you edit `ons-navigator.js` it should reload the examples.

Also needed would be to add a unit test to `ons-navigator.spec.js`.

Good luck!

**Comment by yong-asial** [comment]
@emccorson Thank you. 

The example in `onsenui/examples/navigator/index.html` trigger the code here https://github.com/OnsenUI/OnsenUI/blob/master/onsenui/esm/elements/ons-navigator.js#L622. In this case, it set `this._isRunning = false` so everything is working fine.

However, maybe in some other case, where the code triggered here (`options.pageHTML is true`) - https://github.com/OnsenUI/OnsenUI/blob/master/onsenui/esm/elements/ons-navigator.js#L613 and the page is not existed, it doesn't set `this._isRunning = false` -> that's why we have problem.

How can i mimics this behavior (`options.pageHTML is true`)?

**Comment by yong-asial** [comment]
@happyi  I could not reproduce the incident that you are experiencing. If the page is not existed, it "does" throws the error, but i still can push the "exist" page or pop the page. Could you provide us more detail how to reproduce this?

=========================

@emccorson When the page is not existed, it will first set  `this._isRunning = false;` and throw the error at here https://github.com/OnsenUI/OnsenUI/blob/master/onsenui/esm/elements/ons-navigator.js#L627.

The next time, the `_pushPage` function is called, the `this._isRunning` is `false` and this condition is not true https://github.com/OnsenUI/OnsenUI/blob/master/onsenui/esm/elements/ons-navigator.js#L634.

However, in user's case, they said they got the error when trying to push another "exist" page - which means `this._isRunning` is still `true` somehow.
```
framework.min.js:297 Uncaught (in promise) pushPage is already running.
```

**Comment by emccorson** [comment]
I just looked more closely and it appears that `pushPage` is still allowed even if it has already thrown an error. In that case, this user's issue is not reproducible (I guess I misunderstood in my example above).

The only work to be done for this issue if it can't be reproduced is to improve the error message, since at the moment it throws a bunch of unhelpful HTML. If you can do that I can merge and mark this as fixed. @yong-asial
