### ISSUE TITLE
npm run test:react failed.

### ISSUE THREAD

**Issue by yong-asial** [OnsenUI/OnsenUI#3019]
[test_react.log](https://github.com/OnsenUI/OnsenUI/files/9622576/test_react.log)

**Comment by emccorson** [comment]
The React tests are currently not expected to work.

During the upgrade to (I think) React 17, I completely reworked the React bindings and the development environment. This included using create-react-app for the React examples app, which also specified its own testing setup. I removed these in c94b84daf because they were causing dependency conflicts with Vue.

The React unit tests are actually not that useful currently, since they just check that the core component is rendered.

Instead of trying to get the current tests to work, I think we need to use the standard React testing setup specified by create-react-app (I think specifically this is set by the react-scripts dependency) and write tests that are more useful.

This is a bigger issue than I will be able to do this month, so I will add it to the React label and it should be done as part of #3008.

**Comment by yong-asial** [comment]
@emccorson Yes, i created the issue here (instead of jira) to properly track the status.
