### ISSUE TITLE
Distribution repository has not latest version

### ISSUE THREAD

**Issue by rev111** [OnsenUI/OnsenUI#3039]
Onsen UI Version: 
- 2.12.6

I download Onsen from the distribution builds (https://github.com/OnsenUI/OnsenUI-dist/releases) and save / reference it locally.
The last distribution build is 2.11.2 and > 18 months old.

I would like to try 2.12.6, there are issues with a PWA which I hope might be fixed in there.
Are there any plans to update the distribution build? 

I see the latest version is on CDN, however it's not grouped in a dist folder to download. I learned from other experiences that downloading single files from a CDN can be tedious.

**Comment by yong-asial** [comment]
Hi @rev111 

The repo https://github.com/OnsenUI/OnsenUI-dist/releases is currently under the discussion of being archive or not. That's why we haven't updated the repo since the version 2.11.2 as you said.

Anyway, if you want to download the latest onsenui in zip file. You can do so by navigating to this url https://onsen.io/v2/guide/installation.html and click on "Download Onsen UI (Version 2.12.6)". It will then download the latest onsenui files in zip file.

In addition, if you would like to download the previous version, you can navigate to this url - https://registry.npmjs.org/onsenui/-/onsenui-2.12.6.tgz. Please replace the version `2.12.6` with any version you wish to download.

**Comment by rev111** [comment]
Thanks, I downloaded the latest version (as tar.gz) from here:
https://onsen.io/v2/guide/installation.html
