### ISSUE TITLE
ONSEN UI via cdn issue ? my ui in web its break today ?

### ISSUE THREAD

**Issue by Dfaw17** [OnsenUI/OnsenUI#3079]
<img width="1450" alt="image" src="https://github.com/OnsenUI/OnsenUI/assets/79698509/f5fc8ce9-9e04-4181-9370-a8e86edd6e51">

**Comment by takuyaW** [comment]
Thank you for your report. We're pleased to inform you that the CDN has been restored and is now functioning normally.

We apologize for any inconvenience caused by the issue with the Onsen UI CDN. It should now be available for use as usual. If you continue to experience any problems, please don't hesitate to let us know.

We appreciate your understanding and cooperation.
