### ISSUE TITLE
How to pushPage with tab-bar without losing the tab-bar / blink bug

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#384]
Hi @argelius,

I don't know if it is a bug or maybe I did something wrong, but how could I actually keep the tab bar visible when I do a pushPage inside a tab-view.html?

```
<ons-page ng-controller="TabBarController">

    <ons-tabbar animation="fade" keepPage="true" var="roottab">
        <ons-tab page="neighbor.html" label="" active="true">
            <ons-icon icon="ion-map" class="tab-icon"></ons-icon>
        </ons-tab>

        <ons-tab page="gossip.html" label="">
            <ons-icon icon="ion-planet" class="tab-icon"></ons-icon>
        </ons-tab>

        <ons-tab page="chatrooms.html" label="">
            <div class="notification reply-notification"></div>
            <ons-icon icon="ion-chatbubbles" class="tab-icon"></ons-icon>
        </ons-tab>

        <ons-tab page="tab-news.html" label="">
            <div class="notification earth-notification"></div>
            <ons-icon icon="ion-earth" class="tab-icon"></ons-icon>
        </ons-tab>
    </ons-tabbar>

</ons-page>
```

This is for example my tab-bar.html page. I open this page also with a pushPage, but when I make a pushPage inside neighbor.html, it works, but will not be inside of that tab - instead, it will be over the tab-bar. What do I have to do? Is this expected?

**Comment by Hirbod** [comment]
Hi @argelius,

any update?

**Comment by knanasugi** [comment]
Hi @Hirbod,

I had been tackling the same problem, although my program had only one ons-navigator.
My bug was caused by ons-toolbar put in the same hierarchy as ons-navigator.
I put the toolbar in upper hierarchy (the same as ons-tabbar), and the program worked fine.
If you use ons-toolbar with navigator, this might help you in some way.

**Comment by knanasugi** [comment]
I forgot to say that you need to modify css of .tab-bar__content or some elements if you put any elements out of ons-tabbar.

**Comment by Hirbod** [comment]
Could you share your CDs modifications with me? Thanks

**Comment by knanasugi** [comment]
ons-toolbar (.navigation-bar) 's height is defined as 44px by default, so this will work.
<pre>
.tab-bar__content{
  top: 44px;
}
</pre>
Plus you may have to keep extra 20px height for iOS status bar area.
So something like below or more styling will be needed.
<pre>
.navigation-bar, .navigation-bar__item, .navigation-bar__left, .navigation-bar__right, .navigation-bar__center{
  height: 64px;
}
</pre>

**Comment by knanasugi** [comment]
Ah, this will be needed, too.
<pre>
.page{
  top: 64px;
}
</pre>

**Comment by knanasugi** [comment]
About page initialization, I have a solution. You can use angular's `run` block and `ng-if` directive.
<pre><code>angular.module('app', ['onsen'])
.run(function($rootScope){

  var obj = {};
  /* some initializing prosess */
  $rootScope.someData = obj;

});
</code></pre>
<pre><code>
&lt;ons-page ng-if="! someData"&gt;

  Contents During Initialization

&lt;/ons-page&gt;
&lt;ons-tabbar ng-if="someData" animation="fade" keepPage="true" var="roottab"&gt;
        &lt;ons-tab page="neighbor.html" label="" active="true"&gt;
            &lt;ons-icon icon="ion-map" class="tab-icon"&gt;&lt;/ons-icon&gt;
        &lt;/ons-tab&gt;

        &lt;ons-tab page="gossip.html" label=""&gt;
            &lt;ons-icon icon="ion-planet" class="tab-icon"&gt;&lt;/ons-icon&gt;
        &lt;/ons-tab&gt;

        &lt;ons-tab page="chatrooms.html" label=""&gt;
            &lt;div class="notification reply-notification"&gt;&lt;/div&gt;
            &lt;ons-icon icon="ion-chatbubbles" class="tab-icon"&gt;&lt;/ons-icon&gt;
        &lt;/ons-tab&gt;

        &lt;ons-tab page="tab-news.html" label=""&gt;
            &lt;div class="notification earth-notification"&gt;&lt;/div&gt;
            &lt;ons-icon icon="ion-earth" class="tab-icon"&gt;&lt;/ons-icon&gt;
        &lt;/ons-tab&gt;
&lt;/ons-tabbar&gt;
</code></pre>

`$rootScope.someData` should be an object, instead of a primitive, that assures the initialization has completed, because of the nature of prototype chain. I usually assign `user` data of the app to it.

**Comment by knanasugi** [comment]
Hi @Hirbod,

I think I finally found the cause. What caused the blink were nested `<ons-page>`s, I suppose. After long struggling, I found my code had nested `<ons-page>`s. Then I straightened my DOM structure, removing the nest, and the ugly blink bug finally dissapeared. OnsenUI doesn't seem to allow nested `<ons-page>`s after all. Your code apparently has nested `<ons-page>`s, so try removing it. I hope you will find it working.
