### ISSUE TITLE
Trouble in ons-split-view and ons-navigator

### ISSUE THREAD

**Issue by Sakura777** [OnsenUI/OnsenUI#539]
I use together ons-split-view and ons-navigator.
It is like "Setting" app in iPad, main page of ons-split-view include ons-navigator.
So I have 2 trouble.

1. Page don't move in IE 11 (Windows 7).
When pushpage in ons-navigator, can't show new page. I can success Firefox, Chrome, iOS and Android.

2. Slide animation is terrible.
When pushpage and poppage in ons-navigator, I set animation "slide".
It success to play animation, but old content move to over the left menu.

Can I fix this? Please help me.

**Comment by argelius** [comment]
Hi @Sakura777!

Please make a minimal code example and we will check it out.

You can fork one of our codepen examples:
http://codepen.io/onsen/

**Comment by danjarvis** [comment]
So I noticed the second issue a few weeks ago after upgrading to Onsen v1.2.2

I commented on [this commit](https://github.com/OnsenUI/OnsenUI/commit/4161934bb7ebca5e80dfae14a1652efc734926ac#commitcomment-10323911) to get more details, because the CSS change is what causes the overlap when using ons-navigator with split-view.

As mentioned in the comment, you can work around this by using the following CSS:

```css
.onsen-split-view__main {
    overflow: hidden !important;
}
```

Forked example [here](http://codepen.io/danjarvis/pen/wBOYYy).

**Comment by argelius** [comment]
Thanks @danjarvis !

We'll fix this. Since it's only an issue in the horizontal direction we will add overflow-x rule. I'll also ask why the change was made in the first place but it was a long time ago so there's a chance he's forgotten :)

**Comment by argelius** [comment]
@danjarvis I moved this issue:

https://github.com/OnsenUI/OnsenUI/issues/552

We will fix it now.

**Comment by andipavllo** [comment]
#552 fixed
