### ISSUE TITLE
Ons Gesture Detection with HammerJS Included indivudually 

### ISSUE THREAD

**Issue by Kianenigma** [OnsenUI/OnsenUI#561]
I have a Complex Page With multi Sub pages / modals and i used hamme.JS Manager to handle touch events ( i did know know about ons-gesture-detection> at the time ) and now i realized something . any ons action regarding touch events won't work if i include Hamme.Js after onsenui_all.js ( sliding menu swipe / Carousel and .. ) . and i tried to re write my Hamme.Js Code with ons but had no luck . example of trying to catch touch events on an entire page : 

```
<ons-gesture-detector>
        <ons-page id="drawPage" var="drawPage">
           <div id="gesture">
                  .... 
           </div>
    </ons-page>
</ons-gesture-detector>

$(document).on('pan', '#gesture', function(ev) { 
}) 
```

**Comment by argelius** [comment]
Hi @Kianp !

We're using Hammer for touch events in Onsen UI so it's already loaded, however it's an older version so it looks like the one you're using isn't compatible.

Does it work well if you remove your Hammer import?

We will upgrade to the latest version of Hammer pretty soon.

**Comment by Kianp** [comment]
Hi @argelius , Thanks for the quick Response ! 

What You Said Seems right because Simple Hammer Functionality is available but something line Hamme.Manager isn't . 
Yes as soon as i include the latest Hamme.JS all gesture detections ( like sliding menu open / close )  won't work and some errors appear in the console  . 

So far what solved the problem was to not include any version of hammer , 
use the <gesture-detection> ons tag ( which probably works fine but i didn't try it myself ) 
or 
Create an instance of The Built-in Hammer Object and use it ( the only downside is that if you look at Hammer.gestures or peek the event object you'll find out that many types of gestures like swipe , pinch or pan aren't defined initially and should be detected from a more global event type named "gesture" )
```
var hm = Hammer(document.body); // or any other HTML Element 
hm.on("gesture", function (ev) {
    console.log(ev)
    // ... 
}) 
```

**Comment by DudeNamedBen** [comment]
Another way to solve the issue is to rename the new version of Hammer to for example NewHammer that solves the name conflict and both libraries work as expected. This is also very simple to do because the name is only defined once at the end of the minified Hammer.js file.
