### ISSUE TITLE
ons-tabbar

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#614]
With the latest master version ons-tabbar is not working anymore. The template pages are not found. 
I used the latest master, built onsen and then served to checkout the examples.

Hope this can be fixed easily. Thanks for your awesome work!

**Comment by argelius** [comment]
Hi @d3orn!

We'll take a look at it. I think there is an issue with `<ons-template>` since we started using the Web Components API.

**Comment by d3orn** [comment]
Hi @argelius!
Thanks, I figured as much, tell me if I can help somehow (and where to look)

**Comment by argelius** [comment]
Hi @d3orn !

The reason why it isn't working is that the Web Component's `createdCallback` method is executed after the AngularJS directive.

Directive: https://github.com/OnsenUI/OnsenUI/blob/master/framework/directives/template.js
Web component: https://github.com/OnsenUI/OnsenUI/blob/master/core/elements/ons-template.es6

I'm not really sure where the bug is, but the Web Component should execute first since it's a low level API.

**Comment by argelius** [comment]
@d3orn 
I tried to solve this in a nice way but discovered some pretty big inconsistencies.

* AngularJS directives are compiled before Custom Elements when using the CustomElements.js polyfill.
* When using `angular.bootstrap()` or (`ons.bootstrap()`) the order is reversed.
* `document.registerElement` is a lower level API (at least that's my feeling) so I think it should execute before Angular directives.
* Even worse, in the native implementation in Google Chrome the timing is _random_ (!!!) so there's no way to know which one comes first...

Seems like this is fixed in Canary but right now it doesn't work very well. I've reverted it somewhat so in the case where the Custom Element hasn't been executed yet it will do like it did before. This solution is far from optimal thouch... :(

**Comment by d3orn** [comment]
@argelius Yeah I just tested it on iOS (works fine) but Android still has the error. Is there a way to implement this without using ons-template? We are currently using 2 templates for tabbar and 1 for dialog.

**Comment by argelius** [comment]
You can use the $templateCache service directly.

Do $templateCache.put('page.html', htmlContent). I'll see why it doesn't work on Android tomorrow. 

Sorry for the inconvenience, we're making a lot of big changes right now so things are bound to break. :)
