### ISSUE TITLE
The function configureItemScope() of ons-lazy-repeat seem not correct

### ISSUE THREAD

**Issue by zack24q** [OnsenUI/OnsenUI#680]
Hi, it's me again, I found the function configureItemScope() will run 3 times for each item when I first open the page [onsen docs code] (http://codepen.io/onsen/pen/QwrGBm), and I haven't scroll the list. When I scroll the list, the function configureItemScope() will run more than once for each item too.

**Comment by zack24q** [comment]
It is very strange, in my friend's browser it is correct. my os is windows and he is Mac os, we are both ues chrome to open those codepen.

**Comment by argelius** [comment]
Thanks @zack24q ! It should only execute once for every item so we will investigate this issue.

**Comment by filipefreitas82** [comment]
Hi

I have noticed the same behaviour.

And this maybe the cause for my recent post:
http://stackoverflow.com/questions/30872723/lazy-repeat-calculateitemheight-index-is-always-undefined

**Comment by argelius** [comment]
Hi @filipefreitas82 !

The issue in your post was due to a bug. It has been fixed so it should work in the next version.

**Comment by filipefreitas82** [comment]
@argelius thanks.
We are updating our 1 year old onsen code to the new one.
Is there any workaround I can use until the next version comes out?

**Comment by filipefreitas82** [comment]
I downloaded the latest branch from github. It is fixed there.

**Comment by filipefreitas82** [comment]
@argelius Any info on this?

Right now for my app to work I need to comment out the modal:
<ons-modal var="synchingModal">
            <ons-icon icon="ion-load-c" spin="true"></ons-icon>
</ons-modal>

**Comment by argelius** [comment]
Hi @filipefreitas82 ! I think this happens because of a bug in the native implementation of Web Components in Chrome.

Are you using Chrome?
Before loading `onsenui.js`, please try adding the following code in a script tag:

```javascript
document.registerElement = undefined;
```

This will override the native implementation and instead use a polyfill to implement the Custom Element API.

Actually, right now there are some bugs in Chrome that makes custom elements incompatible with AngularJS. We will probably add this line by default until we are happy with the native implementation.

**Comment by filipefreitas82** [comment]
@argelius yes, I'm using Chrome for testing (cordova run browser), it works on safari.

I added the code you suggested and it works.

thanks again.
