### ISSUE TITLE
Docs are not well for new User

### ISSUE THREAD

**Issue by DILEEP-YADAV** [OnsenUI/OnsenUI#682]
Onsen ui Docs are very confusing for new user, Because content or source code demo is not as per Version wise. Please provide Docs as per version of Onsen ui ,
 I agree , speed of app is very fast in comparing  to another, Please improve docs.

**Comment by argelius** [comment]
Thanks @DILEEP-YADAV !

We will try making the docs better. Please tell us where it's incorrect and we will fix it. Also, since this is an open source project please feel free to fix it yourself.

The docs are generated from comments in the `framework/` directory.

You can also change the guide in the website repo:
https://github.com/OnsenUI/onsen.io

**Comment by DILEEP-YADAV** [comment]
ok ! I will try my level best to Improve Docs, Because Docs is very important part of any successful Project. 

Thank to Reply     @argelius
