### ISSUE TITLE
Onsen 2 demo not working

### ISSUE THREAD

**Issue by 3zzy** [OnsenUI/OnsenUI#859]
I checked out the master branch, and trying to run the demo (http://localhost/ebook/v3/OnsenUI/demo/index.html), but I get this:

<img width="718" alt="screen shot 2015-08-20 at 7 02 37 pm" src="https://cloud.githubusercontent.com/assets/105034/9384429/1051b146-476e-11e5-9903-ce689c81270b.png">

**Comment by frankdiox** [comment]
@3zzy  Those errors are due to a bug in Chrome related to CustomElements implementation. You can add `document.registerElement = undefined;` at the beginning of `core/vendor/CustomElements.js` to force using the polyfill.

**Comment by 3zzy** [comment]
Did that, still the same because I don't even see
core/vendor/CustomElements.js being loaded.

**Comment by 3zzy** [comment]
Ok, got the demos working somehow, but its still all angular? I thought version 2 (master) allowed choosing between jQuery and Angular?

**Comment by frankdiox** [comment]
@3zzy You are allowed to use jQuery or Angular also with Onsen 1.x. The demos are made with AngularJS but they are just that, demos.

Plus, master branch is not "Onsen 2.0" yet. We are porting the elements to WebComponents and preparing everything.

**Comment by 3zzy** [comment]
Allowed to use jQuery ofcourse, but its not either-or, everything is still
based on Angular and one needs to know Angular to use Onsen, right?

**Comment by frankdiox** [comment]
Onsen UI 1.x is based internally on AngularJS to create the elements but it is not compulsory to use AngularJS in actual apps, you can use jQuery or pure JavaScript **instead**. Onsen 2.0 will be based on WebComponents instead of AngularJS, and of course it's not necessary to use AngularJS in apps either.
The reason why you see so much AngularJS in master branch is that we are providing AngularJS directives and stuff for those who want to use AngularJS (like we will provide in the future for Angular 2.0 and hopefully other frameworks), but you can just ignore those and use jQuery or pure JavaScript instead as I mentioned before.
