### ISSUE TITLE
ons-lazy-repeat not refreshing if it's data changes

### ISSUE THREAD

**Issue by JoaoSaleiro** [OnsenUI/OnsenUI#866]
Hello,

the ons-lazy-repeat seems to have a terrible bug that we're not being able to workaround. 

If the list that the Delegate is using is replaced by a new version, the ons-list doesn't refresh.

In other words:

``` js
$scope.MyDelegate = {
    configureItemScope : function(index, itemScope) {
        itemScope.item = {
          name: $scope.data[index]
        };
    },
    calculateItemHeight : function(index) {
      return 45;
    },
    countItems : function() {
      return $scope.data.length;
    }
  };
```

If $scope.data changes to a different array (due to the user filtering data, or a change in the data), the ons-list doesn't refresh.

The problem here is that this is a very common scenario even in simple applications in case the user needs to filter data, or the edit of an item forces a full refresh to the list.

We're not being able to workaround this, and our app should be released before Saturday GMT. This is the only bug missing to close the release...
Any suggestion?

Thanks

**Comment by frankdiox** [comment]
@JoaoSaleiro Hello! I think I know where your problem is.

Do you have primitive values in `$scope.data[index]`? Because those are copied "by value" and not "by reference" in JavaScript, as I'm sure you know. So basically I guess you are updating the internal object `$scope.data` but the view cannot be updated since nothing changes there. The immediate workaround is to use objects instead of primitive values, so everything will be updated at the same time.

I have made an example here where you can modify a specific item (second index of every carousel element) or swap the whole array (toolbar button): http://codepen.io/frankdiox/pen/JYPMOM
I think those are the two different possibilities you may face.

Does this fix the terrible bug or there is something else?
Good luck with the release :)

**Comment by zhuangperola** [comment]
@frankdiox

I have checked this problem and you source code, it does not work in my local environment.

I reviewed the codes in LazyRepeatView and found codes which I think has a syntax bug like below .

`this._scope.$watch(this._countItems.bind(this), this._onChange.bind(this))`

I changed it to
 `this._scope.$watch(this._onChange.bind(this)), this._scope.$watch(this._onChange.bind(this))`

and it works. Could you have a check of this problem.

I found this bug is carried in since the release of 1.3.4. (1.3.2 is OK)

**Comment by tfutada** [comment]
I am not sure this is the right place to ask this, but i am hitting the same issue, as @frankdiox mentioned, a LazyRepeatView won't be refreshed unless the number of the items has changed.
say, in the code at http://codepen.io/frankdiox/pen/epOyPR,
if i tweak the size of the first array from 50 to 26, it does not seem to work.
Is it supposed to be so or will be fixed in the future?

`  $scope.myArrayFilters[0] = [];
  var i;
  for (i = 0; i < 26; i++) {
   	$scope.myArrayFilters[0].push({content: i});
  }

  $scope.myArrayFilters[1] = [];
  for (i = 0; i < 26; i++) {
    $scope.myArrayFilters[1].push({content: String.fromCharCode(97 + i)});
  }`

**Comment by nao0515ki** [comment]
Thanks @frankdiox  !!
your code works for me.

it was really helpful.
http://codepen.io/frankdiox/pen/epOyPR
