### ISSUE TITLE
JS cannot work in <ons-carousel-cover>

### ISSUE THREAD

**Issue by ryokanoshoh** [OnsenUI/OnsenUI#888]
I created this ons-tag.

`<ons-carousel-cover>
    <ons-button modifier="quiet" onclick="alert('prev');" style="color: #FFFFFF;">
        <ons-icon icon="ion-ios-arrow-left" size="40px" var="prevpage" fixed-width="true"></ons-icon>
    </ons-button>
</ons-carousel-cover>`

But I cannot work JS called onclick.
If it have solve the problem, please let me know.

**Comment by frankdiox** [comment]
Looks like `<ons-carousel-cover>` has `pointer-events: none;`, so it can never be the target of mouse events. This is automatically inherited by its children, like the button you have inside. It is set like this because  `<ons-carousel-cover>` is a layer over the whole carousel element, what means that is also over  `<ons-carousel-item>`s and it would avoid clicks on them otherwise.

The easiest workaround is preventing the mentioned inheritance by just adding `pointer-events: auto;` to the button or anything inside `<ons-carousel-cover>`.

You can play with `pointer-events` value (`none` and `auto`) here: http://codepen.io/frankdiox/pen/gaaLbK

Check the CSS for `.cover-label` and `ons-carousel-cover`. Notice the `onmousedown="event.stopPropagation()"` in the button, perhaps that's useful for you.

@argelius Do you think we should change this somehow?

**Comment by ryokanoshoh** [comment]
@frankdiox 
Thank you for answer and explain me my question.
I understand about `<ons-carousel-cover>`

**Comment by frankdiox** [comment]
@ryokanoshoh You are welcome :)

Perhaps we can add this:
```
ons-carousel-cover > * {
  pointer-events: auto;
}
```
