### ISSUE TITLE
Since iOS 9, statusbar push down is buggy

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#950]
Hi,

since iOS 9, the auto tabbar pushdown is buggy somehow. I can't provide any scenario, cause it works sometimes, and sometimes not. After some tabchanges and pushes, my content (which was fine before) is -20px behind the tab-bar. Same works perfectly on iOS8. Since iOS 9, I faced some timing issues generally.

The bug is reproducable on iOS 9.0.2 with iPhone 6 (real device) and Simulator

**Comment by Hirbod** [comment]
#897 could be related @argelius (I've also seen this effect from time to time, but in my case, the "push" won't even fire delayed anymore)

**Comment by Hirbod** [comment]
@anatoo @argelius iOS 9 has a broken tilde (~) selector, which will cause a lot of problems

.page__status-bar-fill ~ ons-toolbar
.page__status-bar-fill ~ ons-toolbar ~ .page__content

this cause some problems like this. After I change just one attribute in safari, it will redraw. We need an urgent fix for this. Ionic had fixes for iOS 9 out where it was still in beta...

![img_5061](https://cloud.githubusercontent.com/assets/504909/10531504/d4b65d3c-73b2-11e5-91c2-5ce316d0cf71.PNG)

**Comment by argelius** [comment]
Hi @Hirbod !

I would love to fix this bug but I can't find any way to reproduce it. I've made some sample apps with tabs, navigators, menus but to no avail.

However, looking at the behavior of your app I can at least guess what's going on.

I need to know some things. Can you inspect the page and see what rules are in place?
I want to know the `top` value of the `.page__content` class and its `paddingTop` value.

There are three rules that should affect the element:

```css
.page__status-bar-fill ~ ons-toolbar ~ .page__content {
    top: 64px;
    padding-top: 0px;
}

.page__status-bar-fill ~ .page__content {
    padding-top: 20px;
}

ons-toolbar ~ .page__content {
    top: 44px;
}
```

It looks like when your bug is triggered the first two rules are not working while the third one is, since it's still pushed down 44px.

Let's try patching it by using adjacent sibling selectors instead:

```
.page__status-bar-fill + ons-toolbar + .page__background + .page__content {
  top: 64px;
  padding-top: 0px;
}

.page__status-bar-fill + .page__background + .page__content {
  padding-top: 20px;
}
```

Could you please try these rules? If they work fine I will add them and release a new version since this is a pretty big deal.

**Comment by Hirbod** [comment]
Hi @argelius ,

yes, the bug is fixed. Wish you had wrote me 30 minutes before, now I've pushed a buggy app to the appstore (with expedited review). Haha..

**Comment by argelius** [comment]
@Hirbod Sorry for the slow response time. Just woke up a few hours ago. :)

Since the adjacent sibling selectors seem to work, I will release a version that implements these changes.

**Comment by Hirbod** [comment]
:+1: - no problem. At least the bug is fixed, you should change every single ~ selector. It just don't work as expected on iOS9

**Comment by argelius** [comment]
@Hirbod: I will change the other ~ selectors as well. Thanks a lot for the assistance! :)
